<style>
    div.limit_last {
        float: right;
        height: 22px;
        line-height: 22px;
        margin: 0 10px;
    }
</style>
<?php
$limit = array(
		5=>'5',
		10=>'10',
		15=>'15',
		20=>'20',
		25=>'25',
		30=>'30',
		50=>'50',
		100=>'100',
		200=>'Tất cả'
);
$idPage = "page".rand();
$selectItem = $this->itemCountPerPage;
$flag = false;
foreach ($limit as $k =>$v){
	if($selectItem==$k){
		$flag = true;
		break;
	}
}
$width='width:60px;';
if(!$flag){
	$selectItem = 20;
}
if($selectItem > 100){
	$selectItem = 200;// chon tat ca
        $width='width:80px;';
}
?>
<ul>
	
        <?php if($selectItem!=200){?>
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
        <li class="pg-first"><a onclick='javascript: jQuery("#<?php echo $idPage; ?>").val("<?php echo $this->first; ?>");jQuery(this).parents("form").submit();return false;' href="#" title="Trang đầu">&Lt;</a></li>
        <?php else: ?>
			<li class="pg-first active"><a>&Lt;</a></li>
        <?php endif; ?>

        <!-- Previous page link -->

        <?php if (isset($this->previous)): ?>
        <li class="pg-prev"><a onclick='javascript: jQuery("#<?php echo $idPage; ?>").val("<?php echo $this->previous; ?>");jQuery(this).parents("form").submit();return false;' href="#" title="Trước đó"></a></li>
        <?php else: ?>
			<li class="pg-prev"><a></a></li>
        <?php endif; ?>
        <!-- Numbered page links -->
        
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
            <li><a href='#' onclick='javascript: jQuery("#<?php echo $idPage; ?>").val("<?php echo $page; ?>");jQuery(this).parents("form").submit();return false;'><?php echo $page;?></a></li>
            <?php else: ?>
            <li<?php if($page==$this->current) echo ' class="active"';?>><span><?php echo $page;?></span></li>
            <?php endif; ?>
        <?php endforeach; ?>
        
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
        <li class="pg-next"><a onclick='javascript: jQuery("#<?php echo $idPage; ?>").val("<?php echo $this->next; ?>");jQuery(this).parents("form").submit();return false;' href="#" title="Tiếp theo"></a></li>
        <?php else: ?>
			<li class="pg-next"><a></a></li>
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
        <li class="pg-last"><a onclick='javascript: jQuery("#<?php echo $idPage; ?>").val("<?php echo $this->last; ?>");jQuery(this).parents("form").submit();return false;' href="#" title="Trang cuối">&Gt;</a></li>
        <?php else: ?>
              <li class="pg-last active"><a>&Gt;</a></li>
        <?php endif; ?>
<!--        <div class="limit_last">
        &nbsp;<?php echo $this->current;?>&nbsp;/&nbsp;<?php echo $this->last; ?>
        </div>-->
        <?php }?>      
    <input type="hidden" id="<?php echo $idPage; ?>" name="page" value="<?php echo $this->current; ?>">    
    <input type="hidden" name="old_item_count_per_page" value="<?php echo $this->itemCountPerPage;?>" />
</ul>