<style>
    table.history{
        width: 100%;
    }
    table.history th,table.history td{
        border: 1px solid black;
    }
</style>
<?php
if (isset($this->error) && trim($this->error) != '') {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="col-lg-3 col-md-3"></div>
        <div class="col-lg-6 col-md-6" align='center' style='color: red;'>
            <?php
            echo $this->error;
            ?>
        </div>
        <div class="col-lg-3 col-md-3"></div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <?php
    $buttons[] = array('onclick' => "window.location = '" . $this->baseUrl('/admin/dichvuhaumai/index') . "'", 'label' => 'Quay lại');
    $buttons[] = array('onclick' => 'document.form.submit();', 'label' => 'Lưu');
    echo $this->toolbar($buttons);
    ?>
</div>
<form name="form" enctype="multipart/form-data" id="form" action="<?php echo $this->url(); ?>" method="post">
    <div class="row-fluid" style="margin-top: 10px;">
        <div class="col-lg-4 col-md-4"></div>

        <div class="col-lg-12 col-md-12">
            <table width="100%"> 
                <tbody>     
                    <tr></tr><tr>                 
                        <td align="right" nowrap="nowrap"><label for="title" class="optional">Tiêu đề:</label>
                        </td>
                        <td nowrap="nowrap">

                            <input type="text" name="title" id="title" value="<?php echo $this->title;?>">					                 </td>

                    </tr><tr>                 
                        <td align="right" nowrap="nowrap"><label for="content" class="required">Nội dung:</label>
                        </td>
                        <td nowrap="nowrap">
                            <br>
                            <textarea cols="50" rows="5" id="content" name="content"><?php echo $this->content;?></textarea>

                    </tr>
                    <tr<?php if($this->is_to_roi=='1') echo ' style="display:none";';?>>                 
                        <td align="right" nowrap="nowrap"><label for="tu_ngay" class="optional">Từ ngày:</label>
                        </td>
                        <td nowrap="nowrap">

                            <input readonly="readonly" type="text" name="tu_ngay" id="tu_ngay" value="<?php echo $this->tu_ngay;?>">					                 </td>

                    </tr>
                    <tr<?php if($this->is_to_roi=='1') echo ' style="display:none";';?>>                 
                        <td align="right" nowrap="nowrap"><label for="den_ngay" class="optional">Đến ngày:</label>
                        </td>
                        <td nowrap="nowrap">

                            <input readonly="readonly" type="text" name="den_ngay" id="den_ngay" value="<?php echo $this->den_ngay;?>">					                 </td>

                    </tr>
                    <tr>                 
                        <td align="right" nowrap="nowrap">
                            <label for="city_cap_1" class="optional">Khu vực:</label>
                        </td>
                        <td nowrap="nowrap">
                            <select name="city_cap_1" id="city_cap_1" class="fp-control fp-input-select">
                                            <option value="">---Chọn khu vực---</option>
                                            <?php 
                                            $city_cap_1s=$this->city_cap_1s;
                                            if(is_array($city_cap_1s)&&count($city_cap_1s)>0){
                                                foreach ($city_cap_1s as $city_cap_1){
                                                    if($city_cap_1['id']==$this->city_cap_1){
                                                        $select=' selected="selected"';
                                                    }
                                                    else{
                                                        $select='';
                                                    }
                                                    
                                                    echo '<option'.$select.' value="'.$city_cap_1['id'].'">'.$city_cap_1['name'].'</option>';
                                                }
                                            }
                                            ?>
                                        </select>

                            </td>

                    </tr>
                    <tr style="visibility: <?php if($this->city_cap_2=='') echo 'hidden;';else echo 'visible;';?>">                 
                        <td align="right" nowrap="nowrap">
                            <label for="city_cap_2" class="optional">QUẬN/HUYỆN</label>
                        </td>
                        <td nowrap="nowrap">
                            <select name="city_cap_2" id="city_cap_2" class="fp-control fp-input-select">
                                            <option value="">---Chọn quận/huyện---</option>
                                            <?php 
                                            $city_cap_2s=$this->city_cap_2s;
                                            if(is_array($city_cap_2s)&&count($city_cap_2s)>0){
                                                foreach ($city_cap_2s as $city_cap_2){
                                                    if($city_cap_2['id']==$this->city_cap_2){
                                                        $select=' selected="selected"';
                                                    }
                                                    else{
                                                        $select='';
                                                    }
                                                    echo '<option'.$select.' class="city_cap_2_'.$city_cap_2['city_cap_1_id'].'" value="'.$city_cap_2['id'].'">'.$city_cap_2['name'].'</option>';
                                                }
                                            }
                                            ?>
                                        </select>

                            </td>

                    </tr>
                    <tr>                 
                        <td align="right" nowrap="nowrap"><label class="optional">&nbsp;</label>
                        </td>
                        <td nowrap="nowrap">

                            <label>
                                <input type="radio" name="is_to_roi" value="1"<?php if($this->is_to_roi=='1') echo ' checked="checked"';?>>&nbsp;&nbsp;Tờ rơi
                            </label>
                            <label style="margin-left: 50px;">
                                <input type="radio" name="is_to_roi" value="0"<?php if($this->is_to_roi!='1') echo ' checked="checked"';?>>&nbsp;&nbsp;Không phải tờ rơi
                            </label>
                            
                        </td>

                    </tr>
                    <tr>                 
                        <td align="right" nowrap="nowrap"><label for="photo" class="optional">Hình ảnh:</label>
                        </td>
                        <td nowrap="nowrap">

                            <input type="file" name="photo" id="photo">					                 </td>

                    </tr>
                    <?php if($this->photo!=''){?>
                    <tr>
                        <td colspan="2" style="padding-left: 150px;">
                            <img src="<?php echo $this->baseUrl('/uploads/'.$this->photo) ;?>" style="width: 100px;height: 100px;"/>
                        </td>
                    </tr>
                    <?php } ?>
                    
                </tbody>
            </table>
            
        </div>

    </div>
    <input type="hidden" name="old_photo" value="<?php echo $this->photo;?>"/>
</form>   

<script type="text/javascript">

    jQuery(function ($) {
        $("form").find("input").eq(0).focus();
        $( "#tu_ngay" ).datepicker({
          changeMonth: true,
          changeYear: true,
          dateFormat: "dd/mm/yy",
          showWeek: true,
            showOn: "button",
            buttonImage: "<?php echo $this->baseUrl('/images/calendar/calendar.gif');?>",
            buttonImageOnly: true,
            buttonText: 'Click để chọn ngày',
            option:$.datepicker.regional['vi']
        });
        $( "#den_ngay" ).datepicker({
          changeMonth: true,
          changeYear: true,
          dateFormat: "dd/mm/yy",
          showWeek: true,
            showOn: "button",
            buttonImage: "<?php echo $this->baseUrl('/images/calendar/calendar.gif');?>",
            buttonImageOnly: true,
            buttonText: 'Click để chọn ngày',
            option:$.datepicker.regional['vi']
        });
        
        $("#city_cap_1").change(function (){
            if($(this).val()==''||$("#city_cap_2").find('option[class="city_cap_2_'+$(this).val()+'"]').length==0){
                $("#city_cap_2").parent().parent().css('visibility','hidden');
                $("#city_cap_2").val('');
            }
            else{
                $("#city_cap_2").parent().parent().css('visibility','visible');
                $("#city_cap_2 option").hide();
                $("#city_cap_2").find('option[class="city_cap_2_'+$(this).val()+'"]').show();
            }
            
        });
        
        $("[name='is_to_roi']").change(function (){
            if($(this).val()=='1'){
                $("#tu_ngay").parent().parent().hide();
                $("#den_ngay").parent().parent().hide();
            }
            else{
                $("#tu_ngay").parent().parent().show();
                $("#den_ngay").parent().parent().show();
            }
        })
    });

</script>



