<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <?php echo $this->headTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&amp;subset=vietnamese" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/front_end/css/vendor.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/front_end/css/style.css">
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-2.0.3.js"></script>
</head>
<body>
    <div id="app">
        <div id="sec1" class="main-wrapper step-wrapper">
            <!-- Start Top  -->
            <div class="top">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-5 col-md-4 col-logo">
                            <div class="top-logo">
                                <div class="logo-link">
                                    <a href="/">DANGTINXAYDUNG</a>
                                </div>
                                <div class="cv-menu">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </div>
                                <div class="mobile-top-icon">
                                    <ul>
                                        <li><a href="#" id="onClickSearch"><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/icon-search.png" alt=""></a></li>
                                        <li>
                                            <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/bookmark-white.png" alt="#"><span>2</span></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="top-step-mobile">
                                <div class="st-btn-back">
                                    <a href="/"></a>
                                </div>
                                <div class="st-info">
                                    <div class="st-t-lg st-tit">Hoàn thành đăng tin</span></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-7 col-md-8 col-ct-step">
                            <div class="top-step">
                                <ul class="ct-step">
                                    <li class="ct-step-i _done"><span></span></li>
                                    <li class="ct-step-i _done"><span></span></li>
                                    <li class="ct-step-i _done"><span></span></li>
                                    <li class="ct-step-i _done"><span></span></li>
                                    <li class="ct-step-i _done"><span></span></li>
                                    <li class="ct-step-i _done"><span></span></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Top -->
            <!-- Category page -->
            <div class="page-content page-option step-content done-page">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-page form-step form-white">
                                <!-- FP COntent -->
                                <div class="fp-content">
                                    <div class="content-done">
                                        <h4>TIN CỦA BẠN ĐÃ ĐƯỢC ĐĂNG</h4>
                                        <p>Cảm ơn</p>
                                        <p><a href="<?php echo $this->baseUrl();?>/default/news/step1">Tiếp tục đăng tin</a></p>
                                    </div>
                                </div>
                                <!-- End FP Content -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End category page -->
            <!-- footer -->
            <footer class="footer">
                <div class="footer-top">
                    <div class="container">
                        <div class="row row-eq-height">
                            <div class="col-xs-3 col-sm-3 col-md-3">
                               <div class="ft-block company-social">
                                    <div class="ft-tit">LIÊN KẾT</div>
                                    <ul>
                                       <li><a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i>Facebook</a></li>
                                       <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i>Google+</a></li>
                                       <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i>Youtube</a></li>
                                       <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i>Twitter</a></li>
                                    </ul>
                               </div>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <div class="ft-block">
                                    <div class="ft-tit">VỀ CÔNG TY</div>
                                    <ul>
                                       <li><a href="#">Giới thiệu</a></li>
                                       <li><a href="#">Tuyển dụng</a></li>
                                       <li><a href="#">Blog</a></li>
                                    </ul>
                               </div>
                            </div>
                            <div class="col-480-full col-xs-3 col-sm-3 col-md-3">
                               <div class="ft-block">
                                    <div class="ft-tit">VỀ KHÁCH HÀNG</div>
                                    <ul>
                                       <li><a href="#">Chính sách quảng cáo</a></li>
                                       <li><a href="#">Dịch vụ hậu mãi</a></li>
                                       <li><a href="#">Bảo mật thông tin</a></li>
                                    </ul>
                               </div>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3">
                               <div class="ft-block">
                                    <div class="ft-img"><a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/dadangky.png" alt=""></a></div>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End footer top -->
                <!-- Footer bottom -->
                <div class="footer-bottom">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                   © 2018 Copyright by DungLV
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Footer bottom -->
            </footer>
            <!-- End footer -->
        </div>
    </div>
    <div class="go-top">
    </div>
    <script src="<?php echo $this->baseUrl();?>/front_end/js/script.js"></script>
</body>

</html>