<div class="page-content page-option step-content done-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form-page form-step form-white">
                    <div class="fp-content">
                        <div class="content-done">
                            <h4>TIN CỦA BẠN ĐÃ ĐƯỢC ĐĂNG</h4>
                            <p>Cảm ơn</p>
                            <p><a href="<?php echo $this->baseUrl();?>/default/news/step1">Tiếp tục đăng tin</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>