<form action="<?php echo $this->baseUrl();?>/default/news/duan3" id="frm" method="POST" onsubmit="return false;">
    <div class="page-content page-option step-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-page form-step fp-mt0">
                        <div class="fp-heading">
                            <div class="fp-tit">Danh mục 1<span>*</span></div>
                            <div class="fp-extra">Phần ưu tiên bắt buộc chọn một mục</div>
                        </div>
                        <div class="fp-content">
                            <!-- Fp Group -->
                            <div class="fp-group">
                                <div class="fp-input fp-list">
                                    <?php 
                                    $items=$this->items;
                                    for($i=0,$n=count($items);$i<$n;$i++){
                                        if($i==0&&!is_numeric($this->du_an_cap_1)){
                                            $checked=' checked="checked"';
                                        }
                                        else{
                                            if($this->du_an_cap_1==$items[$i]['id']){
                                                $checked=' checked="checked"';
                                            }
                                            else{
                                                $checked='';
                                            }
                                        }
                                        ?>
                                        <div class="fp-list-i">
                                            <input value="<?php echo $items[$i]['id'];?>" type="radio" name="muc"<?php echo $checked;?> class="fp-list-chckbox">
                                            <span><?php echo $items[$i]['name'];?></span>
                                        </div>
                                    <?php 
                                    }
                                    ?>
                                </div>
                            </div>
                            <!-- End Fp Group -->
                            <div class="fp-submit" id="next">
                                <button class="fp-btn fp-btn-register">Tiếp</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
jQuery(function ($){
    
   $("#next").click(function (){
        $.ajax({
            url:$("#frm").attr('action'),
            data: $("#frm").serialize(),                         
            type: 'post',
            async: false,
            success: function(php_script_response){
                window.location=$("#frm").attr('action');
            }
        });
   });
});
</script>