<div class="page-content page-option step-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form-page form-step fp-mt0">
                    <div class="fp-heading">
                        <div class="fp-tit">Danh mục 3</div>
                        <div class="fp-extra">Phần không ưu tiên chỉ có thể chọn một mục</div>
                    </div>
                    <div class="fp-content">
                        <!-- Fp Group -->
                        <div class="fp-group">
                            <div class="fp-input fp-list">
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" checked="checked" class="fp-list-chckbox">
                                    <span>Phần thô</span>
                                </div>
                                <!-- End FP List Item -->
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" class="fp-list-chckbox">
                                    <span>Phần hoàn thiện</span>
                                </div>
                                <!-- End FP List Item -->
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" class="fp-list-chckbox">
                                    <span>Thiết bị gia dụng</span>
                                </div>
                                <!-- End FP List Item -->
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" class="fp-list-chckbox">
                                    <span>Nhà bếp</span>
                                </div>
                                <!-- End FP List Item -->
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" class="fp-list-chckbox">
                                    <span>Nhà vệ sinh</span>
                                </div>
                                <!-- End FP List Item -->
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" class="fp-list-chckbox">
                                    <span>Sân vườn</span>
                                </div>
                                <!-- End FP List Item -->
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" class="fp-list-chckbox">
                                    <span>Thiết kế</span>
                                </div>
                                <!-- End FP List Item -->
                            </div>
                        </div>
                        <!-- End Fp Group -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>