<div class="page-content page-option step-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form-page form-step form-white">
                    <div class="fp-heading">
                        <div class="fp-tit">Chi tiết <span>*</span></div>
                    </div>
                    <!-- FP COntent -->
                    <div class="fp-content">
                        <!-- Fp Group -->
                        <div class="fp-group">
                            <div class="fp-label">
                                TIÊU ĐỀ
                                <div class="checkbox-ad">
                                    <input type="checkbox" class="cb-in-ad">
                                    <span>ĐỀ NGHỊ QUẢNG CÁO</span>
                                </div>
                            </div>
                            <div class="fp-input fp-textbox">
                                <input type="text" class="fp-control" placeholder="Nhập tiêu đề">
                            </div>
                        </div>
                        <!-- End Fp Group -->
                        <!-- Fp Group -->
                        <div class="fp-group row">
                            <div class="col-sm-6 col-md-3 col-area">
                                <div class="fp-label">KHU VỰC</div>
                                <div class="fp-input fp-select">
                                    <select name="" id="" class="fp-control fp-input-select">
                                        <option value="">Đà Nẵng</option>
                                        <option value="">Quảng Nam</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 col-addr">
                                <div class="fp-label">QUẬN/HUYỆN</div>
                                <div class="fp-input fp-select">
                                    <select name="" id="" class="fp-control fp-input-select">
                                        <option value="">Sơn Trà</option>
                                        <option value="">Ngũ Hành Sơn</option>
                                        <option value="">Hải Châu</option>
                                        <option value="">Liên Chiểu</option>
                                        <option value="">Cẩm Lệ</option>
                                        <option value="">Thanh Khê</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-6 col-time">
                                <div class="fp-label">THỜI GIAN THI CÔNG</div>
                                <div class="fp-input fp-date">
                                    <div class="fp-control fp-date-w">
                                        <input type="text" name="day" class="fp-d-d" maxlength="2" placeholder="dd">
                                        <span></span>
                                        <input type="text" name="month" class="fp-d-m" maxlength="2" placeholder="mm">
                                        <span></span>
                                        <input type="text" name="year" class="fp-d-y" maxlength="2" placeholder="yy">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End Fp Group -->
                        <!-- Fp Group -->
                        <div class="fp-group row">
                            <div class="col-sm-12 col-md-6">
                                <div class="fp-sub-group">
                                    <div class="fp-label">TỔNG ĐẦU TƯ</div>
                                    <div class="fp-input fp-textbox">
                                        <input type="text" class="fp-control" placeholder="Nhập số tổng đầu tư">
                                    </div>
                                </div>
                                <div class="fp-sub-group">
                                    <div class="fp-label">THÔNG TIN YÊU CẦU</div>
                                    <div class="fp-input fp-textarea">
                                        <textarea name="" rows="5" class="fp-control" placeholder="Nhập thông tin yêu cầu"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <div class="fp-sub-group">
                                    <div class="fp-label">HÌNH ẢNH</div>
                                    <div class="fp-input fp-file">
                                        <div class="fp-f-choose">
                                            <div class="fp-f-main">
                                                <input type="file" name="fileee" class="fp-f-input">
                                                <div class="fp-f-m-before">
                                                    <img src="assets/images/layout/upload-to-cloud.png" alt="">
                                                    <span>Tải ảnh lên</span>
                                                    <span>(tối đa 5 ảnh)</span>
                                                </div>
                                                <div class="fp-f-m-after"></div>
                                            </div>
                                        </div>
                                        <div class="fp-f-chip">
                                            <ul class="fp-f-lstchip">
                                                <li class="fp-f-chip-i _done">
                                                    <div class="fp-f-chip-ii">
                                                        <img src="assets/images/form/chip-1.png" alt="">
                                                        <div class="fp-f-stips">
                                                            <span class="fp-f-stip stip-ok"></span>
                                                            <span class="fp-f-stip stip-remove"></span>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li class="fp-f-chip-i _loading">
                                                    <div class="fp-f-chip-ii">
                                                        <img src="assets/images/form/chip-1.png" alt="">
                                                        <span class="fp-f-loading" data-percent="30%"></span>
                                                    </div>
                                                </li>
                                                <li class="fp-f-chip-i _done">
                                                    <div class="fp-f-chip-ii">
                                                        <img src="assets/images/form/chip-1.png" alt="">
                                                        <div class="fp-f-stips">
                                                            <span class="fp-f-stip stip-ok"></span>
                                                            <span class="fp-f-stip stip-remove"></span>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li class="fp-f-chip-i _unselect">
                                                    <div class="fp-f-chip-ii"></div>
                                                </li>
                                                <li class="fp-f-chip-i _unselect">
                                                    <div class="fp-f-chip-ii"></div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End Fp Group -->
                        <div class="fp-submit">
                            <button class="fp-btn fp-btn-register">ĐĂNG TIN</button>
                        </div>
                    </div>
                    <!-- End FP Content -->
                </div>
            </div>
        </div>
    </div>
</div>