<form action="<?php echo $this->baseUrl();?>/news/nhathauthicong6" id="frm" method="POST">
    <div class="page-content page-option step-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-page form-step fp-mt0">
                        <div class="fp-heading">
                            <div class="fp-tit">Danh mục 3</div>
                            <div class="fp-extra">Phần không ưu tiên có thể chọn nhiều mục</div>
                        </div>
                        <div class="fp-content">
                            <!-- Fp Group -->
                            <div class="fp-group">
                                <div class="fp-input fp-list">
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" checked="checked" name="check0" class="fp-list-chckbox">
                                        <span>Sơn</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" checked="checked" name="check0" class="fp-list-chckbox">
                                        <span>Cốt pha</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" name="check0" class="fp-list-chckbox">
                                        <span>Thép</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" name="check0" class="fp-list-chckbox">
                                        <span>Chống thấm</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" name="check0" class="fp-list-chckbox">
                                        <span>Sơn</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" name="check0" class="fp-list-chckbox">
                                        <span>Cốt pha</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" name="check0" class="fp-list-chckbox">
                                        <span>Thép</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" name="check0" class="fp-list-chckbox">
                                        <span>Chống thấm</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" name="check0" class="fp-list-chckbox">
                                        <span>Sơn</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input type="checkbox" name="check0" class="fp-list-chckbox">
                                        <span>Cốt pha</span>
                                    </div>
                                    <!-- End FP List Item -->
                                </div>
                            </div>
                            <!-- End Fp Group -->
                            <div class="fp-submit">
                                <button class="fp-btn fp-btn-register">Tiếp</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>