<link rel="stylesheet" href="<?php echo $this->baseUrl('/jquery-ui-1.10.3/themes/smoothness/jquery-ui.css'); ?>" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/jquery-ui.js"></script>     
<script src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/i18n/jquery.ui.datepicker-vi.js"></script>
<form action="<?php echo $this->baseUrl();?>/news/savenhathauthicong" id="frm" method="POST">
    <div class="page-content page-option step-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-page form-step form-white">
                        <div class="fp-heading">
                            <div class="fp-tit">Chi tiết <span>*</span></div>
                        </div>
                        <!-- FP COntent -->
                        <div class="fp-content">
                            <!-- Fp Group -->
                            <div class="fp-group">
                                <div class="fp-label">TIÊU ĐỀ</div>
                                <div class="fp-input fp-textbox">
                                    <input name="title" type="text" class="fp-control" placeholder="Nhập tiêu đề">
                                </div>
                            </div>
                            <!-- End Fp Group -->
                            <!-- Fp Group -->
                            <div class="fp-group row">
                                <div class="col-sm-6 col-md-3 col-area">
                                    <div class="fp-label">KHU VỰC</div>
                                    <div class="fp-input fp-select">
                                        <select name="city_cap_1" id="city_cap_1" class="fp-control fp-input-select">
                                            <option value="">---Chọn khu vực---</option>
                                            <?php 
                                            $city_cap_1s=$this->city_cap_1s;
                                            if(is_array($city_cap_1s)&&count($city_cap_1s)>0){
                                                foreach ($city_cap_1s as $city_cap_1){
                                                    echo '<option value="'.$city_cap_1['id'].'">'.$city_cap_1['name'].'</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div style="visibility: hidden;" class="col-sm-6 col-md-3 col-addr">
                                    <div class="fp-label">QUẬN/HUYỆN</div>
                                    <div class="fp-input fp-select">
                                        <select name="city_cap_2" id="city_cap_2" class="fp-control fp-input-select">
                                            <option value="">---Chọn quận/huyện---</option>
                                            <?php 
                                            $city_cap_2s=$this->city_cap_2s;
                                            if(is_array($city_cap_2s)&&count($city_cap_2s)>0){
                                                foreach ($city_cap_2s as $city_cap_2){
                                                    echo '<option class="city_cap_2_'.$city_cap_2['city_cap_1_id'].'" value="'.$city_cap_2['id'].'">'.$city_cap_2['name'].'</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-time">
                                    <div class="fp-label">NGÀY ĐÁP ỨNG DỰ ÁN</div>
                                    <div class="fp-input fp-date">
                                        <input readonly="readonly" type="text" id="ngay" name="ngay">
                                    </div>
<!--                                    <div class="fp-input fp-date">
                                        <div class="fp-control fp-date-w">
                                            <input type="text" name="day" class="fp-d-d" maxlength="2" placeholder="dd">
                                            <span></span>
                                            <input type="text" name="month" class="fp-d-m" maxlength="2" placeholder="mm">
                                            <span></span>
                                            <input type="text" name="year" class="fp-d-y" maxlength="2" placeholder="yy">
                                        </div>
                                    </div>-->
                                </div>
                            </div>
                            <!-- End Fp Group -->
                            <!-- Fp Group -->
                            <div class="fp-group row">
                                <div class="col-sm-12 col-md-6">
                                    <div class="fp-sub-group row">
                                        <div class="col-sm-6 col-md-6 col-area">
                                            <div class="fp-label">Phân loại</div>
                                            <div class="fp-input fp-select">
                                                <select name="phan_loai" id="phan_loai" class="fp-control fp-input-select">
                                                    <option value="1">Nhân viên</option>
                                                    <option value="2">Đối tác</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-6 col-addr">
                                            <div class="fp-label">Dụng cụ thi công</div>
                                            <div class="fp-input fp-textbox">
                                                <input name="dich_vu_thi_cong" type="text" class="fp-control" placeholder="VD: 20 xe múc,...">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="fp-sub-group">
                                        <div class="fp-label fp-label-require">THÔNG TIN YÊU CẦU<span class="s-star">*</span></div>
                                        <div class="fp-input fp-textarea">
                                            <textarea name="content" rows="5" class="fp-control" placeholder="Nhập thông tin yêu cầu"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <div class="fp-sub-group">
                                        <div class="fp-label">HÌNH ẢNH</div>
                                        <div class="fp-input fp-file">
                                            <div class="fp-f-choose">
                                                <div class="fp-f-main">
                                                    <input type="file" name="fileee" id="fileee" class="fp-f-input">
                                                    <div class="fp-f-m-before">
                                                        <img src="<?php echo $this->baseUrl();?>/front_end/images/layout/upload-to-cloud.png" alt="">
                                                        <span>Tải ảnh lên</span>
                                                        <span>(tối đa 5 ảnh)</span>
                                                    </div>
                                                    <div class="fp-f-m-after"></div>
                                                </div>
                                            </div>
                                            <div class="fp-f-chip">
                                                <ul class="fp-f-lstchip">
                                                    <li class="fp-f-chip-i _done">
                                                        <div class="fp-f-chip-ii">
                                                            <img id="img1" alt="">
                                                            <div class="fp-f-stips" style="display: none;">
                                                                <span class="fp-f-stip stip-ok"></span>
                                                                <span class="fp-f-stip stip-remove"></span>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li class="fp-f-chip-i _done">
                                                        <div class="fp-f-chip-ii">
                                                            <img id="img2" alt="">
                                                            <!--<span class="fp-f-loading" data-percent="30%"></span>-->
                                                            <div class="fp-f-stips" style="display: none;">
                                                                <span class="fp-f-stip stip-ok"></span>
                                                                <span class="fp-f-stip stip-remove"></span>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li class="fp-f-chip-i _done">
                                                        <div class="fp-f-chip-ii">
                                                            <img id="img3" alt="">
                                                            <div class="fp-f-stips" style="display: none;">
                                                                <span class="fp-f-stip stip-ok"></span>
                                                                <span class="fp-f-stip stip-remove"></span>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li class="fp-f-chip-i _done">
                                                        <div class="fp-f-chip-ii">
                                                            <img id="img4" alt="">
                                                            <div class="fp-f-stips" style="display: none;">
                                                                <span class="fp-f-stip stip-ok"></span>
                                                                <span class="fp-f-stip stip-remove"></span>
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li class="fp-f-chip-i _done">
                                                        <div class="fp-f-chip-ii">
                                                            <img id="img5" alt="">
                                                            <div class="fp-f-stips" style="display: none;">
                                                                <span class="fp-f-stip stip-ok"></span>
                                                                <span class="fp-f-stip stip-remove"></span>
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- End Fp Group -->
                            <div class="fp-submit">
                                <button class="fp-btn fp-btn-register">ĐĂNG TIN</button>
                            </div>
                        </div>
                        <!-- End FP Content -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    function readURL(input) {

      if (input.files && input.files[0]) {
//        var reader = new FileReader();
//
//        reader.onload = function(e) {
//            imgs=$(".fp-f-chip-ii img");
//            for(i=0;i<imgs.length;i++){
//                if($(imgs[i]).attr('src')==undefined||$(imgs[i]).attr('src')=='undefined'||$(imgs[i]).attr('src')==''){
//                    $(imgs[i]).attr('src', e.target.result);
//                    $(imgs[i]).next().show();
//                    break;
//                }
//            }
//          
//        }
//
//        reader.readAsDataURL(input.files[0]);
        
        var file_data = $('#fileee').prop('files')[0];   
        var form_data = new FormData();                  
        form_data.append('file', file_data);
        form_data.append('type', 'nha_thau_thi_cong');
        $.ajax({
            url:'<?php echo $this->baseUrl();?>/news/upload',
            dataType: 'text',  
            cache: false,
            contentType: false,
            processData: false,
            data: form_data,                         
            type: 'post',
            success: function(php_script_response){
                imgs=$(".fp-f-chip-ii img");
                for(i=0;i<imgs.length;i++){
                    if($(imgs[i]).attr('src')==undefined||$(imgs[i]).attr('src')=='undefined'||$(imgs[i]).attr('src')==''){
                        $(imgs[i]).attr('src', '<?php echo $this->baseUrl();?>/uploads/'+$.trim(php_script_response)).css('width','100%').css('height','auto');
                        $(imgs[i]).next().show();
                        break;
                    }
                }
            }
        });
      }
    }
    
    jQuery(function ($){
        $("#city_cap_2 option").hide();
    
        $( "#ngay" ).datepicker({
          changeMonth: true,
          changeYear: true,
          dateFormat: "dd/mm/yy",
          showWeek: true,
            showOn: "button",
            buttonImage: "<?php echo $this->baseUrl('/images/calendar/calendar.gif');?>",
            buttonImageOnly: true,
            buttonText: 'Click để chọn ngày',
            option:$.datepicker.regional['vi']
        });
        
        $('img.ui-datepicker-trigger').css('margin-left','10px').css('margin-bottom','10px').css('cursor','pointer');
        
        $("#fileee").change(function() {
          readURL(this);
        });
        
        $('.fp-f-stip.stip-remove').click(function (){
            photo=$(this).parent().prev().attr('src');
            $(this).parent().prev().removeAttr('src');
            $(this).parent().hide();
            $.ajax({
                url:'<?php echo $this->baseUrl();?>/news/deletephoto',
                data: {'photo':photo},                         
                type: 'post',
                success: function(php_script_response){
                    
                }
            });
        });
        
        $("#city_cap_1").change(function (){
            if($(this).val()==''||$("#city_cap_2").find('option[class="city_cap_2_'+$(this).val()+'"]').length==0){
                $("#city_cap_2").parent().parent().css('visibility','hidden');
                $("#city_cap_2").val('');
            }
            else{
                $("#city_cap_2").parent().parent().css('visibility','visible');
                $("#city_cap_2 option").hide();
                $("#city_cap_2").find('option[class="city_cap_2_'+$(this).val()+'"]').show();
            }
            
        });
    });
</script>