<div class="page-content page-option step-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form-page form-step fp-mt0">
                    <div class="fp-heading">
                        <div class="fp-tit">Phân loại <span>*</span></div>
                        <div class="fp-extra">Phần ưu tiên bắt buộc chọn một mục</div>
                    </div>
                    <div class="fp-content">
                        <!-- Fp Group -->
                        <div class="fp-group">
                            <div class="fp-input fp-list">
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" checked="checked" class="fp-list-chckbox">
                                    <span>Nhân công lao động</span>
                                </div>
                                <!-- End FP List Item -->
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" class="fp-list-chckbox">
                                    <span>Thiết bị máy móc</span>
                                </div>
                                <!-- End FP List Item -->
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" class="fp-list-chckbox">
                                    <span>Dụng cụ thi công</span>
                                </div>
                                <!-- End FP List Item -->
                                <!-- FP List item -->
                                <div class="fp-list-i">
                                    <input type="radio" name="check0" class="fp-list-chckbox">
                                    <span>Vật tư</span>
                                </div>
                                <!-- End FP List Item -->
                            </div>
                        </div>
                        <!-- End Fp Group -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>