<form action="<?php echo $this->baseUrl();?>/default/news/nhathauthicong4" id="frm" method="POST" onsubmit="return false;">
    <div class="page-content page-option step-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-page form-step fp-mt0">
                        <div class="fp-heading">
                            <div class="fp-tit">Step 3: Danh mục loại tin</div>
                        </div>
                        <div class="step-path">
                            <div class="ct-breadcrumb">
                                <ul>
                                    <li><a href="<?php echo $this->baseUrl();?>/default/news/step1">Step 1</a></li>
                                    <li><a href="<?php echo $this->baseUrl();?>/default/news/nhathauthicong2">Step 2</a></li>

                                </ul>
                            </div>
                        </div>
                        <div class="top-step-mobile">
                            <div class="st-btn-back"><a href="<?php echo $this->baseUrl();?>/default/news/nhathauthicong2"></a></div>
                            <div class="st-info">
                                <div class="st-t-lg st-tit">Nhà thầu thi công</div>
                                <div class="st-t-small st-extra">Phần không ưu tiên chỉ có thể chọn một mục</div>
                            </div>
                        </div>
                        <div class="fp-content">
                            <!-- Fp Group -->
                            <div class="fp-group">
                                <div class="fp-input fp-list">
                                    <?php 
                                    $items=$this->items;
                                    for($i=0,$n=count($items);$i<$n;$i++){
                                        if($i==0&&!is_numeric($this->nha_thau_thi_cong_cap_2)){
                                            $checked=' checked="checked"';
                                        }
                                        else{
                                            if($this->nha_thau_thi_cong_cap_2==$items[$i]['id']){
                                                $checked=' checked="checked"';
                                            }
                                            else{
                                                $checked='';
                                            }
                                            
                                        }
                                        ?>
                                        <div class="fp-list-i">
                                            <input value="<?php echo $items[$i]['id'];?>" type="radio" name="muc"<?php echo $checked;?> class="fp-list-chckbox">
                                            <span><?php echo $items[$i]['name'];?></span>
                                        </div>
                                    <?php 
                                    }
                                    ?>
                                </div>
                            </div>
                            <!-- End Fp Group -->
                            <div class="fp-submit" id="next">
                                <button class="fp-btn fp-btn-register">Tiếp</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
jQuery(function ($){
    
   $("#next").click(function (){
        $.ajax({
            url:$("#frm").attr('action'),
            data: $("#frm").serialize(),                         
            type: 'post',
            async: false,
            success: function(php_script_response){
                window.location=$("#frm").attr('action');
            }
        });
   });
});
</script>