<form action="<?php echo $this->baseUrl();?>/default/news/step1" id="frm" method="POST">
    <div class="page-content page-option step-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-page form-step fp-mt0">

                        <div class="fp-heading">
                            <div class="fp-tit">Bước1: Chọn dự án / nhà thầu</div>
                        </div>
                        <div class="top-step-mobile">
                            <div class="st-btn-back">
                                <!--<a href="#"></a>-->
                            </div>
                            <div class="st-info">
                                <div class="st-t-lg st-tit">Dự án <span>*</span></div>
                                <div class="st-t-small st-extra">Phần ưu tiên bắt buộc chọn một mục</div>
                            </div>
                        </div>
                        <div class="fp-content">
                            <!-- Fp Group -->
                            <div class="fp-group">
                                <div class="fp-input fp-list">
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input id="duan2" value="duan" type="radio" name="type" checked="checked" class="fp-list-chckbox">
                                        <span>Dự án</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input id="nhathauthicong2" value="nhathauthicong" type="radio" name="type" class="fp-list-chckbox">
                                        <span>Nhà thầu thi công</span>
                                    </div>
                                    <!-- End FP List Item -->
                                </div>
                            </div>
                            <!-- End Fp Group -->
                            <div class="fp-submit" id="next">
                                <button class="fp-btn fp-btn-register">Tiếp</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>