<form action="<?php echo $this->baseUrl();?>/default/news/step1" id="frm" method="POST">
    <div class="page-content page-option step-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-page form-step fp-mt0">
                        <div class="fp-heading">
                            <div class="fp-tit">NHU CẦU<span>*</span></div>
                            <div class="fp-extra">Phần ưu tiên bắt buộc chọn một mục</div>
                        </div>
                        <div class="fp-content">
                            <!-- Fp Group -->
                            <div class="fp-group">
                                <div class="fp-input fp-list">
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input id="duan2" type="radio" name="type" value="duan" checked="checked" class="fp-list-chckbox">
                                        <span>Dự án</span>
                                    </div>
                                    <!-- End FP List Item -->
                                    <!-- FP List item -->
                                    <div class="fp-list-i">
                                        <input id="nhathauthicong2" type="radio" name="type" value="nhathauthicong" class="fp-list-chckbox">
                                        <span>Nhà thầu thi công</span>
                                    </div>
                                    <!-- End FP List Item -->
                                </div>
                            </div>
                            <!-- End Fp Group -->
                            <div class="fp-submit">
                                <button class="fp-btn fp-btn-register">Tiếp</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
