<div class="page-content detail-page category-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ct-breadcrumb">
                    <ul>
                        <li><a href="#">DANGTINXAYDUNG</a></li>
                        <li><a href="#">Dự án</a></li>
                        <li><a href="#">Dân dụng</a></li>
                        <li><a href="#">Phần hoàn thiện</a></li>
                        <li><a href="#">Thạch cao</a></li>
                        <li><a href="#">Thạch cao</a></li>
                        <li><a href="#">Cần nghệ nhân làm tiểu cảnh</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-12">
                <!-- Detail Infor -->
                <div class="dt-info">
                    <div class="dt-thumb">
                        <div class="dt-main-thumb">
                            <div class="ct-replace-img">
                                <img src="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-detail-main.png" alt="">
                            </div>
                            <span>03</span>
                        </div>
                        <div class="dt-chip-thumb">
                            <div class="chip-thumb chip-thumb-slider">
                                <div class="chip-thumb-pi">
                                    <div class="chip-thumb-i">
                                        <img src="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-chip.png" alt="">
                                    </div>
                                </div>
                                <div class="chip-thumb-pi">
                                    <div class="chip-thumb-i" data-image="<?php echo $this->baseUrl();?>/front_end/images/home/active-adults-bars-583392 2.png">
                                        <img src="<?php echo $this->baseUrl();?>/front_end/images/home/active-adults-bars-583392 2.png" alt="">
                                    </div>
                                </div>
                                <div class="chip-thumb-pi">
                                    <div class="chip-thumb-i" data-image="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-chip.png">
                                        <img src="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-chip.png" alt="">
                                    </div>
                                </div>
                                <div class="chip-thumb-pi">
                                    <div class="chip-thumb-i" data-image="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-chip.png">
                                        <img src="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-chip.png" alt="">
                                    </div>
                                </div>
                                <div class="chip-thumb-pi">
                                    <div class="chip-thumb-i" data-image="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-chip.png">
                                        <img src="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-chip.png" alt="">
                                    </div>
                                </div>
                                <div class="chip-thumb-pi">
                                    <div class="chip-thumb-i" data-image="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-chip.png">
                                        <img src="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-chip.png" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="dt-share">
                            <div class="dt-t">Chia sẻ dự án tới:</div>
                            <ul class="dt-li-share">
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                    <span>Facebook</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-messenger.png" alt=""></a>
                                    <span>Messenger</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                    <span>Twitter</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                    <span>Google+</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-link.png" alt=""></a>
                                    <span>Link</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="dt-content">
                        <div class="dt-title">
                            <a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a>
                            <a href="#" class="cit-btn">Chọn dự án</a>
                        </div>
                        <div class="dt-desc">
                            Yêu cầu đội thi công đáp ứng công việc 2 ca trong một ngày: Số lượng 30 người Máy thi công đáp ứng đúng yêu cầu công việc Thời gian dự kiến thi công 30 ngày kể từ ngày bàn giao mặt bằng Được tạm ứng 30% khi ký hợp đồng và vận chuyển dụng cụ máy móc thiết bị đến công trình Thanh toán 90 % mỗi tầng hoàn thành khi đã nghiệm thu bàn giao, 10% cong lại khi đã hoàn thành sau thời gian nghiệm thu 1 tháng.
                        </div>
                        <div class="dt-pos">
                            <div class="dt-pos-l">
                                <p>Thời gian thi công: 04/06/2018</p>
                                <p>Cộng tác viên</p>
                            </div>
                            <div class="dt-pos-r">
                                <p>Khu vực</p>
                                <p>Ngũ  Hành Sơn</p>
                            </div>
                        </div>
                        <div class="dt-cast">
                            <ul>
                                <li><a href="#">Phần hoàn thiện</a></li>
                                <li><a href="#">Thạch cao</a></li>
                                <li><a href="#">Sản phẩm nổi</a></li>
                                <li><a href="#">Dự án dự trù</a></li>
                                <li><a href="#">Thạch cao</a></li>
                                <li><a href="#">Phàn hoàn thiện</a></li>
                                <li><a href="#">Thạch cao</a></li>
                                <li><a href="#">Phàn hoàn thiện</a></li>
                                <li><a href="#">Thạch cao</a></li>
                                <li><a href="#">Phàn hoàn thiện</a></li>
                                <li><a href="#">Thạch cao</a></li>
                            </ul>
                        </div>
                        <div class="dt-btn">
                            <div class="dt-btn-cl">
                                <div class="dt-mark">
                                    Tổng đầu tư 500 triệu
                                </div>
                            </div>
                            <div class="dt-btn-cl">
                                <div class="dt-phone">
                                    <!--  <div id="click_show_phone" class="ct-btn-phone" data-number="01228559193">Nhấn để hiện số hoặc để lại tin nhắn</div> -->
                                    <div class="ct-btn-phone ct-btn-mobile"><a href="tel:01228559193">Gọi điện</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="dt-share dt-share-mobile">
                            <div class="dt-t">Chia sẻ dự án tới:</div>
                            <ul class="dt-li-share">
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-messenger.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-link.png" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End detail Infor -->
                <!-- Detail Banner -->
                <div class="dt-banner">
                    <div class="dt-ls-banner dt-banner-slider">
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                    </div>
                </div>
                <!-- End Detail Banner -->

            </div>
        </div>
    </div>
    <div class="detail-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Detail Retated post -->
                    <div class="dt-related content-cate">
                        <div class="dt-rl-head">
                            <h4>Các bài viết liên quan</h4>
                        </div>
                        <div class="dt-rl-cate cate-list">
                            <div class="cate-wr _ct_grid">
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#"><span class="tap-hot">Hot</span>Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main p-opening">Đang thi công</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                            </div>
                        </div>
                    </div>
                    <!-- End Detail Retated post -->
                </div>
            </div>
        </div>
    </div>
    <div class="ct-ad-mobile">
        <div class="ct-ad-mobile-i">
            <span>BANNER</span> DỊCH VỤ HẬU MÃI
        </div>
        <div class="ct-ad-mobile-i">
            <span>BANNER</span> DỊCH VỤ HẬU MÃI
        </div>
    </div>
</div>
