<div class="dt-banner">
    <div class="dt-ls-banner dt-banner-slider">
        <!-- Banner Item -->
        <div class="dt-banner-i">
            <div class="dt-banner-wr">
                <span>Banner</span> dịch vụ hậu mãi
            </div>
        </div>
        <!-- End Banner Item -->
        <!-- Banner Item -->
        <div class="dt-banner-i">
            <div class="dt-banner-wr">
                <span>Banner</span> dịch vụ hậu mãi
            </div>
        </div>
        <!-- End Banner Item -->
        <!-- Banner Item -->
        <div class="dt-banner-i">
            <div class="dt-banner-wr">
                <span>Banner</span> dịch vụ hậu mãi
            </div>
        </div>
        <!-- End Banner Item -->
        <!-- Banner Item -->
        <div class="dt-banner-i">
            <div class="dt-banner-wr">
                <span>Banner</span> dịch vụ hậu mãi
            </div>
        </div>
        <!-- End Banner Item -->
        <!-- Banner Item -->
        <div class="dt-banner-i">
            <div class="dt-banner-wr">
                <span>Banner</span> dịch vụ hậu mãi
            </div>
        </div>
        <!-- End Banner Item -->
    </div>
</div>
