<?php 
$quangcao_items = $this->quangcao_items;
foreach ($quangcao_items as $item) {
    ?>
    <div class="cate-ad-i">
        <div class="cate-ad-ii">
            <div class="cai-thumb">
                <img src="<?php echo $this->baseUrl($item['photo']); ?>" alt="">
            </div>
            <div class="cai-tit" style="margin: 0 auto;text-align: center;">
                <a style="word-wrap: break-word;" href="<?php echo $this->baseUrl("/index/duandetail/id/" . $item['id']); ?>"><?php echo $item['title']; ?></a>
            </div>
            <div class="cai-desc">
                <div class="cai-col cai-cl">
                    <p>&nbsp;&nbsp; <span><?php echo $item['tong_dau_tu']; ?></span></p>
                    <p class="cai-phone"><a><?php echo $item['phone']; ?></a></p>
                </div>
                <!--tuetc-->
                <!--                                                tạm thời ẩn nút Chọn dự án tại các tin ở vùng quảng cáo-->
<!--                                                                <div class="cai-col cai-cr">
                <?php 
                if ($this->isLogin) {
                    if (!in_array($item['id'], $this->du_an_da_chon_ids)) {
                        ?>
                                                                                <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id']; ?>" class="cai-btn-project chon_du_an"></a>
                        <?php 
                    } else {
                        ?>
                                                                                 <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id']; ?>" class="cai-btn-project chon_du_an huy"></a>   
                        <?php 
                    }
                } else {
                    if (!$this->isLogin) {
                        ?>
                                                                                <a href="<?php echo $this->baseUrl(); ?>/default/account/login" class="cai-btn-project"></a>
                        <?php 
                    }
                }
                ?>
                                                                </div>-->
            </div>
        </div>
    </div>
    <?php 
}
?>