<?php 
$items = $this->items;
$auth = Zend_Auth::getInstance();
$identity = $auth->getIdentity();
if ($auth->hasIdentity() && ($identity['type'] == Default_Model_User::KHACH_HANG || $identity['type'] == Default_Model_User::DOI_TAC)) {
    $number_du_an_da_chon = Core_Db_Table::getDefaultAdapter()->fetchCol("select count(*) from du_an_da_chon where user_id='" . $identity['id'] . "' and tin_du_an_id='" . $items[0]['id'] . "'");
    $number_du_an_da_chon = $number_du_an_da_chon[0];
}
?>
<div class="page-content detail-page category-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ct-breadcrumb">
                    <ul>
                        <li><a>DANGTINXAYDUNG</a></li>
                        <li><a>Dự án</a></li>
                        <?php 
                        if(trim($items[0]['du_an_cap_1'])!=''){
                            echo '<li><a>'.$items[0]['du_an_cap_1'].'</a></li>';
                        }
                        
                        if(trim($items[0]['du_an_cap_2'])!=''){
                            echo '<li><a>'.$items[0]['du_an_cap_2'].'</a></li>';
                        }
                        
                        ?>
                    </ul>
                </div>
            </div>
            <div class="col-md-12">
                <!-- Detail Infor -->
                <div class="dt-info">
                    <div class="dt-thumb">
                        <div class="dt-main-thumb">
                            <div class="ct-replace-img">
                                <?php 
                                if($items[0]['photo']!=''){?>
                                    <img style="width: 100%;height: auto;" src="<?php echo $this->baseUrl('/uploads/'.$items[0]['photo']);?>" alt="">
                                <?php 
                                }
                                else{?>
                                    <img src="<?php echo $this->baseUrl(PHOTO_DEFAULT);?>" alt="">
                                <?php 
                                }
                                ?>
                            </div>
<!--                            tuetc
                            <span>03</span>-->
                        </div>
                        <div class="dt-chip-thumb">
                            <div class="chip-thumb chip-thumb-slider">
                                <?php 
                                //ít nhất user phải upload 2 ảnh, thi mới cho hiển thị vùng này
                                if(count($items)>1&&$items[0]['photo']!=''&&$items[1]['photo']!=''){
                                    foreach ($items as $item){
                                        if($item['photo']!=''){?>
                                            <div class="chip-thumb-pi">
                                                <div class="chip-thumb-i" data-image="<?php echo $this->baseUrl();?>/front_end/images/home/active-adults-bars-583392 2.png">
                                                    <img style="width: 100%;height: auto;" src="<?php echo $this->baseUrl('/uploads/'.$item['photo']);?>" alt="">
                                                </div>
                                            </div>
                                <?php 
                                        }
                                    }
                                }
                                ?>
                            </div>
                        </div>
                        <div class="dt-share">
                            <div class="dt-t">Chia sẻ dự án tới:</div>
                            <ul class="dt-li-share">
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                    <span>Facebook</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-messenger.png" alt=""></a>
                                    <span>Messenger</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                    <span>Twitter</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                    <span>Google+</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-link.png" alt=""></a>
                                    <span>Link</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="dt-content<?php if($auth->hasIdentity()&&($identity['type']== Default_Model_User::KHACH_HANG||$identity['type']== Default_Model_User::DOI_TAC)&&isset($number_du_an_da_chon)&&$number_du_an_da_chon!='0') echo ' selected';?>">
                        <div class="dt-title">
                            <a><?php echo $items[0]['title'];?></a>
                            <?php 
                            if ($auth->hasIdentity()&&($identity['type']== Default_Model_User::KHACH_HANG||$identity['type']== Default_Model_User::DOI_TAC)) {
                                if(isset($number_du_an_da_chon)&&$number_du_an_da_chon=='0'){
                                ?>
                                <a style="cursor: pointer;" id="chon_du_an_<?php echo $items[0]['id'];?>" class="cit-btn chon_du_an">Chọn dự án</a>
                            <?php 
                                }
                                else{?>
                                 <a style="cursor: pointer;" id="chon_du_an_<?php echo $items[0]['id'];?>" class="cit-btn chon_du_an huy">Hủy chọn</a>   
                                <?php 
                                }
                            }
                            else{
                                if(!$auth->hasIdentity()){
                                ?>
                                <a href="<?php echo $this->baseUrl();?>/default/account/login" class="cit-btn"><span>Chọn dự án</span></a>
                            <?php    
                                }
                                
                            }
                            ?>
                        </div>
                        <div class="dt-desc">
                            <?php echo $items[0]['content'];?>
                        </div>
                        <div class="dt-pos">
                            <div class="dt-pos-l">
                                <p>Thời gian thi công: <?php echo $items[0]['ngay'];?></p>
                                <!--tuetc-->
                                <!--<p>Cộng tác viên</p>-->
                                <p>&nbsp;</p>
                            </div>
                            <div class="dt-pos-r">
                                <p>Khu vực</p>
                                <p>
                                    <?php 
                                    echo $items[0]['city_cap_1'];
                                    if($items[0]['city_cap_2']!=''){
                                        echo ' - '.$items[0]['city_cap_2'];
                                    }
                                    if($items[0]['city_cap_3']!=''){
                                        echo ' - '.$items[0]['city_cap_3'];
                                    }
                                    ?>
                                </p>
                            </div>
                        </div>
                        <div class="dt-cast">
                            <ul>
                                <?php 
                                $du_an_cap_3s=$this->du_an_cap_3s;
                                if(is_array($du_an_cap_3s)&&count($du_an_cap_3s)>0){
                                    foreach ($du_an_cap_3s as $du_an_cap_3){
                                        echo '<li><a>'.$du_an_cap_3['name'].'</a></li>';
                                    }
                                }
                                $du_an_cap_4s=$this->du_an_cap_4s;
                                if(is_array($du_an_cap_4s)&&count($du_an_cap_4s)>0){
                                    foreach ($du_an_cap_4s as $du_an_cap_4){
                                        echo '<li><a>'.$du_an_cap_4['name'].'</a></li>';
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                        <div class="dt-btn">
                            <div class="dt-btn-cl">
                                <div class="dt-mark">
                                    Đầu tư: <?php echo $items[0]['tong_dau_tu'];?>
                                </div>
                            </div>
                            <?php 
                            if(!$auth->hasIdentity()){
                                ?>                            
                                <div class="dt-btn-cl">
                                    <div class="dt-phone">
                                          <!--<div id="click_show_phone" class="ct-btn-phone" data-number="01228559193">Nhấn để hiện số hoặc để lại tin nhắn</div>--> 
                                          <div onclick="jQuery('#phone_list').fadeIn();" class="ct-btn-phone ct-btn-mobile"><a style="cursor: pointer;">Gọi điện</a></div>
                                          <div id="phone_list" style="display: none;max-height: 200px;overflow-y: auto;margin-top: 20px;background-color: #a9a9a9;padding: 10px;">
                                          <?php 
                                          $user_duan=$this->user_duan;
                                          if(is_array($user_duan)&&count($user_duan)>0){
                                              foreach ($user_duan as $temp){
                                                  echo '<div style="padding: 10px;">'.$temp['full_name'].": ".$temp['phone'].'</div>';
                                              }
                                          }
                                          ?>
                                          </div>
                                    </div>
                                </div>
                            <?php 
                            }
                            else{
                                if($identity['id']==$items[0]['user_id']){
                                    //k hiển thị
                                }
                                else{
                                    if($identity['type']== Default_Model_User::ADMIN){?>
                                        <div class="dt-btn-cl">
                                            <div class="dt-phone">
                                                <div class="ct-btn-phone ct-btn-mobile"><?php echo $items[0]['phone'];?></div>                                                    
                                            </div>
                                        </div>
                                    <?php                                     
                                    }
                                    else if($identity['type']== Default_Model_User::NHAN_VIEN){
                                        if(in_array($items[0]['du_an_cap_1_id'], $identity['du_an_cap_1_ids'])){?>
                                            <div class="dt-btn-cl">
                                                <div class="dt-phone">
                                                    <div class="ct-btn-phone ct-btn-mobile"><?php echo $items[0]['phone'];?></div>                                                    
                                                </div>
                                            </div>
                                    <?php 
                                        }
                                    }
                                    else{?>
                                        <div class="dt-btn-cl">
                                            <div class="dt-phone">
                                                  <!--<div id="click_show_phone" class="ct-btn-phone" data-number="01228559193">Nhấn để hiện số hoặc để lại tin nhắn</div>--> 
                                                  <div onclick="jQuery('#phone_list').fadeIn();" class="ct-btn-phone ct-btn-mobile"><a style="cursor: pointer;">Gọi điện</a></div>
                                                  <div id="phone_list" style="display: none;max-height: 200px;overflow-y: auto;margin-top: 20px;background-color: #a9a9a9;padding: 10px;">
                                                  <?php 
                                                  $user_duan=$this->user_duan;
                                                  if(is_array($user_duan)&&count($user_duan)>0){
                                                      foreach ($user_duan as $temp){
                                                          echo '<div style="padding: 10px;">'.$temp['full_name'].": ".$temp['phone'].'</div>';
                                                      }
                                                  }
                                                  ?>
                                                  </div>
                                            </div>
                                        </div>
                            <?php 
                                    }
                                }
                            }
                            ?>
                        </div>
                        <div class="dt-share dt-share-mobile">
                            <div class="dt-t">Chia sẻ dự án tới:</div>
                            <ul class="dt-li-share">
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-messenger.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-link.png" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End detail Infor -->
                <!-- Detail Banner -->
                <div class="dt-banner">
                    <div class="dt-ls-banner dt-banner-slider">
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                    </div>
                </div>
                <!-- End Detail Banner -->

            </div>
        </div>
    </div>
    <?php 
    $items_lienquan=$this->items_lienquan;
    if(is_array($items_lienquan)&&count($items_lienquan)>0){
    ?>
    <div class="detail-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Detail Retated post -->
                    <div class="dt-related content-cate">
                        <div class="dt-rl-head">
                            <h4>Các bài viết liên quan</h4>
                        </div>
                        <div class="dt-rl-cate cate-list">
                            <div class="cate-wr _ct_grid">
                                
                                <?php 
                                
                                foreach ($items_lienquan as $item){
                                    if($item['photo']==''){
                                        $item['photo']=$this->baseUrl(PHOTO_DEFAULT);
                                    }
                                    else{
                                        $item['photo']=$this->baseUrl("/uploads/".$item['photo']);
                                    }
                                    ?>
                                    
                                
                                    <div class="cate-item">
                                        <div class="cate-item-i<?php if($auth->hasIdentity()&&($identity['type']== Default_Model_User::KHACH_HANG||$identity['type']== Default_Model_User::DOI_TAC)&&in_array($item['id'], $this->du_an_da_chon_ids)) echo ' selected';?>">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $item['photo']; ?>" alt="#">
                                                <span class="cit-mark">Đầu tư: <?php echo $item['tong_dau_tu'];?></span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title">
                                                    <a href="<?php echo $this->baseUrl("/index/duandetail/id/".$item['id']);?>">
                                                        <!--<span class="tap-hot">Hot</span>tuetc-->
                                                            <?php echo $item['title'];?>
                                                    </a>
                                                </div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Thời gian thi công: <?php echo $item['ngay'];?></p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <?php 
                                                        if ($auth->hasIdentity()&&($identity['type']== Default_Model_User::KHACH_HANG||$identity['type']== Default_Model_User::DOI_TAC)) {
                                                            if(!in_array($item['id'], $this->du_an_da_chon_ids)){
                                                            ?>
                                                            <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id'];?>" class="cit-btn chon_du_an"><span>Chọn dự án</span></a>
                                                        <?php 
                                                            }
                                                            else{?>
                                                             <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id'];?>" class="cit-btn chon_du_an huy">Hủy chọn</a>   
                                                            <?php 
                                                            }
                                                        }
                                                        else{
                                                            if(!$auth->hasIdentity()){
                                                            ?>
                                                            <a href="<?php echo $this->baseUrl();?>/default/account/login" class="cit-btn"><span>Chọn dự án</span></a>
                                                        <?php    
                                                            }
                                                            
                                                        }
                                                        ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php 
                                    
                                }
                                
                                        
                                ?>
                            </div>
                        </div>
                    </div>
                    <!-- End Detail Retated post -->
                </div>
            </div>
        </div>
    </div>
    <?php 
    }
    ?>
    <div class="ct-ad-mobile">
        <div class="ct-ad-mobile-i">
            <span>BANNER</span> DỊCH VỤ HẬU MÃI
        </div>
        <div class="ct-ad-mobile-i">
            <span>BANNER</span> DỊCH VỤ HẬU MÃI
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(function ($){
   if($(".dt-cast ul li").length<=3){
       $(".dt-cast ul li").css('width','auto');
   } 
   $(".chon_du_an").click(function (){
       node=$(this);
        if(!$(this).hasClass('huy')){
            action='chonduan';
        }
        else{
            action='huychonduan';
        }
        id=$(this).attr('id').replace("chon_du_an_","");
        
        $.ajax({
            url:'<?php echo $this->baseUrl();?>/default/news/'+action,
            data: {'tin_du_an_id':id},                         
            type: 'post',
            async: true,
            success: function(php_script_response){
                $(node).toggleClass('huy');
                number_of_du_an_da_chon=parseInt($.trim($("#number_of_du_an_da_chon").html()));
                if(action=='chonduan'){
                    number_of_du_an_da_chon++;
                    $(node).html('Hủy chọn');
                }
                else{
                    number_of_du_an_da_chon--;
                    $(node).html('Chọn dự án');
                }
                
                $("#number_of_du_an_da_chon").html(number_of_du_an_da_chon);
                $(node).parents('.dt-content').toggleClass('selected');
                $(node).parents('.cate-item-i').toggleClass('selected');
            }
        });
   });
});
</script>
