<?php 
$auth = Zend_Auth::getInstance();
$items = $this->items;
$quangcao_items = $this->quangcao_items;
$du_an_cap_2s = $this->du_an_cap_2s;
$du_an_cap_2_selected = $this->du_an_cap_2_selected;
?>
<div class="page-content category-page">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="ct-sidebar">
                    <!-- Menu side -->
                    <div class="menu-side">
                        <ul class="mn-parent-side">
                            <?php 
                            foreach ($du_an_cap_2s as $du_an_cap_2){
                                if($du_an_cap_2['id']==$du_an_cap_2_selected){
                                    $class=' class="_current"';
                                }
                                else{
                                    $class='';
                                }?>
                                <li<?php echo $class;?>>
                                    <a href="<?php echo $this->baseUrl('/index/duan/muc/'.$this->muc.'/muccap2/'.$du_an_cap_2['id']);?>"><span><?php echo $du_an_cap_2['name'];?></span></a>
                                </li>
                            <?php 
                            } 
                            ?>
                            
                        </ul>
                    </div>
                    <!-- End Menu side -->
                    <?php if (!$this->isLogin) {?>
                    <p class="login login-p">
                        <a class="a-login" href="<?php echo $this->baseUrl();?>/default/account/login">Đăng nhập</a>
                        <a href="<?php echo $this->baseUrl();?>/default/account/regist">Đăng ký tài khoản</a>
                    </p>
                    <?php } ?>
                    <!-- Banner 1 side -->
                    <?php // echo $this->render('index/dichvuhaumaisidebar.phtml'); ?>
                    <!-- End Banner 2 side -->
                </div>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-8">
                <div class="content-cate">
                    <?php 
                    if(is_array($quangcao_items)&&count($quangcao_items)>0){?>
                    <div class="cate-ad">
                        <div class="cate-ad-wr">
                            <div class="cate-ad-heading">
                                TIN QUẢNG CÁO
                            </div>
                            <div id="cate-ad-slider" class="cate-ad-list">
                                <?php echo $this->render('index/duanquangcao.phtml'); ?>
                            </div>
                        </div>
                    </div>
                    <?php 
                    }
                    ?>
                    <ul class="cate-tabs">
                        <!-- Tab link -->
                        <?php 
                        echo $this->tab($this->tab,array(
                                                        $this->baseUrl('/index/duan/'.$this->mucGet.'/tab/tatCa/'.$this->mucCap2Get),
                                                        $this->baseUrl('/index/duan/'.$this->mucGet.'/tab/nhanVien/'.$this->mucCap2Get),
                                                        $this->baseUrl('/index/duan/'.$this->mucGet.'/tab/doiTac/'.$this->mucCap2Get),
                                                        $this->baseUrl('/index/duan/'.$this->mucGet.'/tab/khachHang/'.$this->mucCap2Get),
                                                    ));
                        ?>
                        <!-- End Tab link -->
                        <!-- Tab show -->
                        <!--tuetc tạm gác cái này lại-->
<!--                        <li class="tab-show">
                            <ul class="ct-display list-show">
                                <li><a class="i-display _current" data-display="_ct_list"  href="#cate_display"><i class="fa fa-th-list" aria-hidden="true"></i></a></li>
                                <li><a class="i-display" data-display="_ct_grid" data-container="cate_display" href="#cate_display"><i class="fa fa-th-large" aria-hidden="true"></i></a></li>
                            </ul>
                        </li>-->
                        <!-- End Tab show -->
                    </ul>
                    <div class="cate-list">
                        <!-- Wrap cate Add _ct_grid to show grid -->
                        <div id="cate_display" class="cate-wr"> 
                            <!-- Item cate -->
                            <?php 
                            if(is_array($items)&& count($items)>0){
                                foreach ($items as $item){
                                    ?>
                                    <div class="cate-item">
                                        <div class="cate-item-i<?php if($this->isLogin&&in_array($item['id'], $this->du_an_da_chon_ids)) echo ' selected'; if(isset($item['is_hot'])&&$item['is_hot']=='1') echo ' hot';?>">
                                            <div class="cit-part cit-left">
                                                    <img src="<?php echo $this->baseUrl($item['photo']); ?>">
                                                <span class="cit-mark"> <?php echo $item['tong_dau_tu'];?></span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title">
                                                    <a href="<?php echo $this->baseUrl("/index/duandetail/id/".$item['id']);?>">
                                                        
                                                        <?php if(isset($item['is_hot'])&&$item['is_hot']=='1'){?>
                                                        <span class="tap-hot">Hot</span>
                                                        <?php } ?>
                                                            <?php echo $item['title'];?>
                                                    </a>
                                                </div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Ngày đăng tin: <?php echo $item['created_at'];?></p>
                                                        <p class="cdes-main">Thời gian thi công: <?php echo $item['ngay'];?></p>
                                                        <p>
                                                            <?php 
                                                            if($item['allow_hoptac']!='1'){
                                                                if($item['type']== Default_Model_User::NHAN_VIEN||$item['type']== Default_Model_User::ADMIN){
                                                                    echo 'Nhân viên';
                                                                }
                                                                else if($item['type']== Default_Model_User::CA_NHAN){
                                                                    echo 'Cá nhân';
                                                                }
                                                                else if($item['type']== Default_Model_User::DOI_TAC){
                                                                    echo 'Đối tác';
                                                                }
                                                            }
                                                            else{
                                                                if($item['type_active']== Default_Model_User::NHAN_VIEN){
                                                                    echo 'Nhân viên';
                                                                }
                                                                else if($item['type_active']== Default_Model_User::CA_NHAN){
                                                                    echo 'Cá nhân';
                                                                }
                                                                else if($item['type_active']== Default_Model_User::DOI_TAC){
                                                                    echo 'Đối tác';
                                                                }
                                                            }
                                                            
                                                            ?>
                                                        </p>
                                                        <p>Mã tin: <?php echo 'DA'.$item['id'];?></p>
                                                        <p>Số người xem: <?php echo $item['so_luot_xem'];?></p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <?php 
                                                        if ($this->isLogin) {
                                                            if(!in_array($item['id'], $this->du_an_da_chon_ids)){
                                                            ?>
                                                            <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id'];?>" class="cit-btn chon_du_an"><span>Chọn</span></a>
                                                        <?php 
                                                            }
                                                            else{?>
                                                             <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id'];?>" class="cit-btn chon_du_an huy">Hủy chọn</a>   
                                                            <?php 
                                                            }
                                                        }
                                                        else{
                                                            if(!$this->isLogin){
                                                            ?>
                                                            <a href="<?php echo $this->baseUrl();?>/default/account/login" class="cit-btn"><span>Chọn</span></a>
                                                        <?php    
                                                            }
                                                            
                                                        }
                                                        ?>
                                                        
                                                    </div>
                                                    <?php echo $this->vote($item['id'],'du_an',(!in_array($item['id'], array_keys($this->voteDuans))?0:$this->voteDuans[$item['id']]));?>
                                                </div>
<!--                                                <ul class="fix-share fix-share-d">
                                                       
                                                    <?php echo $this->render('index/share.phtml'); ?>
                                                </ul>-->
                                            </div>
                                        </div>
                                    </div>
                            <?php 
                                }
                            }
                            ?>
                            
                            <!-- End cate item -->
                            
                        </div>
                        <!-- End wrap cate -->
                        <form method="post" action="<?php echo $this->url(); ?>">
                            <div class="ct-paginate cate-paginate">
                                    <?php if ($this->total > $this->limit) { ?>
                                        <?php echo $this->paginationControl($this->paginator, 'Sliding', array('_partials/paginator.phtml', 'default')); ?>
                                        <?php
                                    }
                                    ?>
                            </div>
                        </form>
                    </div>
                    <?php // echo $this->render('index/dichvuhaumaisidebarmobile.phtml'); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(function ($){
    
   $(".chon_du_an").click(function (){
       node=$(this);
        if(!$(this).hasClass('huy')){
            action='chonduan';
        }
        else{
            action='huychonduan';
        }
        id=$(this).attr('id').replace("chon_du_an_","");
        
        $.ajax({
            url:'<?php echo $this->baseUrl();?>/default/news/'+action,
            data: {'tin_du_an_id':id},                         
            type: 'post',
            async: false,
            success: function(php_script_response){
                $(node).toggleClass('huy');
                if($.trim(php_script_response)=='ok'){
                    number_of_du_an_da_chon=parseInt($.trim($("#number_of_du_an_da_chon").html()));
                    if(action=='chonduan'){
                        number_of_du_an_da_chon++;
                        $(node).html('Hủy chọn');
                    }
                    else{
                        number_of_du_an_da_chon--;
                        $(node).html('Chọn');
                    }
                    $("#number_of_du_an_da_chon").html(number_of_du_an_da_chon);
                    $("#number_of_du_an_da_chon_mobile").html(number_of_du_an_da_chon);
                    
                }
                $(node).parents('.dt-content').toggleClass('selected');
                $(node).parents('.cate-item-i').toggleClass('selected');
                if($(node).parents('.dt-content').find('.tap-hot').length>0){
                    if($(node).parents('.dt-content').hasClass('selected')){
                        $(node).parents('.dt-content').removeClass('hot');
                    }
                    else{
                        $(node).parents('.dt-content').addClass('hot');
                    }
                }
                if($(node).parents('.cate-item-i').find('.tap-hot').length>0){
                    if($(node).parents('.cate-item-i').hasClass('selected')){
                        $(node).parents('.cate-item-i').removeClass('hot');
                    }
                    else{
                        $(node).parents('.cate-item-i').addClass('hot');
                    }
                }

            }
        });
   });
});
</script>