<?php 
$items = $this->items;
$auth = Zend_Auth::getInstance();
$identity = $auth->getIdentity();
if ($auth->hasIdentity() && ($identity['type'] == Default_Model_User::KHACH_HANG || $identity['type'] == Default_Model_User::DOI_TAC)) {
    $number_du_an_da_chon = Core_Db_Table::getDefaultAdapter()->fetchCol("select count(*) from du_an_da_chon where user_id='" . $identity['id'] . "' and tin_du_an_id='" . $items[0]['id'] . "'");
    $number_du_an_da_chon = $number_du_an_da_chon[0];
}
?>
<div class="page-content detail-page category-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ct-breadcrumb">
                    <ul>
                        <li><a>DANGTINXAYDUNG</a></li>
                        <li><a>Dự án</a></li>
                        <?php 
                        if(trim($items[0]['du_an_cap_1'])!=''){
                            echo '<li><a>'.$items[0]['du_an_cap_1'].'</a></li>';
                        }
                        
                        if(trim($items[0]['du_an_cap_2'])!=''){
                            echo '<li><a>'.$items[0]['du_an_cap_2'].'</a></li>';
                        }
                        
                        ?>
                    </ul>
                </div>
            </div>
            <div class="col-md-12">
                <!-- Detail Infor -->
                <div class="dt-info">
                    <div class="dt-thumb">
                        <div class="dt-main-thumb">
                            <div class="ct-replace-img">
                                <?php 
                                if($items[0]['photo']!=''){?>
                                    <img src="<?php echo $this->baseUrl('/uploads/'.$items[0]['photo']);?>" alt="">
                                <?php 
                                }
                                else{?>
                                    <img src="<?php echo $this->baseUrl(PHOTO_DEFAULT);?>" alt="">
                                <?php 
                                }
                                ?>
                            </div>
                        </div>
                        <?php if(count($items)>1&&$items[0]['photo']!=''&&$items[1]['photo']!=''){?>
                        <div class="dt-chip-thumb">
                            <div class="chip-thumb chip-thumb-slider">
                                <?php 
                                //ít nhất user phải upload 2 ảnh, thi mới cho hiển thị vùng này
                                if(count($items)>1&&$items[0]['photo']!=''&&$items[1]['photo']!=''){
                                    foreach ($items as $item){
                                        if($item['photo']!=''){?>
                                            <div class="chip-thumb-pi">
                                                <div class="chip-thumb-i" data-image="<?php echo $this->baseUrl('/uploads/'.$item['photo']);?>">
                                                    <img style="width: 100%;height: auto;position: absolute;top: 50%;margin-top: -20px;left: 50%;margin-left: -20px;" src="<?php echo $this->baseUrl('/uploads/'.$item['photo']);?>" alt="">
                                                </div>
                                            </div>
                                <?php 
                                        }
                                    }
                                }
                                ?>
                            </div>
                        </div>
                        <?php 
                        } ?>
                        <div class="dt-share">
                            <div class="dt-t show-pc">Chia sẻ dự án tới:</div>
                            <ul class="dt-li-share">
                                    <li>
                                        <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://www.facebook.com/sharer.php?u=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                    </li>
                                    <li>

                                        <a class="zalo-share-button sc-RefOD bjSTUc" data-href="https://demo.com#xtatc=INT-5-[share_ad_via_zalo]" data-oaid="570044068386186227" data-layout="2" data-color="blue" data-customize="true">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/social/zalo.svg" height="40" width="40" alt="share button">
                                        </a>
                                    </li>
                                    <li>

                                        <a class="zalo-share-button sc-RefOD bjSTUc" data-href="https://demo.com#xtatc=INT-5-[share_ad_via_zalo]" data-oaid="570044068386186227" data-layout="2" data-color="blue" data-customize="true">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/social/messenger.svg" height="40" width="40" alt="share button">
                                        </a>
                                    </li>

                                    <li>
                                        <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://twitter.com/share?text=testcanlam&url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                        <span>Twitter</span>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0)" onclick="javascript:genericSocialShare('https://plus.google.com/share?url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                        <span>Google+</span>
                                    </li>

                            </ul>
                            <p class="note-detail show-pc"><?php echo nl2br($items[0]['content']);?></p>
                            <!-- login sp -->
                            <p class="login login-p" style="background: #E8E8E8; margin-bottom: 0;">
                                <a class="a-login" href="<?php echo $this->baseUrl();?>/default/account/login">Đăng nhập</a>
                                <a href="<?php echo $this->baseUrl();?>/default/account/regist">Đăng ký tài khoản</a>
                            </p>
                        </div>
                    </div>
                    <div class="dt-content<?php if($auth->hasIdentity()&&($identity['type']== Default_Model_User::KHACH_HANG||$identity['type']== Default_Model_User::DOI_TAC)&&isset($number_du_an_da_chon)&&$number_du_an_da_chon!='0') echo ' selected';else if(isset($items[0]['is_hot'])&&$items[0]['is_hot']=='1') echo ' hot';?>">
                        <div class="dt-title">
                            <a>
                                <?php 
                                if(isset($items[0]['is_hot'])&&$items[0]['is_hot']=='1'){?>
                                <span class="tap-hot">Hot</span>
                                <?php } ?>
                                <?php echo $items[0]['title'];?>
                            </a>
                            <?php 
                            if ($auth->hasIdentity()&&($identity['type']== Default_Model_User::KHACH_HANG||$identity['type']== Default_Model_User::DOI_TAC)) {
                                if(isset($number_du_an_da_chon)&&$number_du_an_da_chon=='0'){
                                ?>
                                <a style="cursor: pointer;" id="chon_du_an_<?php echo $items[0]['id'];?>" class="cit-btn chon_du_an">Chọn dự án</a>
                            <?php 
                                }
                                else{?>
                                 <a style="cursor: pointer;" id="chon_du_an_<?php echo $items[0]['id'];?>" class="cit-btn chon_du_an huy">Hủy chọn</a>   
                                <?php 
                                }
                            }
                            else{
                                if(!$auth->hasIdentity()){
                                ?>
                                <a href="<?php echo $this->baseUrl();?>/default/account/login" class="cit-btn"><span>Chọn dự án</span></a>
                            <?php    
                                }
                                
                            }
                            ?>
                        </div>
                        <div class="dt-desc">
                            <?php echo nl2br($items[0]['content']);?>
                        </div>
                        <div class="dt-pos">
                            <div class="dt-pos-l">
                                <p>Ngày đăng tin: <?php echo $items[0]['created_at'];?></p>
                                <p>Thời gian thi công: <?php echo $items[0]['ngay'];?></p>
                                <p>&nbsp;</p>
                            </div>
                            <div class="dt-pos-r">
                                <p>Khu vực</p>
                                <p>
                                    <?php 
                                    echo $items[0]['city_cap_1'];
                                    if($items[0]['city_cap_2']!=''){
                                        echo ' - '.$items[0]['city_cap_2'];
                                    }
                                    if($items[0]['city_cap_3']!=''){
                                        echo ' - '.$items[0]['city_cap_3'];
                                    }
                                    ?>
                                </p>
                            </div>
                        </div>
                        <div class="dt-cast">
                            <ul>
                                <?php 
                                $du_an_cap_3s=$this->du_an_cap_3s;
                                if(is_array($du_an_cap_3s)&&count($du_an_cap_3s)>0){
                                    foreach ($du_an_cap_3s as $du_an_cap_3){
                                        echo '<li><a>'.$du_an_cap_3['name'].'</a></li>';
                                    }
                                }
                                $du_an_cap_4s=$this->du_an_cap_4s;
                                if(is_array($du_an_cap_4s)&&count($du_an_cap_4s)>0){
                                    foreach ($du_an_cap_4s as $du_an_cap_4){
                                        echo '<li><a>'.$du_an_cap_4['name'].'</a></li>';
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                        <div class="dt-btn">
                            <div class="dt-btn-cl">
                                <div class="dt-mark">
                                    Đầu tư: <?php echo $items[0]['tong_dau_tu'];?>
                                </div>
                            </div>
                            <?php 
                            if(!$auth->hasIdentity()){
                                ?>                            
                                <div class="dt-btn-cl">
                                    <div class="dt-phone">
                                          <div onclick="showPhoneList();" class="ct-btn-phone ct-btn-mobile"><a style="cursor: pointer;">Gọi điện</a></div>                                          
                                    </div>
                                </div>
                            <?php 
                            }
                            else{
                                if($identity['id']==$items[0]['user_id']){?>
                                    <div class="dt-btn-cl">
                                        <div class="dt-phone">
                                              <div style="opacity: 0.3;cursor: not-allowed;" class="ct-btn-phone ct-btn-mobile"><a style="cursor: pointer;">Gọi điện</a></div>
                                        </div>
                                    </div>

                            <?php 
                            
                                }
                                else{
                                    if($identity['type']== Default_Model_User::ADMIN){?>
                                        <div class="dt-btn-cl">
                                            <div class="dt-phone">
                                                <div class="ct-btn-phone ct-btn-mobile"><?php echo $items[0]['phone'];?></div>                                                    
                                            </div>
                                        </div>
                                    <?php                                     
                                    }
                                    else if($identity['type']== Default_Model_User::NHAN_VIEN){
                                        if(in_array($items[0]['du_an_cap_1_id'], $identity['du_an_cap_1_ids'])){?>
                                            <div class="dt-btn-cl">
                                                <div class="dt-phone">
                                                    <div class="ct-btn-phone ct-btn-mobile"><?php echo $items[0]['phone'];?></div>                                                    
                                                </div>
                                            </div>
                                    <?php 
                                        }
                                    }
                                    else{?>
                                        <div class="dt-btn-cl">
                                            <div class="dt-phone">
                                                  <div onclick="showPhoneList();" class="ct-btn-phone ct-btn-mobile"><a style="cursor: pointer;">Gọi điện</a></div>
                                            </div>
                                        </div>
                            <?php 
                                    }
                                }
                            }
                            ?>
                        </div>
                        <div class="dt-share dt-share-mobile">
                            <div class="dt-t">Chia sẻ dự án tới:</div>
                            <ul class="dt-li-share">
                                <li>
                                    <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://www.facebook.com/sharer.php?u=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-messenger.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://twitter.com/share?text=testcanlam&url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" onclick="javascript:genericSocialShare('https://plus.google.com/share?url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-link.png" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End detail Infor -->

            </div>
        </div>
    </div>
    <?php 
    $items_lienquan=$this->items_lienquan;
    if(is_array($items_lienquan)&&count($items_lienquan)>0){
    ?>
    <div class="detail-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Detail Retated post -->
                    <div class="dt-related content-cate">
                        <div class="dt-rl-head">
                            <h4>Các bài viết liên quan</h4>
                        </div>
                        <div class="dt-rl-cate cate-list">
                            <div class="cate-wr _ct_grid">
                                
                                <?php 
                                
                                foreach ($items_lienquan as $item){
                                    if($item['photo']==''){
                                        $item['photo']=$this->baseUrl(PHOTO_DEFAULT);
                                    }
                                    else{
                                        $item['photo']=$this->baseUrl("/uploads/".$item['photo']);
                                    }
                                    ?>
                                    
                                
                                    <div class="cate-item">
                                        <div class="cate-item-i<?php if($auth->hasIdentity()&&($identity['type']== Default_Model_User::KHACH_HANG||$identity['type']== Default_Model_User::DOI_TAC)&&in_array($item['id'], $this->du_an_da_chon_ids)) echo ' selected';else if(isset($item['is_hot'])&&$item['is_hot']=='1') echo ' hot';?>">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $item['photo']; ?>">
                                                <span class="cit-mark">Đầu tư: <?php echo $item['tong_dau_tu'];?></span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title">
                                                    <a href="<?php echo $this->baseUrl("/index/duandetail/id/".$item['id']);?>">
                                                        <?php 
                                                        if(isset($item['is_hot'])&&$item['is_hot']=='1'){?>
                                                        <span class="tap-hot">Hot</span>
                                                        <?php } ?>
                                                            <?php echo $item['title'];?>
                                                    </a>
                                                </div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Ngày đăng tin: <?php echo $item['created_at'];?></p>
                                                        <p class="cdes-main">Thời gian thi công: <?php echo $item['ngay'];?></p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <?php 
                                                        if ($auth->hasIdentity()&&($identity['type']== Default_Model_User::KHACH_HANG||$identity['type']== Default_Model_User::DOI_TAC)) {
                                                            if(!in_array($item['id'], $this->du_an_da_chon_ids)){
                                                            ?>
                                                            <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id'];?>" class="cit-btn chon_du_an"><span>Chọn dự án</span></a>
                                                        <?php 
                                                            }
                                                            else{?>
                                                             <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id'];?>" class="cit-btn chon_du_an huy">Hủy chọn</a>   
                                                            <?php 
                                                            }
                                                        }
                                                        else{
                                                            if(!$auth->hasIdentity()){
                                                            ?>
                                                            <a href="<?php echo $this->baseUrl();?>/default/account/login" class="cit-btn"><span>Chọn dự án</span></a>
                                                        <?php    
                                                            }
                                                            
                                                        }
                                                        ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php 
                                    
                                }
                                
                                        
                                ?>
                            </div>
                        </div>
                    </div>
                    <!-- End Detail Retated post -->
                </div>
            </div>
        </div>
    </div>
    <?php 
    }
    ?>
</div>
<div id="phone_list" title="">
  <?php 
  $user_duan=$this->user_duan;
  if(is_array($user_duan)&&count($user_duan)>0){
      foreach ($user_duan as $temp){
          echo '<div style="padding: 10px;">'.$temp['full_name'].": ".$temp['phone'].'</div>';
      }
  }
  ?>
</div>
<link rel="stylesheet" href="<?php echo $this->baseUrl('/jquery-ui-1.10.3/themes/smoothness/jquery-ui.css'); ?>" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/jquery-ui.js"></script>          
<script type="text/javascript">
    function showPhoneList(){
        dialog_phone_list.dialog( "open" );
    }
    $(window).scroll(function(){
      var sticky = $('.dt-btn'),
          scroll = $(window).scrollTop();

      if (scroll >= 100) sticky.addClass('fixed-detail');
      else sticky.removeClass('fixed-detail');
    });

    // social share
    function genericSocialShare(url){
        window.open(url,'sharer','toolbar=0,status=0,width=648,height=395');
        return true;
    }
jQuery(function ($){
    dialog_phone_list=$( "#phone_list" ).dialog({
      autoOpen: false,
      show: {
        effect: "blind",
        duration: 1000
      },
      hide: {
        effect: "explode",
        duration: 1000
      }
    });
    
   if($(".dt-cast ul li").length<=3){
       $(".dt-cast ul li").css('width','auto');
   } 
   $(".chon_du_an").click(function (){
       node=$(this);
        if(!$(this).hasClass('huy')){
            action='chonduan';
        }
        else{
            action='huychonduan';
        }
        id=$(this).attr('id').replace("chon_du_an_","");
        
        $.ajax({
            url:'<?php echo $this->baseUrl();?>/default/news/'+action,
            data: {'tin_du_an_id':id},                         
            type: 'post',
            async: true,
            success: function(php_script_response){
                $(node).toggleClass('huy');
                number_of_du_an_da_chon=parseInt($.trim($("#number_of_du_an_da_chon").html()));
                if(action=='chonduan'){
                    number_of_du_an_da_chon++;
                    $(node).html('Hủy chọn');
                }
                else{
                    number_of_du_an_da_chon--;
                    $(node).html('Chọn dự án');
                }
                
                $("#number_of_du_an_da_chon").html(number_of_du_an_da_chon);
                $("#number_of_du_an_da_chon_mobile").html(number_of_du_an_da_chon);
                $(node).parents('.dt-content').toggleClass('selected');
                $(node).parents('.cate-item-i').toggleClass('selected');
                if($(node).parents('.dt-content').find('.tap-hot').length>0){
                    if($(node).parents('.dt-content').hasClass('selected')){
                        $(node).parents('.dt-content').removeClass('hot');
                    }
                    else{
                        $(node).parents('.dt-content').addClass('hot');
                    }
                }
                if($(node).parents('.cate-item-i').find('.tap-hot').length>0){
                    if($(node).parents('.cate-item-i').hasClass('selected')){
                        $(node).parents('.cate-item-i').removeClass('hot');
                    }
                    else{
                        $(node).parents('.cate-item-i').addClass('hot');
                    }
                }
                
            }
        });
   });
});
</script>
