<div class="page-content home-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12 home-tit">
                <h3 class="home-tit-o show-pc">KHÁM PHÁ DANH MỤC</h3>
                <?php $auth = Zend_Auth::getInstance(); if (!$this->isLogin) {?>
                <p class="login show-sp">
                    <a class="a-login" href="<?php echo $this->baseUrl();?>/default/account/login">Đăng nhập</a>
                    <a href="<?php echo $this->baseUrl();?>/default/account/regist">Đăng ký tài khoản</a>
                </p>
                <?php } ?>
            </div>
            <div class="col-xs-f col-xs-4 col-sm-5 col-md-4 col-md-opt">
                <div class="home-item item-large">
                    <a href="<?php echo $this->baseUrl();?>/index/nhathauthicong">
                        <img class="foreign" src="<?php echo $this->baseUrl(); ?>/front_end/images/icon/1.jpg" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/nha-thau-thi-cong-2.png" alt="">
                        <span>NHÀ THẦU THI CÔNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/dan-dung">
                        <img class="foreign" src="<?php echo $this->baseUrl(); ?>/front_end/images/icon/2.jpg" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/cau-duong.png" alt="">
                        <span>DÂN DỤNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/ha-tang">
                        <img class="foreign" src="<?php echo $this->baseUrl(); ?>/front_end/images/icon/3.jpg" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/ha-tang.png" alt="">
                        <span>HẠ TẦNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/cau-duong">
                        <img class="foreign" src="<?php echo $this->baseUrl(); ?>/front_end/images/icon/4.jpg" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/cau-duong.png" alt="">
                        <span>CẦU ĐƯỜNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/hoan-thien-noi-ngoai-that">
                        <img class="foreign foreign-w" src="<?php echo $this->baseUrl(); ?>/front_end/images/icon/5.jpg" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/hoan-thien-noi-ngoai-that.png" alt="">
                        <span>HOÀN THIỆN NỘI NGOẠI THẤT</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/kien-truc">
                        <img class="foreign" src="<?php echo $this->baseUrl(); ?>/front_end/images/icon/6.jpg" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/kien-truc.png" alt="">
                        <span>KIẾN TRÚC</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/dien-nuoc">
                        <img class="foreign" src="<?php echo $this->baseUrl(); ?>/front_end/images/icon/7.jpg" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/dien-nuoc.png" alt="">
                        <span>ĐIỆN NƯỚC</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/sua-chua">
                        <img class="foreign" src="<?php echo $this->baseUrl(); ?>/front_end/images/icon/8.jpg" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/sua-chua.png" alt="">
                        <span>SỬA CHỮA</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/cay-xanh">
                        <img class="foreign" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/layout-3/cay-xanh.png" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/cay-xanh.png" alt="">
                        <span>CÂY XANH</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/dich-vu-ve-sinh">
                        <img class="foreign" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/layout-3/dich-vu-ve-sinh.png" alt="">
                        <img class="bg" src="<?php echo $this->baseUrl(); ?>/front_end/images/home/dich-vu-ve-sinh.png" alt="">
                        <span>DỊCH VỤ VỆ SINH</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
