<div class="page-content home-page home-page-2">
    <div class="container">
        <div class="row">

            <div class="col-xs-f col-xs-12 col-sm-12 col-md-12 col-md-reverse">
                <div class="top-slider">
                    <?php 
                    $now=date('Y-m-d');
                    $dich_vu_hau_mais= Core_Db_Table::getDefaultAdapter()->fetchAll("select * from dich_vu_hau_mai where is_to_roi=1 or ('$now' between tu_ngay and den_ngay)");
                    if(is_array($dich_vu_hau_mais)&&count($dich_vu_hau_mais)>0){
                        foreach ($dich_vu_hau_mais as $dich_vu_hau_mai){
                            if($dich_vu_hau_mai['is_to_roi']=='1'){
                                $is_to_roi=' is_to_roi';
                            }
                            else{
                                $is_to_roi='';
                            }
                            ?>
                            <div class="home-item item-large item-slider dich_vu_hau_mai<?php echo $is_to_roi;?>" id="<?php echo $dich_vu_hau_mai['id'];?>">
                                <a>
                                    <img src="<?php echo $this->baseUrl('/uploads/'.$dich_vu_hau_mai['photo']);?>" alt="">
                                </a>
                            </div>
                    <?php 
                        }
                    }
                    ?>
                    
                </div>
            </div>
        </div>
        <p class="login login-c show-sp">
            <a class="a-login">Đăng nhập ngày</a>
            <a>Đăng ký tài khoản</a>
        </p>
        <div class="row row-custom">
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/nha-thau-thi-cong.png" alt="">
                        <span>NHÀ THẦU THI CÔNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/dan-dung.png" alt="">
                        <span>DÂN DỤNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/ha-tang.png" alt="">
                        <span>HẠ TẦNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-8">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/hoan-thien-noi-ngoai-that.png" alt="">
                        <span>HOÀN THIỆN NỘI NGOẠI THẤT</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/cau-duong.png" alt="">
                        <span>CẦU ĐƯỜNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/kien-truc.png" alt="">
                        <span>KIẾN TRÚC</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-8">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/sua-chua.png" alt="">
                        <span>SỬA CHỮA</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/dien-nuoc.png" alt="">
                        <span>ĐIỆN NƯỚC</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/cay-xanh.png" alt="">
                        <span>CÂY XANH</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="#">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/dich-vu-ve-sinh.png" alt="">
                        <span>DỊCH VỤ VỆ SINH</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>