<div class="page-content home-page">
    <div class="container">
        <div class="row">
            <div class="col-xs-f col-xs-8 col-sm-7 col-md-8 col-md-reverse">
                <div class="top-slider">
                    <div class="home-item item-large item-slider">
                        <a href="#">
                            <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/DVHM.png" alt="">
                        </a>
                    </div>
                    <div class="home-item item-large item-slider">
                        <a href="#">
                            <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/30_05_2018_11_34_51_LG-TV-690-300.png" alt="">
                        </a>
                    </div>
                </div>
            </div>
            <p class="login login-index show-sp">
                    <a class="a-login" href="<?php echo $this->baseUrl();?>/default/account/login">Đăng nhập</a>
                    <a href="<?php echo $this->baseUrl();?>/default/account/regist">Đăng ký tài khoản</a>
            </p>
            <div class="col-xs-f col-xs-4 col-sm-5 col-md-4 col-md-opt">
                <div class="home-item item-large item-large480">
                    <a href="<?php echo $this->baseUrl();?>/index/nhathauthicong">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/nha-thau-thi-cong-2.png" alt="">
                        <span>NHÀ THẦU THI CÔNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/dan-dung">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/dan-dung.png" alt="">
                        <span>DÂN DỤNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/ha-tang">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/ha-tang.png" alt="">
                        <span>HẠ TẦNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/cau-duong">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/cau-duong.png" alt="">
                        <span>CẦU ĐƯỜNG</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/hoan-thien-noi-ngoai-that">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/hoan-thien-noi-ngoai-that.png" alt="">
                        <span>HOÀN THIỆN NỘI NGOẠI THẤT</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/kien-truc">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/kien-truc.png" alt="">
                        <span>KIẾN TRÚC</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/dien-nuoc">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/dien-nuoc.png" alt="">
                        <span>ĐIỆN NƯỚC</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/sua-chua">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/sua-chua.png" alt="">
                        <span>SỬA CHỮA</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/cay-xanh">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/cay-xanh.png" alt="">
                        <span>CÂY XANH</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-f col-xs-6 col-sm-6 col-md-4">
                <div class="home-item item-medium">
                    <a href="<?php echo $this->baseUrl();?>/index/duan/muc/dich-vu-ve-sinh">
                        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/home/dich-vu-ve-sinh.png" alt="">
                        <span>DỊCH VỤ VỆ SINH</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>