<?php 
$items = $this->items;
$quangcao_items = $this->quangcao_items;
$mucs = $this->mucs;
$muc_selected = $this->muc_selected;
?>
<div class="page-content category-page">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="ct-sidebar">
                    <!-- Menu side -->
                    <div class="menu-side">
                        <ul class="mn-parent-side">
                            <?php 
                            foreach ($mucs as $muc){
                                if($muc['id']==$muc_selected){
                                    $class=' class="_current"';
                                }
                                else{
                                    $class='';
                                }?>
                                <li<?php echo $class;?>>
                                    <a href="<?php echo $this->baseUrl('/index/nhathauthicong/muc/'.$muc['id']);?>"><span><?php echo $muc['name'];?></span></a>
                                </li>
                            <?php 
                            } 
                            ?>
                        </ul>
                    </div>
                    <!-- End Menu side -->
                    <?php if (!$this->isLogin) {?>
                    <p class="login login-p">
                        <a class="a-login" href="<?php echo $this->baseUrl();?>/default/account/login">Đăng nhập</a>
                        <a href="<?php echo $this->baseUrl();?>/default/account/regist">Đăng ký tài khoản</a>
                    </p>
                    <?php } ?>
                    <?php // echo $this->render('index/dichvuhaumaisidebar.phtml'); ?>
                </div>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-8">
                <div class="content-cate">
                    <?php 
                    if(is_array($quangcao_items)&&count($quangcao_items)>0){?>
                    <div class="cate-ad">
                        <div class="cate-ad-wr">
                            <div class="cate-ad-heading">
                                TIN QUẢNG CÁO
                            </div>
                            <div id="cate-ad-slider" class="cate-ad-list">
                                <?php echo $this->render('index/nhathauquangcao.phtml'); ?>
                                
                            </div>
                        </div>
                    </div>
                    <?php 
                    }
                    ?>
                    <ul class="cate-tabs">
                        <!-- Tab link -->
                        <?php 
                        echo $this->tab($this->tab,array(
                                                        $this->baseUrl('/index/nhathauthicong/tab/tatCa/'.$this->mucGet),
                                                        $this->baseUrl('/index/nhathauthicong/tab/nhanVien/'.$this->mucGet),
                                                        $this->baseUrl('/index/nhathauthicong/tab/doiTac/'.$this->mucGet),
                                                        $this->baseUrl('/index/nhathauthicong/tab/khachHang/'.$this->mucGet),
                                                    ));
                        ?>
                        <!-- End Tab link -->
                        <!-- Tab show -->
                        <!--tuetc tạm gác cái này lại-->
<!--                        <li class="tab-show">
                            <ul class="ct-display list-show">
                                <li><a class="i-display _current" data-display="_ct_list"  href="#cate_display"><i class="fa fa-th-list" aria-hidden="true"></i></a></li>
                                <li><a class="i-display" data-display="_ct_grid" data-container="cate_display" href="#cate_display"><i class="fa fa-th-large" aria-hidden="true"></i></a></li>
                            </ul>
                        </li>-->
                        <!-- End Tab show -->
                    </ul>
                    <div class="cate-list">
                        <!-- Wrap cate Add _ct_grid to show grid -->
                        <div id="cate_display" class="cate-wr"> 
                            <!-- Item cate -->
                            <?php 
                            
                            if(is_array($items)&& count($items)>0){
                                foreach ($items as $item){
                                    ?>
                                    <div class="cate-item">
                                        <div class="cate-item-i<?php if($this->isLogin&&in_array($item['id'], $this->nha_thau_da_chon_ids)) echo ' selected'; if(isset($item['is_hot'])&&$item['is_hot']=='1') echo ' hot';?>">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $this->baseUrl($item['photo']); ?>">
                                                <span class="cit-mark"><?php echo $item['dich_vu_thi_cong'];?></span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title">
                                                    <a href="<?php echo $this->baseUrl("/index/nhathauthicongdetail/id/".$item['id']);?>">
                                                        <?php 
                                                        if(isset($item['is_hot'])&&$item['is_hot']=='1'){?>
                                                        <span class="tap-hot">Hot</span>
                                                        <?php } ?>
                                                            <?php echo $item['title'];?>
                                                    </a>
                                                </div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Ngày đăng tin: <?php echo $item['created_at'];?></p>
                                                        <p class="cdes-main">Thời gian thi công: <?php echo $item['ngay'];?></p>
                                                        <p>
                                                            <?php 
                                                            if($item['phan_loai']=='1'){
                                                                echo 'Nhân viên';
                                                            }
                                                            else{
                                                                echo 'Đối tác';
                                                            }
                                                            ?>
                                                        </p>
                                                        <p>Mã tin: <?php echo 'NT'.$item['id'];?></p>
                                                        <p>Số người xem: <?php echo $item['so_luot_xem'];?></p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <?php 
                                                        if ($this->isLogin){
                                                            if(!in_array($item['id'], $this->nha_thau_da_chon_ids)){
                                                            ?>
                                                            <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id'];?>" class="cit-btn chon_du_an"><span>Chọn</span></a>
                                                        <?php 
                                                            }
                                                            else{?>
                                                             <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id'];?>" class="cit-btn chon_du_an huy"><span>Hủy chọn</span></a>   
                                                            <?php 
                                                            }
                                                        }
                                                        else{
                                                            if(!$this->isLogin){
                                                            ?>
                                                            <a href="<?php echo $this->baseUrl();?>/default/account/login" class="cit-btn"><span>Chọn</span></a>
                                                        <?php    
                                                            }
                                                            
                                                        }
                                                        ?>
                                                    </div>
                                                    <?php echo $this->vote($item['id'],'nha_thau_thi_cong',(!in_array($item['id'], array_keys($this->voteNhathaus))?0:$this->voteNhathaus[$item['id']]));?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            <?php 
                                }
                            }
                            ?>
                            
                            <!-- End cate item -->
                            
                        </div>
                        <!-- End wrap cate -->
                        <form method="post" action="<?php echo $this->url(); ?>">
                            <div class="ct-paginate cate-paginate">
                                    <?php if ($this->total > $this->limit) { ?>
                                        <?php echo $this->paginationControl($this->paginator, 'Sliding', array('_partials/paginator.phtml', 'default')); ?>
                                        <?php
                                    }
                                    ?>
                            </div>
                        </form>
                    </div>
                    <?php // echo $this->render('index/dichvuhaumaisidebarmobile.phtml'); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(function ($){
    
   $(".chon_du_an").click(function (){
       node=$(this);
        if(!$(this).hasClass('huy')){
            action='chonnhathau';
        }
        else{
            action='huychonnhathau';
        }
        id=$(this).attr('id').replace("chon_du_an_","");
        
        $.ajax({
            url:'<?php echo $this->baseUrl();?>/default/news/'+action,
            data: {'tin_nha_thau_thi_cong_id':id},                         
            type: 'post',
            async: false,
            success: function(php_script_response){
                $(node).toggleClass('huy');
                if($.trim(php_script_response)=='ok'){
                    if(action=='chonnhathau'){
                        $(node).html('<span>Hủy chọn</span>');
                    }
                    else{
                        $(node).html('<span>Chọn</span>');
                    }
                    
                }
                $(node).parents('.dt-content').toggleClass('selected');
                $(node).parents('.cate-item-i').toggleClass('selected');
//                if($(node).parents('.dt-content').find('.tap-hot').length>0){
//                    if($(node).parents('.dt-content').hasClass('selected')){
//                        $(node).parents('.dt-content').removeClass('hot');
//                    }
//                    else{
//                        $(node).parents('.dt-content').addClass('hot');
//                    }
//                }
//                if($(node).parents('.cate-item-i').find('.tap-hot').length>0){
//                    if($(node).parents('.cate-item-i').hasClass('selected')){
//                        $(node).parents('.cate-item-i').removeClass('hot');
//                    }
//                    else{
//                        $(node).parents('.cate-item-i').addClass('hot');
//                    }
//                }

            }
        });
   });
});
</script>