<?php 
$auth = Zend_Auth::getInstance();
$identity = $auth->getIdentity();
$items = $this->items;
$quangcao_items = $this->quangcao_items;
$mucs = $this->mucs;
$muc_selected = $this->muc_selected;
?>
<div class="page-content category-page">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="ct-sidebar">
                    <!-- Menu side -->
                    <div class="menu-side">
                        <ul class="mn-parent-side1">
                            <?php 
                            foreach ($mucs as $muc){
                                if($muc['id']==$muc_selected){
                                    $class=' class="_current"';
                                }
                                else{
                                    $class='';
                                }?>
                                <li<?php echo $class;?>>
                                    <a href="<?php echo $this->baseUrl('/index/nhathauthicong/muc/'.$muc['id']);?>"><span><?php echo $muc['name'];?></span></a>
                                </li>
                            <?php 
                            } 
                            ?>
<!--                            <li class="_current">
                                <a  href="#"><span>Phần thô</span></a>
                                <div class="mn-dropdown-side">
                                    <div class="btn-back-parent"></div>
                                    <ul>
                                        <li><a href="#">Thạch cao</a></li>
                                        <li><a href="#">Chống thấm</a></li>
                                        <li><a href="#">Sơn</a></li>
                                        <li><a href="#">Điện nước</a></li>
                                        <li><a href="#">Hệ thống MI</a></li>
                                        <li><a href="#">Thiết bị vệ sinh</a></li>
                                        <li><a href="#">Nhà bếp</a></li>
                                    </ul>
                                    <ul>
                                        <li><a href="#">Thạch cao</a></li>
                                        <li><a href="#">Chống thấm</a></li>
                                        <li><a href="#">Sơn</a></li>
                                        <li><a href="#">Điện nước</a></li>
                                        <li><a href="#">Hệ thống MI</a></li>
                                        <li><a href="#">Thiết bị vệ sinh</a></li>
                                        <li><a href="#">Nhà bếp</a></li>
                                    </ul>
                                </div>
                            </li>-->
                            
                        </ul>
                    </div>
                    <!-- End Menu side -->
                    <!-- Banner 1 side -->
                    <div class="banner-side banner-1">
                        <div class="banner-wr">
                            <span>BANNER</span>
                            DỊCH VỤ HẬU MÃI
                        </div>
                    </div>
                    <!-- End Banner 1 side -->
                    <!-- Banner 2 side -->
                    <div class="banner-side banner-2">
                        <div class="banner-wr">
                            <span>BANNER</span>
                            TUYỂN DỤNG
                        </div>
                    </div>
                    <!-- End Banner 2 side -->
                </div>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-8">
                <div class="content-cate">
                    <?php 
                    if(is_array($quangcao_items)&&count($quangcao_items)>0){?>
                    <div class="cate-ad">
                        <div class="cate-ad-wr">
                            <div class="cate-ad-heading">
                                TIN QUẢNG CÁO
                            </div>
                            <div id="cate-ad-slider" class="cate-ad-list">
                                <?php 
                                foreach ($quangcao_items as $item){
                                    if($item['photo']==''){
                                        $item['photo']=$this->baseUrl('/front_end/images/category/cacti-gardening-grow-707194.png');
                                    }
                                    else{
                                        $item['photo']=$this->baseUrl("/uploads/".$item['photo']);
                                    }
                                    ?>
                                    <div class="cate-ad-i">
                                        <div class="cate-ad-ii">
                                            <div class="cai-thumb">
                                                <img src="<?php echo $item['photo']; ?>" alt="">
                                            </div>
                                            <div class="cai-tit">
                                                <a href="<?php echo $this->baseUrl("/index/duandetail/id/".$item['id']);?>"><?php echo $item['title']; ?></a>
                                            </div>
                                            <div class="cai-desc">
                                                <div class="cai-col cai-cl">
                                                    <!--<p>Tổng đầu tư: <span></span></p>-->
                                                    <p class="cai-phone"><a><?php echo $item['phone'];?></a></p>
                                                </div>
                                                <div class="cai-col cai-cr">
                                                    <?php 
//                                                            if ($auth->hasIdentity()&&($identity['type']== Default_Model_User::KHACH_HANG||$identity['type']== Default_Model_User::DOI_TAC)) {
//                                                                if(!in_array($item['id'], $this->du_an_da_chon_ids)){
                                                        ?>
                                                        <!--<a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id'];?>" class="cai-btn-project chon_du_an"></a>-->
                                                    <?php 
//                                                                }
//                                                            }
//                                                            else{
//                                                                if(!$auth->hasIdentity()){
                                                        ?>
                                                        <!--<a href="<?php echo $this->baseUrl();?>/account/login" class="cai-btn-project"></a>-->
                                                    <?php    
//                                                                }
//
//                                                            }
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php 
                                }
                                ?>
                                
                            </div>
                        </div>
                    </div>
                    <?php 
                    }
                    ?>
                    <ul class="cate-tabs">
                        <!-- Tab link -->
                        <li class="tab-link">
                            <ul class="list-link">
                                <li><a class="tab-link-i<?php if($this->tab=='tatCa') echo ' _current';?>"<?php if($this->allCount>0) echo ' href="'.$this->baseUrl('/index/nhathauthicong/tab/tatCa/'.$this->mucGet).'"';?>>Tất cả(<?php echo $this->allCount;?>)</a></li>
                                <li><a class="tab-link-i<?php if($this->tab=='nhanVien') echo ' _current';?>"<?php if($this->nhanVienCount>0) echo ' href="'.$this->baseUrl('/index/nhathauthicong/tab/nhanVien/'.$this->mucGet).'"';?>>Nhân viên(<?php echo $this->nhanVienCount;?>)</a></li>
                                <li><a class="tab-link-i<?php if($this->tab=='doiTac') echo ' _current';?>"<?php if($this->doiTacCount>0) echo ' href="'.$this->baseUrl('/index/nhathauthicong/tab/doiTac/'.$this->mucGet).'"';?>>Đối tác(<?php echo $this->doiTacCount;?>)</a></li>
                                <li><a class="tab-link-i<?php if($this->tab=='khachHang') echo ' _current';?>"<?php if($this->khachHangCount>0) echo ' href="'.$this->baseUrl('/index/nhathauthicong/tab/khachHang/'.$this->mucGet).'"';?>>Cá nhân(<?php echo $this->khachHangCount;?>)</a></li>
                            </ul>
                        </li>
                        <!-- End Tab link -->
                        <!-- Tab show -->
                        <li class="tab-show">
                            <ul class="ct-display list-show">
                                <li><a class="i-display _current" data-display="_ct_list"  href="#cate_display"><i class="fa fa-th-list" aria-hidden="true"></i></a></li>
                                <li><a class="i-display" data-display="_ct_grid" data-container="cate_display" href="#cate_display"><i class="fa fa-th-large" aria-hidden="true"></i></a></li>
                            </ul>
                        </li>
                        <!-- End Tab show -->
                    </ul>
                    <div class="cate-list">
                        <!-- Wrap cate Add _ct_grid to show grid -->
                        <div id="cate_display" class="cate-wr"> 
                            <!-- Item cate -->
                            <?php 
                            
                            if(is_array($items)&& count($items)>0){
                                foreach ($items as $item){
                                    if($item['photo']==''){
                                        $item['photo']=$this->baseUrl('/front_end/images/category/cacti-gardening-grow-707194.png');
                                    }
                                    else{
                                        $item['photo']=$this->baseUrl("/uploads/".$item['photo']);
                                    }
                                    ?>
                                    <div class="cate-item">
                                        <div class="cate-item-i">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $item['photo']; ?>" alt="#">
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title">
                                                    <a href="<?php echo $this->baseUrl("/index/nhathauthicongdetail/id/".$item['id']);?>">
                                                        <!--<span class="tap-hot">Hot</span>tuetc-->
                                                            <?php echo $item['title'];?>
                                                    </a>
                                                </div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Thời gian thi công: <?php echo $item['ngay'];?></p>
                                                        <p>
                                                            <?php 
                                                            if($item['phan_loai']=='1'){
                                                                echo 'Nhân viên';
                                                            }
                                                            else{
                                                                echo 'Đối tác';
                                                            }
                                                            ?>
                                                        </p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <!--tuetc-->
                                                        <!--<a href="#" class="cit-btn"><span>Chọn dự án</span></a>-->
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            <?php 
                                }
                            }
                            ?>
                            
                            <!-- End cate item -->
                            
                        </div>
                        <!-- End wrap cate -->
                        <!-- Cate paginate -->
                        <!--tuetc-->
<!--                        <div class="ct-paginate cate-paginate">
                            <ul>
                                <li class="pg-prev"><a href="#" title="Trước đó"></a></li>
                                <li><a href="#">1</a></li>
                                <li class="active"><span>2</span></li>
                                <li><span class="unlink">...</span></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li class="pg-next"><a href="#" title="Tiếp theo"></a></li>
                            </ul>
                        </div>-->
                        <!-- End Cate paginate -->
                        <form method="post" action="<?php echo $this->url(); ?>">
                            <div class="ct-paginate cate-paginate">
                                    <?php if ($this->total > $this->limit) { ?>
                                        <?php echo $this->paginationControl($this->paginator, 'Sliding', array('_partials/paginator.phtml', 'default')); ?>
                                        <?php
                                    }
                                    ?>
                            </div>
                        </form>
                    </div>
                    <div class="ct-ad-mobile">
                        <div class="ct-ad-mobile-i">
                            <span>BANNER</span> DỊCH VỤ HẬU MÃI
                        </div>
                        <div class="ct-ad-mobile-i">
                            <span>BANNER</span> DỊCH VỤ HẬU MÃI
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

