<?php 
$items = $this->items;
$auth = Zend_Auth::getInstance();
$identity = $auth->getIdentity();
?>
<div class="page-content detail-page category-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ct-breadcrumb">
                    <ul>
                        <li><a>DANGTINXAYDUNG</a></li>
                        <li><a>Nhà thầu thi công</a></li>
                        <?php 
                        if(trim($items[0]['nha_thau_thi_cong_cap_1'])!=''){
                            echo '<li><a>'.$items[0]['nha_thau_thi_cong_cap_1'].'</a></li>';
                        }
                        
                        if(trim($items[0]['nha_thau_thi_cong_cap_2'])!=''){
                            echo '<li><a>'.$items[0]['nha_thau_thi_cong_cap_2'].'</a></li>';
                        }
                        
                        ?>
                    </ul>
                </div>
            </div>
            <div class="col-md-12">
                <!-- Detail Infor -->
                <div class="dt-info">
                    <div class="dt-thumb">
                        <div class="show-pc">
                            <div class="dt-main-thumb">
                                    <?php 
                                    if($items[0]['photo']!=''){?>
                                        <img src="<?php echo $this->baseUrl('/uploads/'.$items[0]['photo']);?>" alt="">
                                    <?php 
                                    }
                                    else{?>
                                        <img src="<?php echo $this->baseUrl(PHOTO_DEFAULT);?>" alt="">
                                    <?php 
                                    }
                                    ?>
                            </div>
                        </div>
                        <div class="show-sp">
                            <div class="top-slider" style="margin-top: 6px;">                                
                                <?php 
                                if(count($items)>0){
                                    foreach ($items as $item){
                                        if($item['photo']==''){
                                            $item['photo']=PHOTO_DEFAULT;
                                        }
                                        else{
                                            $item['photo']='/uploads/'.$item['photo'];
                                        }
                                        ?>
                                        <div class="home-item item-large item-slider">
                                             <a href="#">
                                                <img src="<?php echo $this->baseUrl($item['photo']);?>" alt="">
                                            </a>
                                        </div>                                        
                                <?php                                         
                                    }
                                }
                                ?>
                            </div>
                        </div>
                        <?php if(count($items)>1&&$items[0]['photo']!=''&&$items[1]['photo']!=''){?>
                        <div class="dt-chip-thumb">
                            <div class="chip-thumb chip-thumb-slider">
                                <?php 
                                //ít nhất user phải upload 2 ảnh, thi mới cho hiển thị vùng này
                                if(count($items)>1&&$items[0]['photo']!=''&&$items[1]['photo']!=''){
                                    foreach ($items as $item){
                                        if($item['photo']!=''){?>
                                            <div class="chip-thumb-pi">
                                                <div class="chip-thumb-i" data-image="<?php echo $this->baseUrl('/uploads/'.$item['photo']);?>">
                                                    <img style="width: 100%;height: auto;position: absolute;top: 50%;margin-top: -20px;left: 50%;margin-left: -20px;" src="<?php echo $this->baseUrl('/uploads/'.$item['photo']);?>" alt="">
                                                </div>
                                            </div>
                                <?php 
                                        }
                                    }
                                }
                                ?>
                            </div>
                        </div>
                        <?php 
                        }
                        ?>
                        <div class="dt-share">
                            <div class="dt-t show-pc">Chia sẻ tới:</div>
                            <ul class="dt-li-share">
                                    <li>
                                        <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://canlam.vn<?php echo $this->url();?>')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                    </li>
                                    <li>

                                        <a class="zalo-share-button sc-RefOD bjSTUc" data-href="https://demo.com#xtatc=INT-5-[share_ad_via_zalo]" data-oaid="570044068386186227" data-layout="2" data-color="blue" data-customize="true">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/social/zalo.svg" height="40" width="40" alt="share button">
                                        </a>
                                    </li>
                                    <li>

                                        <a class="zalo-share-button sc-RefOD bjSTUc" data-href="https://demo.com#xtatc=INT-5-[share_ad_via_zalo]" data-oaid="570044068386186227" data-layout="2" data-color="blue" data-customize="true">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/social/messenger.svg" height="40" width="40" alt="share button">
                                        </a>
                                    </li>

                                    <li>
                                        <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://twitter.com/share?text=testcanlam&url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                        <span>Twitter</span>
                                    </li>
                                    <li>
                                        <a href="javascript:void(0)" onclick="javascript:genericSocialShare('https://plus.google.com/share?url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                        <span>Google+</span>
                                    </li>

                            </ul>
                            <p class="note-detail show-pc"><?php echo NOI_DUNG_HUONG_DAN;?></p>
                            <!-- login sp -->
                            <p class="login login-p" style="background: #E8E8E8; margin-bottom: 0;">
                                <a class="a-login" href="<?php echo $this->baseUrl();?>/default/account/login">Đăng nhập</a>
                                <a href="<?php echo $this->baseUrl();?>/default/account/regist">Đăng ký tài khoản</a>
                            </p>
                        </div>

                    </div>
                    <div class="dt-content">
                        <div class="dt-title">
                            <a>
                                <?php 
                                if(isset($items[0]['is_hot'])&&$items[0]['is_hot']=='1'){?>
                                <span class="tap-hot">Hot</span>
                                <?php } ?>
                                <?php echo $items[0]['title'];?>
                            </a>
                        </div>
                        <div class="dt-desc">
                            <?php echo nl2br($items[0]['content']);?>
                        </div>
                        <div class="dt-pos">
                            <div class="dt-pos-l">
                                <p>Ngày đăng tin: <?php echo $items[0]['created_at'];?></p>
                                <p>Thời gian thi công: <?php echo $items[0]['ngay'];?></p>
                                <p>
                                    <?php 
                                    if($items[0]['phan_loai']=='1'){
                                        echo 'Nhân viên';
                                    }
                                    else{
                                        echo 'Đối tác';
                                    }
                                    ?>
                                </p>
                            </div>
                            <div class="dt-pos-r">
                                <p>Khu vực</p>
                                <p>
                                    <?php 
                                    echo $items[0]['city_cap_1'];
                                    if($items[0]['city_cap_2']!=''){
                                        echo ' - '.$items[0]['city_cap_2'];
                                    }
                                    if($items[0]['city_cap_3']!=''){
                                        echo ' - '.$items[0]['city_cap_3'];
                                    }
                                    ?>
                                </p>
                            </div>
                        </div>
                        <div class="dt-cast">
                            <ul>
                                <?php 
                                $nha_thau_thi_cong_cap_3s=$this->nha_thau_thi_cong_cap_3s;
                                if(is_array($nha_thau_thi_cong_cap_3s)&&count($nha_thau_thi_cong_cap_3s)>0){
                                    foreach ($nha_thau_thi_cong_cap_3s as $nha_thau_thi_cong_cap_3){
                                        echo '<li><a>'.$nha_thau_thi_cong_cap_3['name'].'</a></li>';
                                    }
                                }
                                
                                $nha_thau_thi_cong_cap_4s=$this->nha_thau_thi_cong_cap_4s;
                                if(is_array($nha_thau_thi_cong_cap_4s)&&count($nha_thau_thi_cong_cap_4s)>0){
                                    foreach ($nha_thau_thi_cong_cap_4s as $nha_thau_thi_cong_cap_4){
                                        echo '<li><a>'.$nha_thau_thi_cong_cap_4['name'].'</a></li>';
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                        <div class="dt-btn">
                            <?php 
                            if(!$auth->hasIdentity()){
                                ?>                            
                                <div class="dt-btn-cl">
                                    <div class="dt-phone">
                                          <div class="ct-btn-phone ct-btn-mobile"  data-toggle="modal" data-target="#phoneModal">
                                              <a style="cursor: pointer;">Gọi điện</a>
                                          </div>                                          
                                    </div>
                                </div>
                            <?php 
                            }
                            else{
                                if($identity['id']==$items[0]['user_id']){?>
                                    <div class="dt-btn-cl">
                                        <div class="dt-phone">
                                              <div style="opacity: 0.3;cursor: not-allowed;" class="ct-btn-phone ct-btn-mobile"><a style="cursor: pointer;">Gọi điện</a></div>
                                        </div>
                                    </div>
                                <?php 
                                }
                                else{
                                    if($identity['type']== Default_Model_User::ADMIN){?>
                                        <div class="dt-btn-cl">
                                            <div class="dt-phone">
                                                <div class="ct-btn-phone ct-btn-mobile"><?php echo $items[0]['phone'];?></div>                                                    
                                            </div>
                                        </div>
                                    <?php                                     
                                    }
                                    else if($identity['type']== Default_Model_User::NHAN_VIEN){
                                        if(in_array($items[0]['nha_thau_thi_cong_cap_1_id'], $identity['nha_thau_thi_cong_cap_1_ids'])){?>
                                            <div class="dt-btn-cl">
                                                <div class="dt-phone">
                                                    <div class="ct-btn-phone ct-btn-mobile"><?php echo $items[0]['phone'];?></div>                                                    
                                                </div>
                                            </div>
                                    <?php 
                                        }
                                    }
                                    else{?>
                                        <div class="dt-btn-cl">
                                            <div class="dt-phone">
                                                  <div class="ct-btn-phone ct-btn-mobile"  data-toggle="modal" data-target="#phoneModal">
                                                      <a style="cursor: pointer;">Gọi điện</a>
                                                  </div>
                                            </div>
                                        </div>
                            <?php 
                                    }
                                }
                            }
                            ?>
                        </div>
                        <div class="dt-share dt-share-mobile">
                            <div class="dt-t">Chia sẻ dự án tới:</div>
                            <ul class="dt-li-share">
                                <li>
                                    <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://canlam.vn<?php echo $this->url();?>')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-messenger.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://twitter.com/share?text=testcanlam&url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)" onclick="javascript:genericSocialShare('https://plus.google.com/share?url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-link.png" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End detail Infor -->

            </div>
        </div>
    </div>
    <?php 
    $items_lienquan=$this->items_lienquan;
    if(is_array($items_lienquan)&&count($items_lienquan)>0){
    ?>
    <div class="detail-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Detail Retated post -->
                    <div class="dt-related content-cate">
                        <div class="dt-rl-head">
                            <h4>Các bài viết liên quan</h4>
                        </div>
                        <div class="dt-rl-cate cate-list">
                            <div class="cate-wr _ct_grid">
                                <?php 
                                if(is_array($items_lienquan)&& count($items_lienquan)>0){
                                    foreach ($items_lienquan as $item){
                                        if($item['photo']==''){
                                            $item['photo']=$this->baseUrl(PHOTO_DEFAULT);
                                        }
                                        else{
                                            $item['photo']=$this->baseUrl("/uploads/".$item['photo']);
                                        }
                                        ?>
                                        <div class="cate-item">
                                            <div class="cate-item-i<?php if(isset($item['is_hot'])&&$item['is_hot']=='1') echo ' hot';?>">
                                                <div class="cit-part cit-left">
                                                    <img src="<?php echo $item['photo']; ?>">
                                                </div>
                                                <div class="cit-part cit-right">
                                                    <div class="cit-title">
                                                        <a href="<?php echo $this->baseUrl("/index/nhathauthicongdetail/id/".$item['id']);?>">
                                                            <?php 
                                                        if(isset($item['is_hot'])&&$item['is_hot']=='1'){?>
                                                        <span class="tap-hot">Hot</span>
                                                        <?php } ?>
                                                                <?php echo $item['title'];?>
                                                        </a>
                                                    </div>
                                                    <div class="cit-desc">
                                                        <div class="cit-desc-l">
                                                            <p class="cdes-main">Ngày đăng tin: <?php echo $item['created_at'];?></p>
                                                            <p class="cdes-main">Thời gian thi công: <?php echo $item['ngay'];?></p>
                                                            <p>
                                                                <?php 
                                                                if($item['phan_loai']=='1'){
                                                                    echo 'Nhân viên';
                                                                }
                                                                else{
                                                                    echo 'Đối tác';
                                                                }
                                                                ?>
                                                            </p>
                                                        </div>
                                                        <div class="cit-desc-r">
                                                            &nbsp;
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                <?php 
                                    }
                                }
                                ?>
                                
                            </div>
                        </div>
                    </div>
                    <!-- End Detail Retated post -->
                </div>
            </div>
        </div>
    </div>
    <?php 
    }
    ?>
</div>

<div class="modal fade" id="phoneModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="text-align: center;">&nbsp;</h4>
            </div>
            <div class="modal-body">
                <ul>
                      <?php 
                      $user_duan=$this->user_duan;
                      if(is_array($user_duan)&&count($user_duan)>0){
                          foreach ($user_duan as $temp){?>
                              <li><a href="tel:+<?php echo $temp['phone'];?>"><?php echo $temp['phone'].' ('.$temp['full_name'].')';?></a></li>
                      <?php 
                          }
                      }
                      ?>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>

    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->baseUrl('/jquery-ui-1.10.3/themes/smoothness/jquery-ui.css'); ?>" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/jquery-ui.js"></script> 
<script type="text/javascript">
    
    $(window).scroll(function(){
      var sticky = $('.dt-btn'),
          scroll = $(window).scrollTop();

      if (scroll >= 100) sticky.addClass('fixed-detail');
      else sticky.removeClass('fixed-detail');
    });
    // social share
    function genericSocialShare(url){
        window.open(url,'sharer','toolbar=0,status=0,width=648,height=395');
        return true;
    }
jQuery(function ($){
    
    
   if($(".dt-cast ul li").length<=3){
       $(".dt-cast ul li").css('width','auto');
   } 
});
</script>

