<?php 
$items = $this->items;
?>
<div class="page-content detail-page category-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ct-breadcrumb">
                    <ul>
                        <li><a>DANGTINXAYDUNG</a></li>
                        <li><a>Nhà thầu thi công</a></li>
                        <?php 
                        echo '<li><a>'.$items[0]['nha_thau_thi_cong_cap_1'].'</a></li>';
                        echo '<li><a>'.$items[0]['nha_thau_thi_cong_cap_2'].'</a></li>';
                        echo '<li><a>'.$items[0]['nha_thau_thi_cong_cap_3'].'</a></li>';
                        ?>
                    </ul>
                </div>
            </div>
            <div class="col-md-12">
                <!-- Detail Infor -->
                <div class="dt-info">
                    <div class="dt-thumb">
                        <div class="dt-main-thumb">
                            <div class="ct-replace-img">
                                <?php 
                                if($items[0]['photo']!=''){?>
                                    <img style="width: 100%;height: auto;" src="<?php echo $this->baseUrl('/uploads/'.$items[0]['photo']);?>" alt="">
                                <?php 
                                }
                                else{?>
                                    <img src="<?php echo $this->baseUrl();?>/front_end/images/category-detail/cate-detail-main.png" alt="">
                                <?php 
                                }
                                ?>
                            </div>
<!--                            tuetc
                            <span>03</span>-->
                        </div>
                        <div class="dt-chip-thumb">
                            <div class="chip-thumb chip-thumb-slider">
                                <?php 
                                //ít nhất user phải upload 2 ảnh, thi mới cho hiển thị vùng này
                                if(count($items)>1&&$items[0]['photo']!=''&&$items[1]['photo']!=''){
                                    foreach ($items as $item){
                                        if($item['photo']!=''){?>
                                            <div class="chip-thumb-pi">
                                                <div class="chip-thumb-i" data-image="<?php echo $this->baseUrl();?>/front_end/images/home/active-adults-bars-583392 2.png">
                                                    <img style="width: 100%;height: auto;" src="<?php echo $this->baseUrl('/uploads/'.$item['photo']);?>" alt="">
                                                </div>
                                            </div>
                                <?php 
                                        }
                                    }
                                }
                                ?>
                            </div>
                        </div>
                        <div class="dt-share">
                            <div class="dt-t">Chia sẻ dự án tới:</div>
                            <ul class="dt-li-share">
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                    <span>Facebook</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-messenger.png" alt=""></a>
                                    <span>Messenger</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                    <span>Twitter</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                    <span>Google+</span>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-link.png" alt=""></a>
                                    <span>Link</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="dt-content">
                        <div class="dt-title">
                            <a><?php echo $items[0]['title'];?></a>
                            <!--tuetc-->
                            <!--<a href="#" class="cit-btn">Chọn dự án</a>-->
                        </div>
                        <div class="dt-desc">
                            <?php echo $items[0]['content'];?>
                        </div>
                        <div class="dt-pos">
                            <div class="dt-pos-l">
                                <p>Thời gian thi công: <?php echo $items[0]['ngay'];?></p>
<!--                                tuetc
                                <p>Cộng tác viên</p>-->
                                <p>
                                    <?php 
                                    if($items[0]['phan_loai']=='1'){
                                        echo 'Nhân viên';
                                    }
                                    else{
                                        echo 'Đối tác';
                                    }
                                    ?>
                                </p>
                            </div>
                            <div class="dt-pos-r">
                                <p>Khu vực</p>
                                <p>
                                    <?php 
                                    echo $items[0]['city_cap_1'];
                                    if($items[0]['city_cap_2']!=''){
                                        echo ' - '.$items[0]['city_cap_2'];
                                    }
                                    if($items[0]['city_cap_3']!=''){
                                        echo ' - '.$items[0]['city_cap_3'];
                                    }
                                    ?>
                                </p>
                            </div>
                        </div>
                        <div class="dt-cast">
                            <ul>
                                <?php 
                                
                                $nha_thau_thi_cong_cap_4s=$this->nha_thau_thi_cong_cap_4s;
                                if(is_array($nha_thau_thi_cong_cap_4s)&&count($nha_thau_thi_cong_cap_4s)>0){
                                    foreach ($nha_thau_thi_cong_cap_4s as $nha_thau_thi_cong_cap_4){
                                        echo '<li><a>'.$nha_thau_thi_cong_cap_4['name'].'</a></li>';
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                        <div class="dt-btn">
                            <!--tuetc-->
<!--                            <div class="dt-btn-cl">
                                <div class="dt-mark">
                                    Tổng đầu tư: <?php // echo $items[0]['tong_dau_tu'];?>
                                </div>
                            </div>-->
                            <div class="dt-btn-cl">
                                <div class="dt-phone">
                                    <!--  <div id="click_show_phone" class="ct-btn-phone" data-number="01228559193">Nhấn để hiện số hoặc để lại tin nhắn</div> -->
                                    <div class="ct-btn-phone ct-btn-mobile"><a href="tel:01228559193">Gọi điện</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="dt-share dt-share-mobile">
                            <div class="dt-t">Chia sẻ dự án tới:</div>
                            <ul class="dt-li-share">
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-fb.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-messenger.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-twitter.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-google.png" alt=""></a>
                                </li>
                                <li>
                                    <a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/social/icon-link.png" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End detail Infor -->
                <!-- Detail Banner -->
                <div class="dt-banner">
                    <div class="dt-ls-banner dt-banner-slider">
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                        <!-- Banner Item -->
                        <div class="dt-banner-i">
                            <div class="dt-banner-wr">
                                <span>Banner</span> dịch vụ hậu mãi
                            </div>
                        </div>
                        <!-- End Banner Item -->
                    </div>
                </div>
                <!-- End Detail Banner -->

            </div>
        </div>
    </div>
    <div class="detail-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Detail Retated post -->
                    <div class="dt-related content-cate">
                        <div class="dt-rl-head">
                            <h4>Các bài viết liên quan</h4>
                        </div>
                        <div class="dt-rl-cate cate-list">
                            <div class="cate-wr _ct_grid">
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#"><span class="tap-hot">Hot</span>Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main p-opening">Đang thi công</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                                <!-- Cate Item -->
                                <div class="cate-item">
                                    <div class="cate-item-i">
                                        <div class="cit-part cit-left">
                                            <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png" alt="#">
                                            <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                        </div>
                                        <div class="cit-part cit-right">
                                            <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                            <div class="cit-desc">
                                                <div class="cit-desc-l">
                                                    <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                    <p>Cộng tác viên</p>
                                                </div>
                                                <div class="cit-desc-r">
                                                    <a href="#" class="cit-btn"><span>Chọn dự án</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Item -->
                            </div>
                        </div>
                    </div>
                    <!-- End Detail Retated post -->
                </div>
            </div>
        </div>
    </div>
    <div class="ct-ad-mobile">
        <div class="ct-ad-mobile-i">
            <span>BANNER</span> DỊCH VỤ HẬU MÃI
        </div>
        <div class="ct-ad-mobile-i">
            <span>BANNER</span> DỊCH VỤ HẬU MÃI
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(function ($){
   if($(".dt-cast ul li").length<=3){
       $(".dt-cast ul li").css('width','auto');
   } 
});
</script>

