<li>
    <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://canlam.vn<?php echo $this->url(); ?>')"><img src="<?php echo $this->baseUrl(); ?>/front_end/images/social/icon-fb.png" alt=""></a>
</li>
<li>

    <a class="zalo-share-button sc-RefOD bjSTUc" data-href="https://demo.com#xtatc=INT-5-[share_ad_via_zalo]" data-oaid="570044068386186227" data-layout="2" data-color="blue" data-customize="true">
        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/social/zalo.svg" height="40" width="40" alt="share button">
    </a>
</li>
<li>

    <a class="zalo-share-button sc-RefOD bjSTUc" data-href="https://demo.com#xtatc=INT-5-[share_ad_via_zalo]" data-oaid="570044068386186227" data-layout="2" data-color="blue" data-customize="true">
        <img src="<?php echo $this->baseUrl(); ?>/front_end/images/social/messenger.svg" height="40" width="40" alt="share button">
    </a>
</li>

<li>
    <a href="javascript:void(0)" onclick="javascript:genericSocialShare('http://twitter.com/share?text=testcanlam&url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl(); ?>/front_end/images/social/icon-twitter.png" alt=""></a>
    <span>Twitter</span>
</li>
<li>
    <a href="javascript:void(0)" onclick="javascript:genericSocialShare('https://plus.google.com/share?url=https://www.google.com/maps')"><img src="<?php echo $this->baseUrl(); ?>/front_end/images/social/icon-google.png" alt=""></a>
    <span>Google+</span>
</li>
