<?php  
$quangcao_items = $this->quangcao_items;
if (is_array($quangcao_items) && count($quangcao_items) > 0) { ?>
    <div class="cate-ad">
        <div class="cate-ad-wr">
            <div class="cate-ad-heading">
                TIN QUẢNG CÁO
            </div>
            <div id="cate-ad-slider" class="cate-ad-list">
                <?php
                foreach ($quangcao_items as $item) {
                    if ($item['photo'] == '') {
                        $item['photo'] = $this->baseUrl(PHOTO_DEFAULT);
                    } else {
                        $item['photo'] = $this->baseUrl("/uploads/" . $item['photo']);
                    }
                    ?>
                    <div class="cate-ad-i">
                        <div class="cate-ad-ii">
                            <div class="cai-thumb">
                                <img src="<?php echo $item['photo']; ?>" alt="">
                            </div>
                            <div class="cai-tit">
                                <a href="<?php echo $this->baseUrl("/index/duandetail/id/" . $item['id']); ?>"><?php echo $item['title']; ?></a>
                            </div>
                            <div class="cai-desc">
                                <div class="cai-col cai-cl">
                                    <p> <span><?php echo $item['tong_dau_tu']; ?></span></p>
                                    <p class="cai-phone"><a><?php echo $item['phone']; ?></a></p>
                                </div>
                                <!--tuetc-->
                                <!--                                                tạm thời ẩn nút Chọn dự án tại các tin ở vùng quảng cáo-->
                                <!--                                                <div class="cai-col cai-cr">
        <?php
        if ($auth->hasIdentity()) {
            if (!in_array($item['id'], $this->du_an_da_chon_ids)) {
                ?>
                                                                                                <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id']; ?>" class="cai-btn-project chon_du_an">Chọn dự án</a>
                                        <?php 
                                    } else {
                                        ?>
                                                                                                 <a style="cursor: pointer;" id="chon_du_an_<?php echo $item['id']; ?>" class="cai-btn-project chon_du_an huy">Hủy chọn</a>   
                                        <?php 
                                    }
                                } else {
                                    if (!$auth->hasIdentity()) {
                                        ?>
                                                                                                <a href="<?php echo $this->baseUrl(); ?>/default/account/login" class="cai-btn-project"></a>
                                        <?php 
                                    }
                                }
                                ?>
                                                                                </div>-->
                            </div>
                        </div>
                    </div>
        <?php  
    }
    ?>
            </div>
        </div>
    </div>
                <?php 
            }
            ?>
