<div class="footer-top">
    <div class="container">
        <div class="row row-eq-height">
            <?php 
            if(!$this->isMobile){
            ?>
            <div class="col-xs-3 col-sm-3 col-md-3 col-ft-social">
                <div class="ft-block company-social">
                    <div class="ft-tit"><b>LIÊN KẾT</b></div>
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i>Facebook</a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i>Google+</a></li>
                        <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i>Youtube</a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i>Twitter</a></li>
                    </ul>
                </div>
            </div>
            <?php 
            }
            ?>
            <div class="col-xs-3 col-sm-3 col-md-3">
                <div class="ft-block">
                    <div class="ft-tit"><b>VỀ CÔNG TY</b></div>
                    <ul>
                        <li><a href="#">Giới thiệu</a></li>
                        <li><a href="#">Tuyển dụng</a></li>
                        <?php 
                        if(!$this->isMobile){
                        ?>
                        <li><a href="#">Blog</a></li>
                        <?php 
                        }
                        ?>
                    </ul>
                </div>
            </div>
            <?php 
            if(!$this->isMobile){
            ?>
            <div class="col-480-full col-xs-3 col-sm-3 col-md-3">
                <div class="ft-block">
                    <div class="ft-tit"><b>VỀ KHÁCH HÀNG</b></div>
                    <ul>
                        <li><a href="#">Chính sách quảng cáo</a></li>
                        <li><a href="#">Dịch vụ hậu mãi</a></li>
                        <li><a href="#">Bảo mật thông tin</a></li>
                    </ul>
                </div>
            </div>
            <?php 
            }
            ?>
            <div class="col-xs-3 col-sm-3 col-md-3">
                <div class="ft-block">
                    <div class="ft-img"><a href="#"><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/dadangky.png" alt=""></a></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End footer top -->
<!-- Footer bottom -->
<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="ftbt-i">
                    <div class="ftbt-col ftbt-left">
                        © 2018 Copyright by DungLV
                    </div>
                    <div class="ftbt-col ftbt-right">
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
