<div class="form-list">
    <div class="form-item">
        <div class="form-input form-text">
            <input name="q" type="text" placeholder="Nhập tìm kiếm..." class="focus-text" value="<?php if(isset($this->q)) echo trim($this->q); ?>">
        </div>
    </div>
    <div class="form-item">
        <ul class="form-right">
            <li>
                <div class="form-input form-select form-select-city">
                    <div class="input-nt" data-toggle="modal" data-target="#searchItem" id="selectItem"><?php if(isset($this->tenMuc)) echo $this->tenMuc; else echo 'Tất cả danh mục';?></div>
                    <input type="hidden" id="khu_vuc" name="muc" value="<?php if(isset($this->muc)&&$this->muc!='0') echo trim($this->muc); if(isset($this->mucCap2)&& ctype_digit($this->mucCap2)&&$this->mucCap2!='0') echo '_'.trim($this->mucCap2); if(isset($this->mucCap3)&& ctype_digit($this->mucCap3)&&$this->mucCap3!='0') echo '_'.trim($this->mucCap3); ?>" class="input-dropdown value-category"> 
                </div>
            </li>
            <li>
                <div class="form-input form-select form-select-city">
                    <div class="input-nt" data-toggle="modal" data-target="#searchCity" id="selectCity"><?php if(isset($this->tenKhuVuc)) echo $this->tenKhuVuc; else echo 'Khu vực';?></div>
                    <input type="hidden" id="city" name="city" value="<?php if(isset($this->city)&&$this->city!='0') echo trim($this->city); if(isset($this->cityCap2)&& ctype_digit($this->cityCap2)&&$this->cityCap2!='0') echo '_'.trim($this->cityCap2); ?>" class="input-dropdown value-category">
                </div>
            </li>
            <li class="btn-link search-button">
                <button class="ct-btn  btn-post">TÌM KIẾM <span></span></button>
            </li>
            <li class="btn-link">
                <a href="<?php echo $this->baseUrl();?>/default/news/step1" class="ct-btn  btn-post">ĐĂNG TIN CỦA BẠN</a>
            </li>
        </ul>
    </div>
</div>
