<div class="row">
    <div class="col-xs-3 col-sm-5 col-md-4 col-logo">
        <div class="top-logo">
            <div class="logo-link">
                <a href="/"><img class="logo" src="<?php echo $this->baseUrl();?>/front_end/images/icon/logo.png"></a>
            </div>
        </div>
    </div>
    <div class="col-xs-9 col-sm-7 col-md-8 col-opt">
        <div class="top-poc">
            <?php if(true || $this->action=='index'||$this->action=='search'||$this->controller=='news'){?>
                <?php if($this->action=='index'||$this->action=='search'){?>
                <a class="onClickSearch show-sp" href="#" id="onClickSearch"><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/icon-search.png" alt=""></a>
                <?php } ?>
                <div class="top-oc top-login" id="div_dangnhap_dangky1">
                    <a style="min-width: 100px;width: 100%;" href="javascript:void(0)" class="ct-btn onClickInformation"  data-bg=""><?php if (!$this->isLogin) {?>Đăng nhập/Đăng ký<?php } else echo $this->full_name!=''?$this->full_name:'Guest';?>&nbsp;</a>
                </div>

                <?php if (!$this->isLogin) {?>
                <ul class="show-information">
                    <li><a href="<?php echo $this->baseUrl();?>/default/account/login">Đăng nhập</a></li>
                    <li><a href="<?php echo $this->baseUrl();?>/default/account/regist">Đăng ký tài khoản</a></li>
                </ul>
                <?php }
                else{ ?>
                <ul class="show-information">
                    <li><a href="<?php echo $this->baseUrl();?>/default/account/logout">Đăng xuất</a></li>
                    <li><a href="<?php echo $this->baseUrl();?>/default/account/info">Thông tin cá nhân</a></li>
                    <li><a href="<?php echo $this->baseUrl();?>/default/account/newsuploaded">Các tin đã đăng</a></li>
                    <li><a href="<?php echo $this->baseUrl();?>/default/account/duanchon">Các dự án đã chọn</a></li>
                </ul>
                <?php 
                }
                ?>

                <?php if ($this->isLogin) {?>
                <div class="top-oc top-project">
                    <a href="<?php echo $this->baseUrl('/default/account/duanchon');?>" class="ct-btn" data-bg=""><text>Dự án đã chọn</text>
                        <?php if ($this->isLogin) {?>
                        <span id="number_of_du_an_da_chon"><?php echo $this->number_du_an_da_chon;?></span>
                        <?php } ?>
                    </a>
                </div>
                <?php } ?>
                
                <div class="top-oc top-post" id="div_dang_tin1">
                    <a href="<?php echo $this->baseUrl();?>/default/news/step1" class="ct-btn" data-bg=""><text>Đăng tin của bạn</text></a>
                </div>
                <a id="a_dang_tin1" href="<?php echo $this->baseUrl();?>/default/news/step1" class="dang-tin show-sp">Đăng tin</a>
            <?php 
            }
            else{
            ?>
                <!-- menu show cpc -->
                <div class="show-pc">
                    
                    <div class="top-oc top-login" id="div_dangnhap_dangky">
                        <a href="#" data-bg="" id="login_click"><?php if (!$this->isLogin) {?>Đăng nhập<?php } else echo $this->full_name!=''?$this->full_name:'Guest';?></a>
                    </div>
                    
                    <div class="top-oc top-project" id="div_du_an_da_chon">
                        <a href="<?php echo $this->baseUrl('/default/account/duanchon');?>" class="ct-btn" data-bg="">Dự án đã chọn
                            <span id="number_of_du_an_da_chon"><?php echo $this->number_du_an_da_chon;?></span>
                        </a>

                        <a href="<?php echo $this->baseUrl();?>/default/news/step1" class="ct-btn btn-post">ĐĂNG TIN CỦA BẠN</a>
                    </div>
                    <div class="oc-dropdown">
                        <?php if (!$this->isLogin) {?>
                        <ul>
                            <li><a href="<?php echo $this->baseUrl();?>/default/account/login">Đăng nhập</a></li>
                            <li><a href="<?php echo $this->baseUrl();?>/default/account/regist">Đăng ký tài khoản</a></li>
                        </ul>
                        <?php }
                        else{ ?>
                        <ul>
                            <li><a href="<?php echo $this->baseUrl();?>/default/account/logout">Đăng xuất</a></li>
                            <li><a href="<?php echo $this->baseUrl();?>/default/account/info">Thông tin cá nhân</a></li>
                            <li><a href="<?php echo $this->baseUrl();?>/default/account/newsuploaded">Các tin đã đăng</a></li>
                            <li><a href="<?php echo $this->baseUrl();?>/default/account/duanchon">Các dự án đã chọn</a></li>
                        </ul>
                        <?php 
                        }
                        ?>
                    </div>
                </div>
                <!-- menu show sp -->
                <div class="show-sp">
                    <?php if($this->action!='duan'&&$this->action!='nhathauthicong'&&$this->action!='login'&&$this->action!='regist'){?>
                    <a class="onClickSearch" href="#" id="onClickSearch"><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/icon-search.png" alt=""></a>
                    <?php 
                    }
                    ?>
                    <?php 
                    if($this->action!='login'&&$this->action!='regist'){
                    ?>
                    <div class="top-oc top-login">
                        <a class="ct-btn onClickInformation"  data-bg=""><text><?php if (!$this->isLogin) {?>Đăng nhập/Đăng ký<?php } else echo $this->full_name!=''?$this->full_name:'Guest';?></text></a>
                    </div>
                    <?php 
                    }
                    ?>
                    <!-- show thong tin da dang nhap -->
                    <?php if (!$this->isLogin) {?>
                    <ul class="show-information">
                        <li><a href="<?php echo $this->baseUrl();?>/default/account/login">Đăng nhập</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/default/account/regist">Đăng ký tài khoản</a></li>
                    </ul>
                    <?php }
                    else{ ?>
                    <ul class="show-information">
                        <li><a href="<?php echo $this->baseUrl();?>/default/account/logout">Đăng xuất</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/default/account/info">Thông tin cá nhân</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/default/account/newsuploaded">Các tin đã đăng</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/default/account/duanchon">Các dự án đã chọn</a></li>
                    </ul>
                    <?php 
                    }
                    ?>
                    
                    <!-- end -->
                    <div class="top-oc top-project" id="div_du_an_da_chon1">
                        <a href="<?php echo $this->baseUrl('/default/account/duanchon');?>" class="ct-btn" data-bg=""><text>Dự án đã chọn</text>
                            <span id="number_of_du_an_da_chon"><?php echo $this->number_du_an_da_chon;?></span>
                        </a>
                    </div>
                    
                    <!-- dang tin for pc -->
                    
                    <div class="top-oc top-post" id="div_dang_tin">
                        <a href="<?php echo $this->baseUrl();?>/default/news/step1" class="ct-btn" data-bg=""><text>Đăng tin của bạn</text></a>
                    </div>
                    <!-- dang tin for sp -->
                    <a id="a_dang_tin" href="<?php echo $this->baseUrl();?>/default/news/step1" class="dang-tin show-sp">Đăng tin</a>
                </div>
            <?php 
            }
            ?>
        </div>
    </div>
</div>
