<div class="page-content account-page category-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="pc-main">
                    <div class="pc-col pc-menu">
                        <ul>
                            <li><a href="<?php echo $this->baseUrl('/default/account/info');?>">Thông tin cá nhân</a></li>
                            <li><a href="<?php echo $this->baseUrl('/default/account/newsuploaded');?>">Các tin đã đăng</a></li>
                            <li class="_current"><a href="javascript:void(0)">Các dự án đã chọn</a></li>
                        </ul>
                    </div>
                    <div class="pc-col pc-info">
                        <div class="page-option content-cate">
                            <div class="cate-list">
                                <!-- Wrap cate Add _ct_grid to show grid -->
                                <div id="cate_display" class="cate-wr"> 
                                    <!-- Item cate -->
                                    <?php 
                                    $items=$this->items;
                                    if(is_array($items)&&count($items)>0){
                                        foreach ($items as $item){
                                            
                                            ?>
                                            <div class="cate-item">
                                                <div class="cate-item-i<?php if($this->isLogin&&in_array($item['id'], $this->du_an_da_chon_ids)) echo ' selected'; if(isset($item['is_hot'])&&$item['is_hot']=='1') echo ' hot';?>"<?php if($item['status']=='3') echo ' style="background: #c8cedd;"';?>>
                                                    <div class="cit-part cit-left">
                                                        <img src="<?php echo $this->baseUrl($item['photo']); ?>">
                                                        <span class="cit-mark"> <?php echo $item['tong_dau_tu'];?></span>
                                                    </div>
                                                    <div class="cit-part cit-right">
                                                        <div class="cit-title">
                                                            <a href="<?php echo $this->baseUrl("/index/duandetail/id/".$item['id']);?>">
                                                                <?php 
                                                        if(isset($item['is_hot'])&&$item['is_hot']=='1'){?>
                                                        <span class="tap-hot">Hot</span>
                                                        <?php } ?>
                                                                <?php echo $item['title'];?>
                                                            </a>
                                                        </div>
                                                        <div class="cit-desc">
                                                            <div class="cit-desc-l">
                                                                <p class="cdes-main">Ngày đăng tin: <?php echo $item['created_at'];?></p>
                                                                <p class="cdes-main">Thời gian thi công: <?php echo $item['ngay'];?></p>
                                                                <!--tuetc-->
                                                                <p>
                                                                    <?php 
                                                                    if($item['allow_hoptac']!='1'){
                                                                        if($item['type']== Default_Model_User::NHAN_VIEN||$item['type']== Default_Model_User::ADMIN){
                                                                            echo 'Nhân viên';
                                                                        }
                                                                        else if($item['type']== Default_Model_User::CA_NHAN){
                                                                            echo 'Cá nhân';
                                                                        }
                                                                        else if($item['type']== Default_Model_User::DOI_TAC){
                                                                            echo 'Đối tác';
                                                                        }
                                                                    }
                                                                    else{
                                                                        if($item['type_active']== Default_Model_User::NHAN_VIEN){
                                                                            echo 'Nhân viên';
                                                                        }
                                                                        else if($item['type_active']== Default_Model_User::CA_NHAN){
                                                                            echo 'Cá nhân';
                                                                        }
                                                                        else if($item['type_active']== Default_Model_User::DOI_TAC){
                                                                            echo 'Đối tác';
                                                                        }
                                                                    }

                                                                    ?>
                                                                </p>
                                                                <p>Mã tin: <?php echo 'DA'.$item['id'];?></p>
                                                                <p>Số người xem: <?php echo $item['so_luot_xem'];?></p>
                                                            </div>
                                                            
                                                            <?php if($item['status']=='3'){?>
                                                            <div class="cit-desc-r">
                                                                <a class="btn-green"><span>Đã hoàn thành giao dịch</span></a>
                                                            </div>
                                                            <?php }?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                    <?php                                             
                                        }
                                    }
                                    ?>
                                    
                                    <!-- End cate item -->
                                    
                                </div>
                                <!-- End wrap cate -->
                                <form method="post" action="<?php echo $this->url(); ?>">
                                    <div class="ct-paginate cate-paginate">
                                            <?php if ($this->total > $this->limit) { ?>
                                                <?php echo $this->paginationControl($this->paginator, 'Sliding', array('_partials/paginator.phtml', 'default')); ?>
                                                <?php
                                            }
                                            ?>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
