<div class="page-content account-page category-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="pc-main">
                    <div class="pc-col pc-menu">
                        <ul>
                            <li><a href="<?php echo $this->baseUrl('/default/account/info');?>">Thông tin cá nhân</a></li>
                            <li><a href="<?php echo $this->baseUrl('/default/account/newsuploaded');?>">Các tin đã đăng</a></li>
                            <li class="_current"><a href="javascript:void(0)">Các dự án đã chọn</a></li>
                        </ul>
                    </div>
                    <div class="pc-col pc-info">
                        <div class="page-option content-cate">
                            <div class="cate-list">
                                <!-- Wrap cate Add _ct_grid to show grid -->
                                <div id="cate_display" class="cate-wr"> 
                                    <!-- Item cate -->
                                    <?php 
                                    $items=$this->items;
                                    if(is_array($items)&&count($items)>0){
                                        foreach ($items as $item){
                                            if($item['photo']==''){
                                                $item['photo']=$this->baseUrl(PHOTO_DEFAULT);
                                            }
                                            else{
                                                $item['photo']=$this->baseUrl("/uploads/".$item['photo']);
                                            }
                                            ?>
                                            <div class="cate-item">
                                                <div class="cate-item-i">
                                                    <div class="cit-part cit-left">
                                                        <img style="width: 100%;height: auto;" src="<?php echo $item['photo']; ?>" alt="#">
                                                        <span class="cit-mark">Đầu tư: <?php echo $item['tong_dau_tu'];?></span>
                                                    </div>
                                                    <div class="cit-part cit-right">
                                                        <div class="cit-title">
                                                            <a href="<?php echo $this->baseUrl("/index/duandetail/id/".$item['id']);?>">
                                                                <!--tuetc-->
                                                                <!--<span class="tap-hot">Hot</span>-->
                                                                <?php echo $item['title'];?>
                                                            </a>
                                                        </div>
                                                        <div class="cit-desc">
                                                            <div class="cit-desc-l">
                                                                <p class="cdes-main">Thời gian thi công: <?php echo $item['ngay'];?></p>
                                                                <!--<p>Đối tác</p>-->
                                                            </div>
                                                            <!--tuetc-->
<!--                                                            <div class="cit-desc-r">
                                                                <a href="#" class="btn-green"><span>Khôi phục tin</span></a>
                                                            </div>-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                    <?php                                             
                                        }
                                    }
                                    ?>
                                    
                                    <!-- End cate item -->
                                    
                                </div>
                                <!-- End wrap cate -->
                                <form method="post" action="<?php echo $this->url(); ?>">
                                    <div class="ct-paginate cate-paginate">
                                            <?php if ($this->total > $this->limit) { ?>
                                                <?php echo $this->paginationControl($this->paginator, 'Sliding', array('_partials/paginator.phtml', 'default')); ?>
                                                <?php
                                            }
                                            ?>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
