<style>
    .password.hide{
        display: none;
    }
</style>
<div class="page-content account-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="pc-main">
                    <div class="pc-col pc-menu">
                        <ul>
                            <li class="_current"><a href="javascript:void(0)">Thông tin cá nhân</a></li>
                            <li><a href="<?php echo $this->baseUrl('/default/account/newsuploaded');?>">Các tin đã đăng</a></li>
                            <li><a href="<?php echo $this->baseUrl('/default/account/duanchon');?>">Các dự án đã chọn</a></li>
                        </ul>
                    </div>
                    <div class="pc-col pc-info">
                        <div class="page-option">
                            <div class="form-page">
                                <div class="fp-content">
                                    <div class="fp-group">
                                        <div class="fp-label">HỌ TÊN</div>
                                        <div class="fp-input fp-textbox">
                                            <input name="full_name" type="textbox" class="fp-control" placeholder="Họ tên">
                                        </div>
                                    </div>
                                    <div class="fp-group fp-phone">
                                        <div class="fp-label">SỐ ĐIỆN THOẠI</div>
                                        <div class="fp-input fp-textbox">
                                            <input name="phone" type="textbox" class="fp-control" placeholder="Số điện thoại">
                                        </div>
                                    </div>
                                    <div class="fp-group">
                                        <div class="fp-label">
                                            <label style="cursor: pointer;">
                                                <input type="checkbox" id="reset_password" class="fp-control">
                                                ĐẶT LẠI MẬT KHẨU
                                            </label>
                                        </div>
                                        <div class="fp-input fp-textbox">&nbsp;</div>
                                    </div>
                                    <div class="fp-group fp-phone password hide">
                                        <div class="fp-label">MẬT KHẨU CŨ</div>
                                        <div class="fp-input fp-textbox">
                                            <input name="old_password" type="password" class="fp-control" placeholder="Số điện thoại">
                                        </div>
                                    </div>
                                    <div class="fp-group fp-phone password hide">
                                        <div class="fp-label">MẬT KHẨU MỚI</div>
                                        <div class="fp-input fp-textbox">
                                            <input name="new_password" type="password" class="fp-control" placeholder="Số điện thoại">
                                        </div>
                                    </div>
                                    <div class="fp-group fp-phone password hide">
                                        <div class="fp-label">NHẬP LẠI MẬT KHẨU MỚI</div>
                                        <div class="fp-input fp-textbox">
                                            <input name="confirm_new_password" type="password" class="fp-control" placeholder="Số điện thoại">
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
jQuery(function ($){
   
   $("#reset_password").change(function (){
       $(".password").toggleClass('hide');
   });
});
</script>