<style>
    .password.hide{
        display: none;
    }
</style>
<form id="change_info" action="<?php echo $this->url();?>" method="POST" onsubmit="return false;">
<div class="page-content account-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="pc-main">
                    <div class="pc-col pc-menu">
                        <ul>
                            <li class="_current"><a href="javascript:void(0)">Thông tin cá nhân</a></li>
                            <li><a href="<?php echo $this->baseUrl('/default/account/newsuploaded');?>">Các tin đã đăng</a></li>
                            <li><a href="<?php echo $this->baseUrl('/default/account/duanchon');?>">Các dự án đã chọn</a></li>
                        </ul>
                    </div>
                    <div class="pc-col pc-info">
                        <div class="page-option">
                            <?php 
                            if(isset($this->message)&&$this->message=='Chúc mừng bạn đã thay đổi thông tin cá nhân thành công.'){
                                $color='blue';
                            }
                            else{
                                $color='red';
                            }
                            ?>
                            <h3 style="text-align: center;width: 100%;color: <?php echo $color;?>">
                                <?php if(isset($this->message)) echo $this->message;?>
                            </h3>
                            <div class="form-page">
                                <div class="fp-content">
                                    <div class="fp-group">
                                        <div class="fp-label">HỌ TÊN</div>
                                        <div class="fp-input fp-textbox">
                                            <input name="full_name" type="textbox" class="fp-control" placeholder="Họ tên" value="<?php if(isset($this->full_name)) echo $this->full_name;?>">
                                        </div>
                                    </div>
                                    <div class="fp-group fp-phone">
                                        <div class="fp-label">SỐ ĐIỆN THOẠI</div>
                                        <div class="fp-input fp-textbox">
                                            <input name="phone" type="textbox" class="fp-control" placeholder="Số điện thoại" value="<?php if(isset($this->phone)) echo $this->phone;?>">
                                        </div>
                                    </div>
                                    <div class="fp-group">
                                        <div class="fp-label fp-label-require">CHỌN LOẠI HÌNH</div>
                                        <div class="fp-input fp-tab">
                                            <div class="fp-tab-i">
                                                <div class="fp-tab-ii">
                                                    <input type="radio" name="type_active"<?php if($this->type_active== Default_Model_User::CA_NHAN){?> checked="checked"<?php }?> class="hd-check-tab" value="3">
                                                    <div class="fp-tab-select">
                                                        Cá nhân
                                                        <span class="fp-tab-check"></span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="fp-tab-i">
                                                <div class="fp-tab-ii">
                                                    <input type="radio" name="type_active"<?php if($this->type_active=='2'){?> checked="checked"<?php }?> class="hd-check-tab" value="2">
                                                    <div class="fp-tab-select">
                                                        Nhân viên
                                                        <span class="fp-tab-check"></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="fp-tab-i">
                                                <div class="fp-tab-ii">
                                                    <input type="radio" name="type_active"<?php if($this->type_active=='4'){?> checked="checked"<?php }?> class="hd-check-tab" value="4">
                                                    <div class="fp-tab-select">
                                                        Đối tác
                                                        <span class="fp-tab-check"></span>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                        </div>
                                        <div class="row" style="margin-top: 20px;display: none;">
                                            <div id="error1" class="col-lg-12 col-md-12" style='padding-bottom:20px;color: red;margin-bottom: 20px;text-align: center;'>
                                                Vui lòng chọn loại hình.
                                            </div>
                                        </div>   
                                    </div>
                                    <div class="fp-group">
                                        <div class="fp-label">
                                            <label style="cursor: pointer;">
                                                <input type="checkbox" value="1" name="reset_password" id="reset_password" class="fp-control">
                                                ĐẶT LẠI MẬT KHẨU
                                            </label>
                                        </div>
                                        <div class="fp-input fp-textbox">&nbsp;</div>
                                    </div>
                                    <div class="fp-group fp-phone password hide">
                                        <div class="fp-label">MẬT KHẨU CŨ</div>
                                        <div class="fp-input fp-textbox">
                                            <input id="old_password" name="old_password" type="password" class="fp-control" placeholder="Mật khẩu cũ">
                                        </div>
                                    </div>
                                    <div class="fp-group fp-phone password hide">
                                        <div class="fp-label">MẬT KHẨU MỚI</div>
                                        <div class="fp-input fp-textbox">
                                            <input id="new_password" name="new_password" type="password" class="fp-control" placeholder="Mật khẩu mới">
                                        </div>
                                    </div>
                                    <div class="fp-group fp-phone password hide">
                                        <div class="fp-label">NHẬP LẠI MẬT KHẨU MỚI</div>
                                        <div class="fp-input fp-textbox">
                                            <input id="confirm_new_password" name="confirm_new_password" type="password" class="fp-control" placeholder="Nhập lại mật khẩu mới">
                                        </div>
                                    </div>
                                    
                                    <div class="fp-group fp-submit" id="submit">
                                        <button class="fp-btn fp-btn-register">Lưu</button>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

<script type="text/javascript">
jQuery(function ($){
   
   $("#reset_password").change(function (){
       $(".password").toggleClass('hide');
   });
   
   $("#submit").click(function (){
       if($("#reset_password").is(':checked')){
           if($("#new_password").val()!=$("#confirm_new_password").val()){
               alert("password mới chưa trùng khớp.");
               return;
           }
           error=false;
           $.ajax({
                url:'<?php echo $this->baseUrl();?>/default/account/checkpassword',
                data: {'password':$("#old_password").val()},                         
                type: 'post',
                async: false,
                success: function(php_script_response){
                    if($.trim(php_script_response)=='sai'){
                        alert("password cũ không chính xác. Vui lòng nhập lại.");
                        error=true;
                    }
                }
            });
            if(!error){
                $("#change_info").attr('onsubmit','return true').submit();
            }
       }
       else{
           $("#change_info").attr('onsubmit','return true').submit();
       }
   });
});
</script>