<div class="page-content page-option login-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form-page form-login">
                    <div class="fp-heading">
                        <div class="fp-tit">ĐĂNG NHẬP</div>
                        <div class="fp-extra">Đăng nhập để bắt đầu đăng tin của bạn ngay</div>
                    </div>
                    <div class="fp-content">
                        <!-- Fp Group -->
                        <div class="fp-group">
                            <div class="fp-label fp-label-require">SỐ ĐIỆN THOẠI<span class="s-star">*</span></div>
                            <div class="fp-input fp-textbox">
                                <input type="text" class="fp-control" placeholder="Nhập số điện thoại">
                            </div>
                        </div>
                        <!-- End Fp Group -->
                        <!-- Fp Group -->
                        <div class="fp-group">
                            <div class="fp-label fp-label-require">MẬT KHẨU<span class="s-star">*</span></div>
                            <div class="fp-input fp-textbox">
                                <input type="password" class="fp-control" placeholder="Nhập mật khẩu">
                            </div>
                        </div>
                        <!-- End Fp Group -->
                        <div class="fp-submit">
                            <button class="fp-btn fp-btn-register">ĐĂNG NHẬP</button>
                        </div>
                        <div class="fp-desc">
                            <a href="#">Quên mật khẩu?</a>Bạn chưa có tài khoản?<a href="#">ĐĂNG KÝ</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>