<div class="page-content account-page category-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="pc-main">
                    <div class="pc-col pc-menu">
                        <ul>
                            <li><a href="#">Thông tin cá nhân</a></li>
                            <li><a href="#">Các tin đã đăng</a></li>
                            <li class="_current"><a href="#">Các tin đã hủy</a></li>
                        </ul>
                    </div>
                    <div class="pc-col pc-info">
                        <div class="page-option content-cate">
                            <div class="cate-list">
                                <!-- Wrap cate Add _ct_grid to show grid -->
                                <div id="cate_display" class="cate-wr"> 
                                    <!-- Item cate -->
                                    <div class="cate-item">
                                        <div class="cate-item-i">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png">
                                                <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title"><a href="#"><span class="tap-hot">Hot</span>Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                        <p>Đối tác</p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <a href="#" class="btn-green"><span>Khôi phục tin</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- End cate item -->
                                    <!-- Item cate -->
                                    <div class="cate-item">
                                        <div class="cate-item-i">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png">
                                                <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                        <p>Đối tác</p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <a href="#" class="btn-green"><span>Khôi phục tin</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- End cate item -->
                                    <!-- Item cate -->
                                    <div class="cate-item">
                                        <div class="cate-item-i">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png">
                                                <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                        <p>Đối tác</p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <a href="#" class="btn-green"><span>Khôi phục tin</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- End cate item -->
                                    <!-- Item cate -->
                                    <div class="cate-item">
                                        <div class="cate-item-i">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png">
                                                <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="p-opening cdes-main">ĐANG THI CÔNG</p>
                                                        <p>Đối tác</p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <a href="#" class="btn-green"><span>Khôi phục tin</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- End cate item -->
                                    <!-- Item cate -->
                                    <div class="cate-item">
                                        <div class="cate-item-i">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $this->baseUrl();?>/front_end/images/home/active-adults-bars-583392 2.png">
                                                <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                        <p>Đối tác</p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <a href="#" class="btn-green"><span>Khôi phục tin</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- End cate item -->
                                    <!-- Item cate -->
                                    <div class="cate-item">
                                        <div class="cate-item-i">
                                            <div class="cit-part cit-left">
                                                <img src="<?php echo $this->baseUrl();?>/front_end/images/category/cacti-gardening-grow-707194.png">
                                                <span class="cit-mark">Tổng đầu tư: 500 triệu</span>
                                            </div>
                                            <div class="cit-part cit-right">
                                                <div class="cit-title"><a href="#">Cần nghệ nhân làm tiểu cảnh hiện đại trong sân nhà tại Đà Nẵng</a></div>
                                                <div class="cit-desc">
                                                    <div class="cit-desc-l">
                                                        <p class="cdes-main">Thời gian thi công: 04/06/2018</p>
                                                        <p>Đối tác</p>
                                                    </div>
                                                    <div class="cit-desc-r">
                                                        <a href="#" class="btn-green"><span>Khôi phục tin</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- End cate item -->
                                </div>
                                <!-- End wrap cate -->
                                <!-- Cate paginate -->
                                <div class="ct-paginate cate-paginate">
                                    <ul>
                                        <li class="pg-prev"><a href="#" title="Trước đó"></a></li>
                                        <li><a href="#">1</a></li>
                                        <li class="active"><span>2</span></li>
                                        <li><span class="unlink">...</span></li>
                                        <li><a href="#">4</a></li>
                                        <li><a href="#">5</a></li>
                                        <li class="pg-next"><a href="#" title="Tiếp theo"></a></li>
                                    </ul>
                                </div>
                                <!-- End Cate paginate -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
