<style>
    .huy_dang_tin{
        cursor: pointer;
    }
</style>
<div class="page-content account-page category-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="pc-main">
                    <div class="pc-col pc-menu">
                        <ul>
                            <li><a href="<?php echo $this->baseUrl('/default/account/info');?>">Thông tin cá nhân</a></li>
                            <li class="_current"><a href="javascript:void(0)">Các tin đã đăng</a></li>
                            <li><a href="<?php echo $this->baseUrl('/default/account/duanchon');?>">Các dự án đã chọn</a></li>
                        </ul>
                    </div>
                    <div class="pc-col pc-info">
                        <div class="page-option content-cate">
                            <div class="cate-list">
                                <!-- Wrap cate Add _ct_grid to show grid -->
                                <div id="cate_display" class="cate-wr"> 
                                    <?php 
                                    $items=$this->items;
                                    if(is_array($items)&&count($items)>0){
                                        foreach ($items as $item){
                                            if($item['photo']==''){
                                                $item['photo']=$this->baseUrl(PHOTO_DEFAULT);
                                            }
                                            else{
                                                $item['photo']=$this->baseUrl("/uploads/".$item['photo']);
                                            }
                                            ?>
                                            <div class="cate-item">
                                                <div class="cate-item-i">
                                                    <div class="cit-part cit-left">
                                                        <a href="<?php echo $item['photo']; ?>" rel="prettyPhoto">
                                                            <img src="<?php echo $item['photo']; ?>">
                                                        </a>
                                                        <?php 
                                                        if($item['type_tin']=='du_an'){?>
                                                        <span class="cit-mark"> <?php echo $item['tong_dau_tu'];?></span>
                                                        <?php } ?>
                                                    </div>
                                                    <div class="cit-part cit-right">
                                                        <div class="cit-title">
                                                            <a href="<?php echo $this->baseUrl("/index/duandetail/id/".$item['id']);?>">
                                                                <?php 
                                                        if(isset($item['is_hot'])&&$item['is_hot']=='1'){?>
                                                        <img src="<?php echo $this->baseUrl(PHOTO_HOT);?>" style="width: 50px;height: 50px;display: block;min-width: 50px;"/>
                                                        <?php } ?>
                                                                <?php echo $item['title'];?>
                                                            </a>
                                                        </div>
                                                        <div class="cit-desc">
                                                            <div class="cit-desc-l">
                                                                <p class="cdes-main">
                                                                    <?php 
                                                                    if($item['type_tin']=='du_an'){
                                                                        echo 'Thời gian thi công: ';
                                                                    }
                                                                    else{
                                                                        echo 'Ngày đáp ứng dự án: ';
                                                                    }
                                                                    echo $item['ngay'];
                                                                    ?>
                                                                </p>
                                                                <?php 
                                                                    if($item['type_tin']=='nha_thau_thi_cong'){
                                                                        echo '<p>'.($item['phan_loai']=='1'?'Nhân viên':'Đối tác').'</p>';
                                                                    }
                                                                    ?>
                                                                <!--<p>Đối tác</p>-->
                                                            </div>
                                                            <!--tuetc-->
                                                            <div class="cit-desc-r">
                                                                <?php 
                                                                if($item['is_active']=='1'){
                                                                    echo 'Đã được duyệt';
                                                                }
                                                                else{
                                                                    echo 'Đang chờ duyệt';
                                                                }
                                                                echo '<br>';
                                                                if($item['status']==''||$item['status']=='1'){
                                                                ?>
                                                                <a class="btn-green huy_dang_tin"><span>Hủy đăng tin</span></a>
                                                                <?php 
                                                                }
                                                                ?>
                                                                <input type="hidden" value="<?php echo $item['id'];?>"/>
                                                                <input type="hidden" value="<?php echo 'tin_'.$item['type_tin'];?>"/>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                    <?php                                             
                                        }
                                    }
                                    ?>
                                </div>
                                <!-- End wrap cate -->
                                <form method="post" action="<?php echo $this->url(); ?>">
                                    <div class="ct-paginate cate-paginate">
                                            <?php if ($this->total > $this->limit) { ?>
                                                <?php echo $this->paginationControl($this->paginator, 'Sliding', array('_partials/paginator.phtml', 'default')); ?>
                                                <?php
                                            }
                                            ?>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(function ($){
    
   if($(".dt-cast ul li").length<=3){
       $(".dt-cast ul li").css('width','auto');
   } 
   $(".btn-green.huy_dang_tin").click(function (){
       if(confirm('Bạn có chắc hủy tin này không?')){
           $(this).parents('.cate-item').remove();
           id=$(this).next().val();
           table_name=$(this).next().next().val();
           
            $.ajax({
                url:'<?php echo $this->baseUrl();?>/news/canceltindadang',
                data: {'id':id,'table_name':table_name},                         
                type: 'post',
                async: true,
                success: function(php_script_response){
                }
            });
       }
        
   });
});
</script>
