<div class="page-content page-option register-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form-page form-register">
                    <div class="fp-heading">
                        <div class="fp-tit">ĐĂNG KÝ</div>
                        <div class="fp-extra">Tạo tài khoản và bắt đầu đăng tin của bạn ngay</div>
                    </div>
                    <div class="fp-content">
                        <!-- Fp Group -->
                        <div class="fp-group">
                            <div class="fp-label fp-label-require">CHỌN LOẠI HÌNH<span class="s-star">*</span></div>
                            <div class="fp-input fp-tab">
                                <!-- FP tab item -->
                                <div class="fp-tab-i">
                                    <div class="fp-tab-ii">
                                        <input type="radio" name="select_loaihinh" class="hd-check-tab">
                                        <div class="fp-tab-select">
                                            Nhân viên
                                            <span class="fp-tab-check"></span>
                                        </div>
                                    </div>
                                </div>
                                <!-- End FP Tab Item -->
                                <!-- FP tab item -->
                                <div class="fp-tab-i">
                                    <div class="fp-tab-ii">
                                        <input type="radio" name="select_loaihinh" class="hd-check-tab">
                                        <div class="fp-tab-select">
                                            Đối tác
                                            <span class="fp-tab-check"></span>
                                        </div>
                                    </div>
                                </div>
                                <!-- End FP Tab Item -->
                                <!-- FP tab item -->
                                <div class="fp-tab-i">
                                    <div class="fp-tab-ii">
                                        <input type="radio" name="select_loaihinh" class="hd-check-tab">
                                        <div class="fp-tab-select">
                                            Cá nhân
                                            <span class="fp-tab-check"></span>
                                        </div>
                                    </div>
                                </div>
                                <!-- End FP Tab Item -->
                            </div>
                        </div>
                        <!-- End Fp Group -->
                        <!-- Fp Group -->
                        <div class="fp-group fp-error">
                            <div class="fp-label fp-label-require">SỐ ĐIỆN THOẠI<span class="s-star">*</span></div>
                            <div class="fp-input fp-textbox">
                                <input type="text" class="fp-control" placeholder="Nhập số điện thoại">
                                <span class="s-error">Số điện thoại đã sử dụng</span>
                            </div>
                        </div>
                        <!-- End Fp Group -->
                        <!-- Fp Group -->
                        <div class="fp-group">
                            <div class="fp-label fp-label-require">MẬT KHẨU<span class="s-star">*</span></div>
                            <div class="fp-input fp-textbox">
                                <input type="password" class="fp-control" placeholder="Nhập mật khẩu">
                                <span class="fp-btn-hide"></span>
                            </div>
                        </div>
                        <!-- End Fp Group -->
                        <!-- Fp Group -->
                        <div class="fp-group">
                            <div class="fp-label fp-label-require">NHẬP LẠI MẬT KHẨU<span class="s-star">*</span></div>
                            <div class="fp-input fp-textbox">
                                <input type="password" class="fp-control" placeholder="Nhập mật khẩu">

                            </div>
                        </div>
                        <!-- End Fp Group -->
                        <div class="fp-submit">
                            <button class="fp-btn fp-btn-register">ĐĂNG KÝ</button>
                        </div>
                        <div class="fp-desc">
                            Bạn đã có tài khoản?<a href="#">ĐĂNG NHẬP</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
