<?php
echo $this->doctype();
?>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html;charset=utf-8;" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-2.0.3.js"></script>
        <!--bootstrap-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
              integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
                crossorigin="anonymous"></script> 
        <!--end bootstrap-->
        <!--menu-->
        <link href="<?php echo $this->baseUrl('/css/menu/menu.css'); ?>?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>" media="screen" rel="stylesheet" type="text/css" />				 
        <!--end menu-->  
        <!-- top bottom-->
<!--        <link href="<?php echo $this->baseUrl(); ?>/css/top_bottom.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/css/style.css" rel="stylesheet" type="text/css"/>-->
        <!--end layout--> 

        <link rel="stylesheet" href="<?php echo $this->baseUrl('/jquery-ui-1.10.3/themes/smoothness/jquery-ui.css'); ?>" type="text/css"/>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/jquery-ui.js"></script>          

        <style>
        
        
            form label:hover{
                background-color: #cccccc;
            }
            form label{
                cursor: pointer;
            }


        </style>
        
        <script type="text/javascript">
            $('body').on("beforeunload", function() { 
                $.ajax({
                   async: false,
                   url:'<?php echo $this->baseUrl('/'.Zend_Controller_Front::getInstance()->getRequest()->getModuleName().'/index/logout'); ?>'
                });
            });
        </script>

    </head>
    <body style="background:#f0f0f0;">

        <?php echo $this->render('admin/dialog.phtml'); ?>
        <div class="container">
            <div class="row" style="padding-top: 30px;height: 100px;background-repeat: no-repeat;background-size: 100% 100%;margin-bottom: 20px;margin-top: 20px;">
                <div class="col-lg-3 col-md-3">
                    &nbsp;
                </div>
                <div class="col-lg-5 col-md-5">
                    <div class="row" style="font-size: 30px;line-height: 1.3;text-align: center;color: #c1976c;font-family: serif;padding-top: 0;">
                        <div class="col-lg-12 col-md-12">Quản lý hệ thống</div>
                    </div>  
                </div>
                <div class="col-lg-4 col-md-4">
                        <?php 
                            echo $this->render('admin/auth.phtml'); 
                        ?>
                </div>
            </div>
            <div class="row" style="margin-bottom: 20px;">
                <?php echo $this->render('admin/menu.phtml'); ?>
            </div>

            <?php 
            $bg=$this->bg;
            if($bg!=''){
                $bg='background-image: url('.$this->baseUrl($bg).');background-size: cover;-webkit-background-size: cover;background-repeat: no-repeat;';
            }
            else{
                $bg='background: white;';
            }
            ?>
            <div class="row" id="container" style="padding: 20px;min-height: 500px;<?php echo $bg;?>">
                <?php echo $this->layout()->content; ?>     
            </div>
            
            <div class="row" style="color:white;background-color: #c1976c;margin-top: 30px;margin-bottom: 30px;">	
                <div class="col-lg-12 col-md-12" style="text-align: center;">
                    Copyright....
                </div>
            </div>


        </div><!-- /.container -->
    </body>
</html>