<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <?php echo $this->headTitle(); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&amp;subset=vietnamese" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/front_end/css/vendor.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/front_end/css/style.css?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>">
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-2.0.3.js"></script>
    
        
    </head>
    <body>
        <script src="https://sp.zalo.me/plugins/sdk.js"></script>
        <div id="app">
            <div id="sec1" class="main-wrapper <?php if(($this->action=='index'||$this->action=='search')&&$this->controller=='index') echo 'layout-3'; else echo 'index';?>">
                <!-- Start Top  -->
                <div class="top">
                    <div class="container">
                        <?php 
                        echo $this->render('index/top.phtml');
                        ?>
                    </div>
                </div>
                <!-- End Top -->
                <!-- Start Search -->
            <?php 
            if($this->action=='index'||$this->action=='search'||$this->action=='searchnhathau'||$this->action=='duandetail'||$this->action=='nhathauthicongdetail'){
                if($this->action=='searchnhathau'||$this->action=='nhathauthicongdetail'){
                    $action='searchnhathau';
                }
                else{
                    $action='search';
                }
                ?>
                <div class="top-search">
                    <div class="container" style="position: relative;">
                        <div class="top-search-c top-search-la3">   
                            <div class="row">
                                <div class="col col-md-12">
                                    <div class="search-block">
                                        <form id="search" action="<?php echo $this->baseUrl('/index/'.$action);?>" method="GET">
                                            <?php 
                                            echo $this->render('index/formsearch.phtml'); 
                                            ?>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php 
                    if($this->action=='index'||$this->action=='search'){
                        echo $this->render('index/dichvuhaumai.phtml');
                    }
                    ?>
                </div>
            <?php } 
            else if($this->action=='duan'||$this->action=='dichvuhaumai'||$this->action=='nhathauthicong'){
                if($this->action=='nhathauthicong'){
                    $action='searchnhathau';
                }
                else{
                    $action='search';
                }
                ?>
                <div class="top-search">
                    <div class="top-search-c" style="max-height: 1000px;">
                        <div class="container">
                            <div class="row">
                                <div class="col col-md-12">
                                    <div class="search-block">
                                        <form id="search" action="<?php echo $this->baseUrl('/index/'.$action);?>" method="GET">
                                            <?php echo $this->render('index/formsearch1.phtml'); ?>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php 
            }
            ?>
            
                <!-- End Search -->
                <ul class="breadcrumb show-sp">
                    <li><span>
                            <?php 
                            if($this->action=='duan'){
                                echo $this->muc;
                            }
                            else{
                                echo 'Tìm kiếm';
                            }
                            ?>
                        </span></li>
                    <li><span id="ten_danh_muc"><?php if(isset($this->tenMuc)) echo $this->tenMuc; else echo 'Tất cả danh mục';?></span></li>
                    <li><span id="ten_khu_vuc"><?php if(isset($this->tenKhuVuc)) echo $this->tenKhuVuc; else echo 'Khu vực';?></span></li>
                </ul>
                <!-- home page -->
                <?php echo $this->layout()->content; ?>
                <!-- End home page -->
                <div class="container">
                    <ul class="fix-share">
                        <?php echo $this->render('index/share.phtml'); ?>
                    </ul>  
                </div>     
                <!-- footer -->
                <footer class="footer">
                    <?php echo $this->render('index/footer.phtml'); ?>
                </footer>
                <!-- End footer -->
            </div>
        </div>
        <!-- Mobile menu -->
        <div class="mobile-menu">
            <!-- End top mobile menu -->
            <div class="mb-over">
                <!-- Link menu mobile -->
                <div class="mb-menu-link">
                    <div class="mb-menu-wr">
                        <ul>
                            <li>
                                <a href="/"><span><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/home.png" alt=""></span>VỀ TRANG CHỦ</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl();?>/default/news/step1"><span><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/pencil-dark.png" alt=""></span>ĐĂNG TIN CỦA BẠN</a>
                            </li>
                            <li>
                                <?php 
                                if ($this->isLogin) {
                                    ?>
                                    <a href="<?php echo $this->baseUrl();?>/default/account/duanchon"><span><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/bookmark-light.png" alt=""></span>DỰ ÁN ĐÃ CHỌN  <strong><?php echo $this->number_du_an_da_chon;?></strong></a>
                                <?php 
                                }  
                                else{?>
                                    <a style="visibility: hidden;" href="<?php echo $this->baseUrl();?>/default/account/duanchon"><span><img src="<?php echo $this->baseUrl();?>/front_end/images/layout/bookmark-light.png" alt=""></span>DỰ ÁN ĐÃ CHỌN  <strong>0</strong></a>
                                <?php 
                                }
                                ?>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- End moblie menu link -->
                
            </div>
        </div>
        <div id="dichvuhaumai_dialog" title="">
          
        </div>
        <!-- End Mobile menu -->
        <div class="go-top">
        </div>
        
        <div class="modal fade searchModal" id="searchItem" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Chọn danh mục</h4>
                    </div>
                    <div class="modal-body">
                        <ul class="parent-menu">
                            <li data-value="0"><a class="item-select"><span>Tất cả danh mục</span></a></li>
                            <?php 
                            if($this->action=='searchnhathau'||$this->action=='nhathauthicongdetail'||$this->action=='nhathauthicong'){
                                $du_an_cap_1s=Core_Db_Table::getDefaultAdapter()->fetchAll("SELECT nha_thau_thi_cong_cap_1.id,nha_thau_thi_cong_cap_1.name,nha_thau_thi_cong_cap_2.id as id1 from nha_thau_thi_cong_cap_1 LEFT JOIN nha_thau_thi_cong_cap_2 on nha_thau_thi_cong_cap_1.id=nha_thau_thi_cong_cap_2.nha_thau_thi_cong_cap_1_id GROUP BY nha_thau_thi_cong_cap_1.id");
                                foreach ($du_an_cap_1s as $dac1){
                                    if($dac1['id1']!=''){
                                        $class='next';
                                    }
                                    else{
                                        $class='item-select';
                                    }
                                    ?>
                                    <li data-value="<?php echo $dac1['id'];?>">
                                        <a class="<?php echo $class;?>"><span><?php echo $dac1['name'];?></span>
                                            <?php if($dac1['id1']!=''){ echo '<i class="fa fa-angle-right fa-5 pull-right"></i>';}?>
                                        </a>
                                    </li>
                                <?php                                                                         
                                }
                            }
                            else{
                                $du_an_cap_1s=Core_Db_Table::getDefaultAdapter()->fetchAll("SELECT du_an_cap_1.id,du_an_cap_1.name,du_an_cap_2.id as id1 from du_an_cap_1 LEFT JOIN du_an_cap_2 on du_an_cap_1.id=du_an_cap_2.du_an_cap_1_id GROUP BY du_an_cap_1.id");
                                foreach ($du_an_cap_1s as $dac1){
                                    if($dac1['id1']!=''){
                                        $class='next';
                                    }
                                    else{
                                        $class='item-select';
                                    }
                                    ?>
                                    <li data-value="<?php echo $dac1['id'];?>">
                                        <a class="<?php echo $class;?>"><span><?php echo $dac1['name'];?></span>
                                            <?php if($dac1['id1']!=''){ echo '<i class="fa fa-angle-right fa-5 pull-right"></i>';}?>
                                        </a>
                                    </li>
                                <?php                                                                         
                                }
                            }
                            ?>
                        </ul>
                        <!-- sub menu -->
                        <div class="sub-menu" style="display: none;">
                            <ul>
                                <?php 
                                if($this->action=='searchnhathau'||$this->action=='nhathauthicongdetail'||$this->action=='nhathauthicong'){
                                    foreach ($du_an_cap_1s as $dac1){?>
    <!--                                    <li class="<?php echo $dac1['id'];?>" data-value="<?php echo $dac1['id'];?>"><a class="item-select"><span>Tất cả</span>
                                            </a>
                                        </li>-->
                                    <?php                                                                         
                                    }
                                    ?>
                                    <?php 
                                    $du_an_cap_2s=Core_Db_Table::getDefaultAdapter()->fetchAll("SELECT nha_thau_thi_cong_cap_2.nha_thau_thi_cong_cap_1_id,nha_thau_thi_cong_cap_2.id,nha_thau_thi_cong_cap_2.name,nha_thau_thi_cong_cap_3.id as id1 from nha_thau_thi_cong_cap_2 LEFT JOIN nha_thau_thi_cong_cap_3 on nha_thau_thi_cong_cap_2.id=nha_thau_thi_cong_cap_3.nha_thau_thi_cong_cap_2_id GROUP BY nha_thau_thi_cong_cap_2.id");
                                    foreach ($du_an_cap_2s as $dac2){
                                        if($dac2['id1']!=''){
                                            $class='next sub-next';
                                        }
                                        else{
                                            $class='item-select';
                                        }
                                        ?>
                                        <li class="<?php echo $dac2['nha_thau_thi_cong_cap_1_id'];?>" data-value="<?php echo $dac2['nha_thau_thi_cong_cap_1_id'].'_'.$dac2['id'];?>"><a class="<?php echo $class;?>"><span><?php echo $dac2['name'];?></span>
                                                <?php if($dac2['id1']!=''){ echo '<i class="fa fa-angle-right fa-5 pull-right"></i>';}?>
                                            </a>
                                        </li>
                                    <?php                                                                         
                                    }
                                }
                                else{
                                    foreach ($du_an_cap_1s as $dac1){?>
    <!--                                    <li class="<?php echo $dac1['id'];?>" data-value="<?php echo $dac1['id'];?>"><a class="item-select"><span>Tất cả</span>
                                            </a>
                                        </li>-->
                                    <?php                                                                         
                                    }
                                    ?>
                                    <?php 
                                    $du_an_cap_2s=Core_Db_Table::getDefaultAdapter()->fetchAll("SELECT du_an_cap_2.du_an_cap_1_id,du_an_cap_2.id,du_an_cap_2.name,du_an_cap_3.id as id1 from du_an_cap_2 LEFT JOIN du_an_cap_3 on du_an_cap_2.id=du_an_cap_3.du_an_cap_2_id GROUP BY du_an_cap_2.id");
                                    foreach ($du_an_cap_2s as $dac2){
                                        if($dac2['id1']!=''){
                                            $class='next sub-next';
                                        }
                                        else{
                                            $class='item-select';
                                        }
                                        ?>
                                        <li class="<?php echo $dac2['du_an_cap_1_id'];?>" data-value="<?php echo $dac2['du_an_cap_1_id'].'_'.$dac2['id'];?>"><a class="<?php echo $class;?>"><span><?php echo $dac2['name'];?></span>
                                                <?php if($dac2['id1']!=''){ echo '<i class="fa fa-angle-right fa-5 pull-right"></i>';}?>
                                            </a>
                                        </li>
                                    <?php                                                                         
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                        <!-- sub sub menu -->
                        <div class="sub-menu-s" style="display: none;">
                            <ul>
                                <?php 
                                if($this->action=='searchnhathau'||$this->action=='nhathauthicongdetail'||$this->action=='nhathauthicong'){
                                    foreach ($du_an_cap_2s as $dac2){?>
    <!--                                    <li data-value="<?php echo $dac2['id'];?>" class="<?php echo $dac2['id'];?>"><a class="item-select"><span>Tất cả</span>
                                            </a>
                                        </li>-->
                                    <?php                                                                         
                                    }
                                    ?>
                                    <?php 
                                    $du_an_cap_3s=Core_Db_Table::getDefaultAdapter()->fetchAll("select nha_thau_thi_cong_cap_3.nha_thau_thi_cong_cap_2_id,nha_thau_thi_cong_cap_3.id,nha_thau_thi_cong_cap_3.name,nha_thau_thi_cong_cap_2.nha_thau_thi_cong_cap_1_id from nha_thau_thi_cong_cap_3 join nha_thau_thi_cong_cap_2 on nha_thau_thi_cong_cap_2.id=nha_thau_thi_cong_cap_3.nha_thau_thi_cong_cap_2_id");
                                    foreach ($du_an_cap_3s as $dac3){?>
                                        <li class="<?php echo $dac3['nha_thau_thi_cong_cap_2_id'];?>" data-value="<?php echo $dac3['nha_thau_thi_cong_cap_1_id'].'_'.$dac3['nha_thau_thi_cong_cap_2_id'].'_'.$dac3['id'];?>"><a class="item-select"><span><?php echo $dac3['name'];?></span>
                                            </a>
                                        </li>
                                    <?php                                                                         
                                    }
                                }
                                else{
                                    foreach ($du_an_cap_2s as $dac2){?>
    <!--                                    <li data-value="<?php echo $dac2['id'];?>" class="<?php echo $dac2['id'];?>"><a class="item-select"><span>Tất cả</span>
                                            </a>
                                        </li>-->
                                    <?php                                                                         
                                    }
                                    ?>
                                    <?php 
                                    $du_an_cap_3s=Core_Db_Table::getDefaultAdapter()->fetchAll("select du_an_cap_3.du_an_cap_2_id,du_an_cap_3.id,du_an_cap_3.name,du_an_cap_2.du_an_cap_1_id from du_an_cap_3 join du_an_cap_2 on du_an_cap_2.id=du_an_cap_3.du_an_cap_2_id");
                                    foreach ($du_an_cap_3s as $dac3){?>
                                        <li class="<?php echo $dac3['du_an_cap_2_id'];?>" data-value="<?php echo $dac3['du_an_cap_1_id'].'_'.$dac3['du_an_cap_2_id'].'_'.$dac3['id'];?>"><a class="item-select"><span><?php echo $dac3['name'];?></span>
                                            </a>
                                        </li>
                                    <?php                                                                         
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        
        <div class="modal fade searchModal" id="searchCity" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Chọn khu vực</h4>
                    </div>
                    <div class="modal-body">
                        <ul class="parent-menu">
                            <li data-value="0"><a class="item-select"><span>Tất cả</span></a></li>
                            <?php 
                            $city_cap_1s=Core_Db_Table::getDefaultAdapter()->fetchAll("select * from city_cap_1");
                            foreach ($city_cap_1s as $dac1){
                                if(true){
                                    $class='next';
                                }
                                else{
                                    $class='item-select';
                                }
                                ?>
                                <li data-value="<?php echo $dac1['id'];?>"><a class="<?php echo $class;?>"><span><?php echo $dac1['name'];?></span>
                                        <?php if(true){ echo '<i class="fa fa-angle-right fa-5 pull-right"></i>';}?>
                                    </a></li>
                            <?php                                                                         
                            }
                            ?>
                        </ul>
                        <!-- sub menu -->
                        <div class="sub-menu" style="display: none;">
                            <ul>
                                <?php 
                                foreach ($city_cap_1s as $dac1){?>
                                    <!--<li class="<?php echo $dac1['id'];?>" data-value="<?php echo $dac1['id'];?>"><a class="item-select"><span>Tất cả</span></a></li>-->
                                <?php                                                                         
                                }
                                ?>
                                <?php 
                                $city_cap_2s=Core_Db_Table::getDefaultAdapter()->fetchAll("select * from city_cap_2");
                                foreach ($city_cap_2s as $dac2){?>
                                    <li class="<?php echo $dac2['city_cap_1_id'];?>" data-value="<?php echo $dac2['city_cap_1_id'].'_'.$dac2['id'];?>"><a class="item-select"><span><?php echo $dac2['name'];?></span></a></li>
                                <?php                                                                         
                                }
                                ?>
                                
                            </ul>
                        </div>

                    </div>
                </div>

            </div>
        </div>
        
        
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/jquery-ui-1.10.3/themes/smoothness/jquery-ui.css'); ?>" type="text/css"/>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/jquery-ui.js"></script>  
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>        
        <script type="text/javascript">
            function genericSocialShare(url){
                window.open(url,'sharer','toolbar=0,status=0,width=648,height=395');
                return true;
            }
            jQuery(function ($){
                // show submenu next
                $(".modal-body ul li a.next").click(function () {
                    if ($(this).hasClass("sub-next")) {
                        $(".pull-left").addClass('back-parent');
                        $(".sub-menu-s").show();
                        $(".sub-menu").hide();
                    } else {
                        $("<div class='pull-left'><i class='fa fa-arrow-left'></i></div>").insertBefore("h4");
                        $(".parent-menu").hide();
                        $(".sub-menu").show();
                    }
                });
                // show parentmenu
                $(document).on('click', '.pull-left', function () {
                    if ($(this).hasClass("back-parent")) {
                        $(".pull-left").removeClass('back-parent');
                        $(".sub-menu-s").hide();
                        $(".sub-menu").show();
                    } else {
                        $(".parent-menu").show();
                        $(".sub-menu").hide();
                    }
                });
                // select item search
                $(document).on('click', '.item-select', function () {
                    var data = $(this).find("span").text();

                    if ($('#searchItem').hasClass('in')) {
                        $('#selectItem').text(data);
                    } else
                    if ($('#searchCity').hasClass('in')) {
                        $('#selectCity').text(data);
                    }
                    $('.searchModal').modal('hide');
                });
                $('.searchModal').on('hidden.bs.modal', function (e) {
                    $(".modal-body ul").show();
                    $(".modal-body div").hide();
                    $(".pull-left").remove();
                });
                
                $(".dich_vu_hau_mai").css('cursor','pointer');
                dialog=$( "#dichvuhaumai_dialog" ).dialog({
                  autoOpen: false,
                  show: {
                    effect: "blind",
                    duration: 1000
                  },
                  hide: {
                    effect: "explode",
                    duration: 1000
                  },
                  width: 500,
                  height: 400
                });
                
                $(".dich_vu_hau_mai").click(function (){
                   if($(this).hasClass('is_to_roi')){
                       var id=$(this).attr('id');
                       $.ajax({
                            url:'<?php echo $this->baseUrl();?>/default/index/gettoroi/id/'+id,
                            success: function(data){
                                dialog.dialog( "open" );
                                $("#dichvuhaumai_dialog").html(data);
                            }
                        });
                   }
                   else{
                       window.location='<?php echo $this->baseUrl('index/dichvuhaumai/id/');?>'+$(this).attr('id');
                   }
                });
                
                $('.ratings_stars').hover(
                    function() {
                        $(this).prevAll().andSelf().addClass('ratings_hover');
                    },
                    function() {
                        $(this).prevAll().andSelf().removeClass('ratings_hover');
                    }
                );
                $('.ratings_stars').click(function(){
                    <?php 
                    if(!$this->isLogin){?> 
                        alert("Vui lòng đăng nhập trước!");
                        return;
                    <?php 
                    }
                    ?>
                    var values =  $(this).find("input").val();
                    var tinID=$(this).parent().attr('class').replace("vote id_","");
                    var type=$(this).parent().attr('data-type');
                    $.ajax({
                        url:'<?php echo $this->baseUrl();?>/default/index/vote/tin_id/'+tinID+'/value/'+values+'/type/'+type,
                        success: function(data){
                        }
                    });
                    if ($(this).hasClass('ratings_over')) {
                        $('.ratings_stars').removeClass('ratings_over');
                        $(this).prevAll().andSelf().addClass('ratings_over');
                    } else {
                        $(this).prevAll().andSelf().addClass('ratings_over');
                    }
                });
            });
        </script>
        <script src="<?php echo $this->baseUrl();?>/front_end/js/script.js?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>"></script>

  
    </body>

</html>
