<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/js/jqwidgets/styles/jqx.base.css" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/demos.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxcore.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxbuttons.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxscrollbar.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxpanel.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxtree.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxcheckbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jqwidgets/jqxmenu.js"></script>
<script type="text/javascript">
    var level,id,photo='',name_show='',is_show_at_home_page='0';
    var contextMenuAll,contextMenu,contextMenuRoot;
</script>
<?php echo $this->render('common/tree_functions_js_city.phtml'); ?>
