<?php 
$items = $this->items;
?>

<style>
    .center{
        text-align:left;
    }

    table{
        width:100%;
        max-width:1600px;
        border-right:1px solid #999;
    }
    tr.show{
        background: #c8cedd;
    }

    td{
        text-indent:5px;
        color:#444;
        border-bottom:1px solid #bbb;
        border-left:1px solid #bbb;
    }

    td.left{
        border-left:1px solid #2e638e;
    }

    td.right{
        border-right:1px solid #2e638e;
    }

    td.bottom{
        border-bottom:1px solid #2e638e;
    }
    
    .quangcao td,th{
        text-align: center;
    }

    .grip{
        width:20px;
        height:15px;
        margin-top:-3px;
        background-image:url('<?php echo $this->baseUrl(); ?>/images/grip.png');
        margin-left:-5px;
        position:relative;
        z-index:88;
        cursor:e-resize;
    }

    .grip:hover{
        background-position-x:-20px;
    }

    .JCLRLastGrip .grip{
        background-position-y:-18px;
        left:-2px;
    }

    .dragging .grip{
        background-position-x:-40px;
    }

    .sampleText{
        position:relative;
        width:100%;
    }

    .dotted{
        background-image:url('<?php echo $this->baseUrl(); ?>/images/dotted.png');
        background-repeat:repeat-y;
    }
    
    .is_hien_thi{
        background: #c8cedd;
    }
    
    .vote {
        display: inline-block;
        text-align: center;
    }
    .ratings_stars {
        background: url(<?php echo $this->baseUrl(); ?>/front_end/images/vote/start.png) no-repeat;
        float:      left;
        height:     30px;
        padding:    0;
        width:      32px;
        margin-right: 4px;
    }
    .ratings_over {
        background: url(<?php echo $this->baseUrl(); ?>/front_end/images/vote/start-active.png) no-repeat;
    }
    .ratings_hover {
        background: url(<?php echo $this->baseUrl(); ?>/front_end/images/vote/start-hover.png) no-repeat;
    }
</style>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min.js?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <link href="<?php echo $this->baseUrl('/css/form_search.css'); ?>?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>" media="screen" rel="stylesheet" type="text/css" />				 
    <script src="<?php echo $this->baseUrl(); ?>/js/colResizable-1.6.js?<?php echo substr(str_shuffle(str_repeat($x='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', ceil(10/strlen($x)) )),1,10);?>"></script>

<div class="row-fluid">
    <table class="table table-bordered quangcao" id="nanopool-table" style="display: none;width: 100%;">
            <thead>
                <th style="width: 300px !important;">Mã tin</th>
                <th>Hình ảnh</th>
                <th>Phone</th>
                <th>Tựa đề</th>
                <th>Nội dung</th>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
            </thead>
            <tbody>
                <?php 
                    foreach ($items as $item){?>
                    <tr id="tin_<?php echo $item['id'];?>"<?php if($item['allow_show_quang_cao']=='1') echo ' class="is_hien_thi"';?>>
                        <td style="width: 300px !important;">
                            <?php 
                            if($item['type_tin']=='du_an'){
                                echo 'DA';
                            }
                            else{
                                echo 'NT';
                            }
                            echo $item['id'];
                            echo '<br>';
                            echo 'Số người xem: '.$item['so_luot_xem'];
                            echo '<br>';
                            $vote=$item['vote'];
                            $temp= explode(".", $vote);
                            if(count($temp)==2){
                                if("0.".$temp[1]>=0.5){
                                    $vote=$temp[0]+1;
                                }
                                else{
                                    $vote=$temp[0];
                                }
                            }
                            ?>
                            <div class="vote">
                                <?php 
                                for($i=0;$i<5;$i++){
                                    if($i<$vote){
                                        echo '<div class="star_3 ratings_stars ratings_over ratings_hover"></div>';
                                    } 
                                    else{
                                        echo '<div class="star_1 ratings_stars"></div>';
                                    }
                                }
                                ?>
                            </div>
                        </td>
                        <td style="width: 10%;">
                            <?php if(trim($item['photo'])!=""){?>
                                <img style="width: 100%;height: auto;" src="<?php echo $this->baseUrl("/uploads/".$item['photo']);?>"/>
                             <?php }
                             else{?>
                                 <img style="width: 100%;height: auto;" src="<?php echo $this->baseUrl(PHOTO_DEFAULT);?>"/>
                             <?php 
                             }
                             ?>
                        </td>
                        <td>
                            <?php echo $item['phone'];?>
                        </td>
                        <td>
                            <?php echo $item['title'];?>
                        </td>
                        <td>
                            <?php echo $item['content'];?>
                        </td>
                        <td>
                            <?php echo $item['type_tin_text'];?>
                        </td>
                        
                        
                        <td>
                            <?php 
                            if($item['allow_show_quang_cao']=='1'){
                            ?>
                            <button class="cancel_show">Hủy hiển thị</button>
                            <?php 
                            }
                            else {?> 
                            <button class="allow_show">Cho hiển thị</button>
                            <?php 
                            }
                            ?>
                            <br>
                            <a target="_blank" href="<?php echo $this->baseUrl("index/".($item['type_tin']=='du_an'?'duandetail':'nhathauthicongdetail')."/id/".$item['id']);?>">Xem chi tiết</a>
                        </td>
                        
                    </tr>
                    <?php 
                    }
                ?>
            </tbody>
        </table>

</div>
<script>
        
    $(window).load(function() {
          $('#nanopool-table').show();
          $('#nanopool-table').DataTable();
          $('#nanopool-table_filter').find('input').eq(0).css('width','270px');
          $('#nanopool-table td').css('text-align','center');
          <?php 
          if(is_array($items)&&count($items)>0){?>
          $("table").colResizable({
                liveDrag:true, 
                gripInnerHtml:"<div class='grip'></div>", 
                draggingClass:"dragging", 
                resizeMode:'overflow',//'fit'
                postbackSafe:true,
                partialRefresh:true
          });
          <?php 
          }
          ?>
    });
    
    jQuery(function ($){
        $( "body" ).delegate( ".allow_show", "click", function() {
          
          var id=$(this).parent().parent().attr('id');
          id=id.replace("tin_","");
          if($.trim($(this).parent().parent().find('td').eq(4).html())=='Dự án'){
              table_name='tin_du_an';
          }
          else{
              table_name='tin_nha_thau_thi_cong';
          }
          var node=$(this);
            $.ajax({
                url:'<?php echo $this->baseUrl();?>/admin/quangcao/show',
                data: {'id':id,'table_name':table_name},                         
                type: 'post',
                async: false,
                success: function(php_script_response){
                    if($.trim(php_script_response)=='ok'){
                        $(node).toggleClass( "allow_show" );
                      $(node).toggleClass( "cancel_show" );
                      $(node).html("Hủy hiển thị");
                      $(node).parent().parent().toggleClass('is_hien_thi');
                    }
                      
                }
            });
        });
        
        $( "body" ).delegate( ".cancel_show", "click", function() {
          
          var id=$(this).parent().parent().attr('id');
          id=id.replace("tin_","");
          if($.trim($(this).parent().parent().find('td').eq(4).html())=='Dự án'){
              table_name='tin_du_an';
          }
          else{
              table_name='tin_nha_thau_thi_cong';
          }
          var node=$(this);
            $.ajax({
                url:'<?php echo $this->baseUrl();?>/admin/quangcao/hide',
                data: {'id':id,'table_name':table_name},                         
                type: 'post',
                async: false,
                success: function(php_script_response){
                    if($.trim(php_script_response)=='ok'){
                        $(node).toggleClass( "allow_show" );
                      $(node).toggleClass( "cancel_show" );
                      $(node).html("Cho hiển thị");
                      $(node).parent().parent().toggleClass('is_hien_thi');
                    }
                      
                }
            });
        });
    });
</script>
